hostConfiguration:
  storage:
    disks:
      - id: os
        device: /dev/disk/by-path/pci-0000:00:1f.2-ata-2
        partitionTableType: gpt
        partitions:
          - id: esp
            type: esp
            size: 1G
          - id: boot-a
            type: xbootldr
            size: 200M
          - id: boot-b
            type: xbootldr
            size: 200M
          - id: root-a-1
            type: root
            size: 4G
          - id: root-b-1
            type: root
            size: 4G
          - id: root-a-2
            type: root
            size: 4G
          - id: root-b-2
            type: root
            size: 4G
          - id: root-hash-a-1
            type: root-verity
            size: 1G
          - id: root-hash-b-1
            type: root-verity
            size: 1G
          - id: root-hash-a-2
            type: root-verity
            size: 1G
          - id: root-hash-b-2
            type: root-verity
            size: 1G
          - id: home-a-e-1
            type: linux-generic
            size: 100M
          - id: home-a-e-2
            type: linux-generic
            size: 100M
          - id: home-b-e-1
            type: linux-generic
            size: 100M
          - id: home-b-e-2
            type: linux-generic
            size: 100M
          - id: trident-overlay-a-1
            type: linux-generic
            size: 100M
          - id: trident-overlay-b-1
            type: linux-generic
            size: 100M
          - id: trident-overlay-a-2
            type: linux-generic
            size: 100M
          - id: trident-overlay-b-2
            type: linux-generic
            size: 100M
          - id: trident
            type: linux-generic
            size: 100M
          - id: var
            type: linux-generic
            size: 1G
          - id: run
            type: linux-generic
            size: 1G
      - id: disk2
        device: /dev/disk/by-path/pci-0000:00:1f.2-ata-3
        partitionTableType: gpt
        partitions: []
    raid:
      software:
        - id: home-a-e
          name: home-a-e
          level: raid1
          devices:
            - home-a-e-1
            - home-a-e-2
          metadataVersion: "1.2"
        - id: home-b-e
          name: home-b-e
          level: raid1
          devices:
            - home-b-e-1
            - home-b-e-2
          metadataVersion: "1.2"
        - id: root-a
          name: root-a
          level: raid1
          devices:
            - root-a-1
            - root-a-2
          metadataVersion: "1.2"
        - id: root-b
          name: root-b
          level: raid1
          devices:
            - root-b-1
            - root-b-2
          metadataVersion: "1.2"
        - id: root-hash-a
          name: root-hash-a
          level: raid1
          devices:
            - root-hash-a-1
            - root-hash-a-2
          metadataVersion: "1.2"
        - id: root-hash-b
          name: root-hash-b
          level: raid1
          devices:
            - root-hash-b-1
            - root-hash-b-2
          metadataVersion: "1.2"
        - id: trident-overlay-a
          name: trident-overlay-a
          level: raid1
          devices:
            - trident-overlay-a-1
            - trident-overlay-a-2
          metadataVersion: "1.2"
        - id: trident-overlay-b
          name: trident-overlay-b
          level: raid1
          devices:
            - trident-overlay-b-1
            - trident-overlay-b-2
          metadataVersion: "1.2"
    # tracked by: https://dev.azure.com/mariner-org/ECF/_workitems/edit/7350
    # encryption:
    #   volumes:
    #     - id: home-a
    #       deviceName: home-a
    #       targetId: home-a-e
    #     - id: home-b
    #       deviceName: home-b
    #       targetId: home-b-e
    abUpdate:
      volumePairs:
        - id: boot
          volumeAId: boot-a
          volumeBId: boot-b
        - id: root
          volumeAId: root-a
          volumeBId: root-b
        - id: root-hash
          volumeAId: root-hash-a
          volumeBId: root-hash-b
        - id: trident-overlay
          volumeAId: trident-overlay-a
          volumeBId: trident-overlay-b
        - id: home
          volumeAId: home-a-e
          volumeBId: home-b-e
    mountPoints:
      - path: /boot/efi
        targetId: esp
        filesystem: vfat
        options: ["umask=0077"]
      - path: /boot
        targetId: boot
        filesystem: ext4
        options: ["defaults"]
      - path: /
        targetId: verity-root
        filesystem: ext4
        options: ["defaults", "ro"]
      - path: /var/lib/trident
        targetId: trident
        filesystem: ext4
        options: ["defaults"]
      - path: /var/lib/trident-overlay
        targetId: trident-overlay
        filesystem: ext4
        options: ["defaults"]
      - path: /home
        targetId: home
        filesystem: ext4
        options: ["defaults"]
      - path: /var
        targetId: var
        filesystem: ext4
        options: ["defaults"]
      - path: /run
        targetId: run
        filesystem: ext4
        options: ["defaults"]
    images:
      - url: http://NETLAUNCH_HOST_ADDRESS/files/verity_esp.rawzst
        sha256: ignored
        format: raw-zst
        targetId: esp
      - url: http://NETLAUNCH_HOST_ADDRESS/files/verity_boot.rawzst
        sha256: ignored
        format: raw-zst
        targetId: boot
      - url: http://NETLAUNCH_HOST_ADDRESS/files/verity_root.rawzst
        sha256: ignored
        format: raw-zst
        targetId: root
      - url: http://NETLAUNCH_HOST_ADDRESS/files/verity_roothash.rawzst
        sha256: ignored
        format: raw-zst
        targetId: root-hash
      - url: http://NETLAUNCH_HOST_ADDRESS/files/verity_var.rawzst
        sha256: ignored
        format: raw-zst
        targetId: var
    verity:
      - id: verity-root
        deviceName: root
        dataTargetId: root
        hashTargetId: root-hash
  trident:
    selfUpgrade: false
  os:
    network:
      ethernets:
        vmeths:
          match:
            name: enp*
          dhcp4: true
      version: 2
    users:
      - name: testing-user
        secondaryGroups: [wheel]
        sshPublicKeys: []
        sshMode: key-only
  scripts:
    postConfigure:
    - content: |
        mkdir -p /var/lib/trident-overlay/etc-rw/upper
        mkdir -p /var/lib/trident-overlay/etc-rw/work
      name: overlay
      servicingType:
      - clean-install
      - ab-update
    postProvision:
      - name: fail-on-the-first-run-to-force-rerun
        servicingType:
          - all
        interpreter: /usr/bin/python3
        content: |
          import sys
          import os.path
          if not os.path.isfile("/run/already-run"):
            f = open('/run/already-run', 'x')
            f.close()
            sys.exit(1)
