hostConfiguration:
  storage:
    disks:
      - id: os
        device: /dev/disk/by-path/pci-0000:00:1f.2-ata-2
        partitionTableType: gpt
        partitions:
          - id: esp
            type: esp
            size: 1G
          - id: root
            type: root
            size: 8G
      - id: disk2
        device: /dev/disk/by-path/pci-0000:00:1f.2-ata-3
        partitionTableType: gpt
        partitions: []
    mountPoints:
      - path: /boot/efi
        targetId: esp
        filesystem: vfat
        options: ["umask=0077"]
      - path: /
        targetId: root
        filesystem: ext4
        options: ["defaults"]
    images:
      - url: file:///trident_cdrom/data/esp.rawzst
        sha256: ignored
        format: raw-zst
        targetId: esp
      - url: file:///trident_cdrom/data/root.rawzst
        sha256: ignored
        format: raw-zst
        targetId: root
  network:
    ethernets:
      vmeths:
        match:
          name: enp*
        dhcp4: true
    version: 2
  management:
    selfUpgrade: false
  osconfig:
    users:
      - name: testing-user
        sshKeys: []
        sshMode: key-only
  scripts:
    postProvision:
      - name: detect-second-run
        servicingType:
          - all
        interpreter: /usr/bin/python3
        content: |
          import sys
          import os.path
          if not os.path.isfile("/already-run"):
            f = open('/already-run', 'x')
            f.close()
            sys.exit(1)
    postConfigure:
      - name: testing-privilege
        servicingType:
          - clean-install
        content: 'echo "testing-user ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/testing-user'
