parameters:
  - name: "feed"
    displayName: "Target feed to publish to"
    type: string
    default: ECF/Trident

  - name: "stageType"
    displayName: "Controls whether this is a pre-release or a CI run."
    type: string
    default: ci
    values:
      - ci
      - pre
      - rel

stages:
  - stage: Publishing
    dependsOn:
      - Trident
      - ${{ if eq(parameters.stageType, 'pre') }}:
          - DeploymentTesting
          - BaremetalDeploymentTesting
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main') )

    jobs:
      - job: Publishing
        displayName: Publish Trident RPMs and Provisioning OS Template ISO to Universal Packages
        pool:
          type: linux

        variables:
          - template: ../../feed-staging-vars.yml
          - name: ob_outputDirectory
            value: $(Build.SourcesDirectory)/build
          - name: "artifactSuffix"
            ${{ if eq(parameters.stageType, 'ci') }}:
              value: "${{ variables.stage_ci_suffix }}"
            ${{ if eq(parameters.stageType, 'pre') }}:
              value: "${{ variables.stage_pre_suffix }}"
            ${{ if eq(parameters.stageType, 'rel') }}:
              value: "${{ variables.stage_rel_suffix }}"

        steps:
          - script: echo $(Build.BuildNumber)
            displayName: "Print Trident Version"

          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: current
              patterns: |
                *.rpm
              targetPath: $(Pipeline.Workspace)/rpms
              artifactName: trident-binaries
            displayName: "Download Trident RPMs"

          - task: AzureCLI@2
            displayName: "Check if package version has already been published in the Feed."
            inputs:
              azureSubscription: CoreOS_ECF_Kubernetes_dev (b8a0db63-c5fa-4198-8e2a-f9d6ff52465e)
              scriptType: "bash"
              workingDirectory: $(Build.SourcesDirectory)
              scriptLocation: inlineScript
              inlineScript: |
                set -eux

                alreadyPublished=$(./scripts/get-packages.py --debug \
                    --package '${{ variables.rpmsPackageBaseName }}${{ variables.artifactSuffix }}' \
                    --version '$(Build.BuildNumber)' \
                    --action=exists)

                # Save variable to know if package needs to be published
                echo "##vso[task.setvariable variable=isVersionInFeed;]$alreadyPublished"

          - task: UniversalPackages@0
            displayName: "Publish rpms Universal Package"
            condition: and(succeeded(), eq(variables.isVersionInFeed, false))
            inputs:
              command: publish
              vstsFeedPublish: ${{ parameters.feed }}
              vstsFeedPackagePublish: "${{ variables.rpmsPackageBaseName }}${{ variables.artifactSuffix }}"
              publishDirectory: "$(Pipeline.Workspace)/rpms"
              versionPublish: $(Build.BuildNumber)
              versionOption: custom
