steps:
  - task: DownloadPipelineArtifact@2
    displayName: "Download base-image-config"
    inputs:
      buildType: current
      artifactName: base-image-config
      targetPath: /tmp/base-image-config

  - bash: |
      BASEIMG_BUILD_TYPE=$(jq -r .baseimgBuildType /tmp/base-image-config/baseimage.json)
      BASE_IMAGE_PIPELINE_BUILD_ID=$(jq -r .baseImagePipelineBuildId /tmp/base-image-config/baseimage.json)
      BASE_IMAGE_ARM64_PIPELINE_BUILD_ID=$(jq -r .baseImageArm64PipelineBuildId /tmp/base-image-config/baseimage.json)

      echo "BASEIMG_BUILD_TYPE = $(BASEIMG_BUILD_TYPE)"
      echo "BASE_IMAGE_PIPELINE_BUILD_ID = $(BASE_IMAGE_PIPELINE_BUILD_ID)"
      echo "BASE_IMAGE_ARM64_PIPELINE_BUILD_ID = $(BASE_IMAGE_ARM64_PIPELINE_BUILD_ID)"

      echo "##vso[task.setvariable variable=BASEIMG_BUILD_TYPE]$BASEIMG_BUILD_TYPE"
      echo "##vso[task.setvariable variable=BASE_IMAGE_PIPELINE_BUILD_ID]$BASE_IMAGE_PIPELINE_BUILD_ID"
      echo "##vso[task.setvariable variable=BASE_IMAGE_ARM64_PIPELINE_BUILD_ID]$BASE_IMAGE_ARM64_PIPELINE_BUILD_ID"
    displayName: "Read Base Image Config artifact into variables"
