parameters:
  - name: "hostRepository"
    displayName: "Repository containing COSI images"
    type: string
    default: regular

  - name: "containerRepository"
    displayName: "Repository containing COSI images"
    type: string
    default: regular

  - name: "registry"
    type: string
    default: maritimuspublic

stages:
  - stage: DeleteFromAcr
    displayName: Delete from ACR
    condition: always()
    dependsOn:
      - TridentTestImg_trident_testimage
      - TridentTestImg_trident_container_testimage
      - DeploymentTesting_host
      - DeploymentTesting_container

    jobs:
      - job: DeleteCosiFromAcr
        displayName: Delete COSI images from ${{ parameters.registry }} ACR
        pool:
          type: linux

        variables:
          - name: ob_outputDirectory
            value: $(Build.SourcesDirectory)/build

        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: maritimus-staging-eastus-cr-service-connection
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -eux

                # Login to ACR
                az acr login -n ${{ parameters.registry }}

                host_repository_name="${{ parameters.hostRepository }}"
                container_repository_name="${{ parameters.containerRepository }}"
                build_id="$(Build.BuildId)"

                # Delete repository with COSI images
                for i in {1..3}; do
                  tag="v${build_id}.${i}"

                  if az acr repository show --name ${{ parameters.registry }} --image ${host_repository_name}:${tag} &> /dev/null; then
                    echo "Deleting image ${host_repository_name}:${tag} from ACR ${{ parameters.registry }}"
                    az acr repository delete --name ${{ parameters.registry }} --image ${host_repository_name}:${tag} --yes
                  else
                    echo "Image ${host_repository_name}:${tag} not found in ACR ${{ parameters.registry }}."
                  fi

                  if az acr repository show --name ${{ parameters.registry }} --image ${container_repository_name}:${tag} &> /dev/null; then
                    echo "Deleting image ${container_repository_name}:${tag} from ACR ${{ parameters.registry }}"
                    az acr repository delete --name ${{ parameters.registry }} --image ${container_repository_name}:${tag} --yes
                  else
                    echo "Image ${container_repository_name}:${tag} not found in ACR ${{ parameters.registry }}."
                  fi
                done
            displayName: "Log into ACR and delete images by tag"
