parameters:
  - name: artifactName
    type: string

  - name: packageName
    type: string
    values:
      - rpms
      - usb-iso

  - name: "stageType"
    displayName: "Pipeline configuration type"
    type: string
    values:
      - pre
      - rel
      - full-validation
      - azl-validation

  - name: specificVersion
    type: string
    displayName: |
      Specific version of the package to download, leave empty to download latest
    default: ""

  - name: dependsOnStage
    type: string
    default: ''

  - name: targetArchitecture
    type: string
    values:
      - amd64
      - arm64

stages:
  - stage: GetTridentBinaries_${{ replace(parameters.packageName, '-', '_') }}_${{ parameters.targetArchitecture }}
    displayName: Download staged ${{ parameters.packageName }} (${{ parameters.targetArchitecture }}) for ${{ parameters.stageType }}
    ${{ if ne(parameters.dependsOnStage, '') }}:
      dependsOn: ${{ parameters.dependsOnStage }}

    jobs:
      - job: DownloadTrident_${{ parameters.targetArchitecture }}
        displayName: Download Trident
        pool:
          type: linux

        variables:
          # Control the name of the artifact where Trident binaries are stored
          - name: ob_artifactBaseName
            ${{ if eq(parameters.targetArchitecture, 'amd64') }}:
              value: ${{ parameters.artifactName }}
            ${{ else }}:
              value: ${{ parameters.artifactName }}-${{ parameters.targetArchitecture }}
          - name: ob_outputDirectory
            value: "/tmp/out"

          - template: ../../feed-staging-vars.yml

          # Set the download artifact suffix to be that of the *previous* stage
          - name: downloadArtifactSuffix
            ${{ if eq(parameters.stageType, 'rel') }}:
              value: ${{ variables.stage_pre_suffix }}
            ${{ else }}:
              value: ${{ variables.stage_ci_suffix }}

        steps:
          - template: ../common_tasks/checkout_trident.yml
          - template: ../common_tasks/download-universal-artifact.yml
            parameters:
              tridentSourceDirectory: $(TRIDENT_SOURCE_DIR)
              packageName: ${{ parameters.packageName }}${{ variables.downloadArtifactSuffix }}
              downloadLocation: $(ob_outputDirectory)
              outputVersionVariable: trident_version
              specificVersion: ${{ parameters.specificVersion }}

          - task: onebranch.pipeline.version@1
            displayName: "Set build number"
            inputs:
              system: "Custom"
              customVersion: $(trident_version)

          - ${{ if eq(parameters.packageName, 'rpms') }}:
            - script: sudo tdnf install -y p7zip p7zip-plugins zstd
              displayName: Install native dependencies to extract Trident binary
              retryCountOnTaskFailure: 3

            - script: ./scripts/extract-binary.sh $(ob_outputDirectory) $(ob_outputDirectory) ${{ parameters.targetArchitecture }}
              displayName: Extract Trident binary
              workingDirectory: $(TRIDENT_SOURCE_DIR)
