parameters:
  - name: label
    type: string
    displayName: "Label for the image"

  - name: labelPrefix
    type: string
    displayName: "Prefix for the image label"
    default: ""

  - name: makeTarget
    type: string
    displayName: "Make target for the image"
    default: ""

  - name: baseimgType
    displayName: Base Image Type
    type: string
    default: "baremetal"

  - name: baseimgAzlVersion
    displayName: Base Image AZL version
    type: string
    default: "3.0"

  - name: micBuildType
    displayName: MIC Build Type
    type: string
    values:
      - dev
      - preview
      - release
    default: release

  - name: micVersion
    displayName: MIC Version
    type: string
    default: "*.*.*"

  - name: useStagedSshKeys
    displayName: "Use staged SSH keys"
    type: boolean
    default: false

  - name: architecture
    displayName: Architecture for MIC
    type: string
    values:
      - arm64
      - amd64
    default: "amd64"

  - name: downloadGoTools
    displayName: "Download Go Tools"
    type: boolean
    default: false

  - name: dependsOnTrident
    displayName: "Requires Trident binaries"
    type: boolean
    default: true

  - name: clones
    displayName: "Number of clones to generate"
    type: number
    default: 1

  - name: dependsOnStage
    type: string
    default: ""

stages:
  - stage: TridentTestImg_${{ replace(parameters.makeTarget, '-', '_') }}
    displayName: "Build Image: ${{ parameters.makeTarget }}"
    dependsOn:
      - ${{ if ne(parameters.dependsOnStage, '') }}:
          - ${{ parameters.dependsOnStage }}
      - ${{ if parameters.dependsOnTrident }}:
          - GetTridentBinaries_rpms_amd64
      - ${{ if parameters.downloadGoTools }}:
          - ${{ if eq(parameters.architecture, 'arm64') }}:
              - BuildingTools_arm64
          - ${{ if eq(parameters.architecture, 'amd64') }}:
              - BuildingTools
      - PrepareSSHKeys
    jobs:
      - template: ./build-image-job.yml
        parameters:
          label: ${{ parameters.label }}
          labelPrefix: ${{ parameters.labelPrefix }}
          makeTarget: ${{ parameters.makeTarget }}
          baseimgType: ${{ parameters.baseimgType }}
          baseimgAzlVersion: ${{ parameters.baseimgAzlVersion }}
          micBuildType: ${{ parameters.micBuildType }}
          micVersion: ${{ parameters.micVersion }}
          useStagedSshKeys: ${{ parameters.useStagedSshKeys }}
          architecture: ${{ parameters.architecture }}
          downloadGoTools: ${{ parameters.downloadGoTools }}
          dependsOnTrident: ${{ parameters.dependsOnTrident }}
          clones: ${{ parameters.clones }}
