graph TD
A[servicingType: no-active-servicing\nservicingState: provisioned] --> |'stage' in 'allowedOperations'.\nReceived a valid HC|B[servicingType: ab-update\nservicingState: not-provisioned]
B --> |Staging failed|A
B --> |Staging succeeded|C[servicingType: ab-update\nservicingState: staged]
C --> |'finalize' in 'allowedOperations'.\nFinalizing succeeded|E[servicingType: ab-update\nservicingState: finalized]
C --> |'finalize' in 'allowedOperations'.\nFinalizing failed|A
C --> |'stage' in 'allowedOperations'.\nReceived a valid updated HC|B
E --> |Successfully rebooted into the updated runtime OS image|G[servicingType: no-active-servicing\nservicingState: provisioned]
E --> |Failed to reboot into the updated runtime OS image|D[servicingType: no-active-servicing\nservicingState: ab-update-failed]
D --> |'stage' in 'allowedOperations'.\nReceived a valid updated HC|B