graph TD
A[Provisioned] --> |Received a new valid HC & 'stage' in 'allowedOperations'|B[Staging]
B --> |Staging succeeded|C[Staged]
B --> |Staging failed|B
C --> |Received 'finalize' in 'allowedOperations'|E[Finalizing]
C --> |Received a new valid HC & 'stage' in 'allowedOperations'|B
E --> |Finalizing succeeded|F[Finalized]
E --> |Finalizing failed|B
F --> |Reboot into new OS image succeeded|A
F --> |Rollback into old OS occurred|D[CleanInstallFailed]
D --> |Received a new valid HC & 'stage' in 'allowedOperations'|B