graph TD
A[servicingType: no-active-servicing\nservicingState: not-provisioned] --> |'stage' in 'allowedOperations'.\nReceived a valid HC|B[servicingType: clean-install\nservicingState: not-provisioned]
B --> |Staging failed|A
B --> |Staging succeeded|C[servicingType: clean-install\nservicingState: staged]
C --> |'finalize' in 'allowedOperations'.\nFinalizing succeeded|E[servicingType: clean-install\nservicingState: finalized]
C --> |'finalize' in 'allowedOperations'.\nFinalizing failed|A
C --> |'stage' in 'allowedOperations'.\nReceived a valid updated HC|B
E --> |Successfully rebooted into the runtime OS image|G[servicingType: no-active-servicing\nservicingState: provisioned]
E --> |Failed to reboot into the runtime OS image|D[servicingType: no-active-servicing\nservicingState: clean-install-failed]
D --> |'stage' in 'allowedOperations'.\nReceived a valid updated HC|B