package screenshot

import (
	"bytes"
	"image/png"
	"testing"
)

// buildPpm produces a minimal binary PPM with the given header text and pixels.
func buildPpm(header string, pixels []byte) []byte {
	return append([]byte(header), pixels...)
}

func TestPpmToPngDecodesPixels(t *testing.T) {
	// 2x1 image: red pixel, then green.
	ppm := buildPpm("P6\n2 1\n255\n", []byte{0xFF, 0x00, 0x00, 0x00, 0xFF, 0x00})

	var out bytes.Buffer
	if err := PpmToPng(bytes.NewReader(ppm), &out); err != nil {
		t.Fatalf("PpmToPng: %v", err)
	}

	img, err := png.Decode(bytes.NewReader(out.Bytes()))
	if err != nil {
		t.Fatalf("output is not a valid PNG: %v", err)
	}

	if got := img.Bounds().Dx(); got != 2 {
		t.Errorf("width = %d, want 2", got)
	}
	if got := img.Bounds().Dy(); got != 1 {
		t.Errorf("height = %d, want 1", got)
	}

	r, g, b, a := img.At(0, 0).RGBA()
	if r>>8 != 0xFF || g>>8 != 0 || b>>8 != 0 || a>>8 != 0xFF {
		t.Errorf("pixel(0,0) = %d,%d,%d,%d; want opaque red", r>>8, g>>8, b>>8, a>>8)
	}
	r, g, b, _ = img.At(1, 0).RGBA()
	if r>>8 != 0 || g>>8 != 0xFF || b>>8 != 0 {
		t.Errorf("pixel(1,0) = %d,%d,%d; want green", r>>8, g>>8, b>>8)
	}
}

// A PPM header may carry comments between any two tokens, and may separate
// them with arbitrary whitespace.
func TestPpmToPngHandlesCommentsAndWhitespace(t *testing.T) {
	ppm := buildPpm("P6\n# generated by qemu\n  2   1\n# another comment\n255\n",
		[]byte{0x01, 0x02, 0x03, 0x04, 0x05, 0x06})

	var out bytes.Buffer
	if err := PpmToPng(bytes.NewReader(ppm), &out); err != nil {
		t.Fatalf("PpmToPng: %v", err)
	}
	img, err := png.Decode(bytes.NewReader(out.Bytes()))
	if err != nil {
		t.Fatalf("output is not a valid PNG: %v", err)
	}
	if r, g, b, _ := img.At(1, 0).RGBA(); r>>8 != 4 || g>>8 != 5 || b>>8 != 6 {
		t.Errorf("pixel(1,0) = %d,%d,%d; want 4,5,6", r>>8, g>>8, b>>8)
	}
}

func TestPpmToPngRejectsBadInput(t *testing.T) {
	for name, input := range map[string]string{
		"ascii P3 format":   "P3\n1 1\n255\n0 0 0\n",
		"empty":             "",
		"truncated pixels":  "P6\n2 2\n255\n\x00\x01",
		"non-numeric width": "P6\nx 1\n255\n\x00\x00\x00",
		"16-bit maxval":     "P6\n1 1\n65535\n\x00\x00\x00",
		"zero width":        "P6\n0 1\n255\n",
		// Dimensions large enough that width*height*3 wraps: without a bound
		// the multiply overflows to a small positive, make() succeeds, and the
		// pixel loop then indexes past the buffer and panics. These must be
		// rejected while reading the header instead.
		"dimensions overflow the pixel buffer": "P6\n4294967296 4294967296\n255\n",
		"dimension above the maximum":          "P6\n65537 1\n255\n",
	} {
		t.Run(name, func(t *testing.T) {
			var out bytes.Buffer
			if err := PpmToPng(bytes.NewReader([]byte(input)), &out); err == nil {
				t.Error("expected an error, got nil")
			}
		})
	}
}

// The capture path must not depend on the mime type libvirt reports, because
// go-libvirt cannot return it for a streamed call. These pin the sniffing.
func TestFormatMagicsAreDistinct(t *testing.T) {
	realPng := func() []byte {
		var buf bytes.Buffer
		if err := PpmToPng(bytes.NewReader(buildPpm("P6\n1 1\n255\n", []byte{1, 2, 3})), &buf); err != nil {
			t.Fatalf("PpmToPng: %v", err)
		}
		return buf.Bytes()
	}()

	if !bytes.HasPrefix(realPng, pngMagic) {
		t.Errorf("encoded PNG does not start with the PNG magic: %x", realPng[:8])
	}
	if bytes.HasPrefix(realPng, ppmMagic) {
		t.Error("PNG must not be mistaken for PPM")
	}
	if !bytes.HasPrefix([]byte("P6\n1 1\n255\n"), ppmMagic) {
		t.Error("PPM magic does not match a PPM header")
	}
}
