parameters:
  - name: updateCheckTimeoutInMinutes
    displayName: "Timeout for checking target OS deployment in minutes"
    type: number
    default: 25

  - name: verboseLogging
    displayName: "Enable verbose logging"
    type: boolean
    default: false

  - name: imageOverride
    displayName: "Image override prefix"
    type: string
    default: ""

  - name: platform
    displayName: Test platform
    type: string
    values:
      - qemu

  - name: flavor
    displayName: Image flavor
    type: string
    values:
      - qemu-grub
      - qemu
      - uki

  - name: pool
    displayName: Agent pool
    type: string
    default: "trident-ubuntu-1es-pool-eastus2"

  - name: skipExtensionTesting
    displayName: "Skip extension testing"
    type: string
    default: "false"

  - name: skipManualRollbackTesting
    displayName: "Skip manual rollback testing"
    type: string
    default: "false"

  - name: skipRuntimeUpdateTesting
    displayName: "Skip runtime update testing"
    type: string
    default: "false"

  - name: skipNetplanRuntimeTesting
    displayName: "Skip netplan runtime testing"
    type: string
    default: "false"

  - name: micBuildType
    displayName: MIC Build Type
    type: string
    values:
      - dev
      - preview
      - release
    default: release

  - name: micVersion
    displayName: MIC Version
    type: string
    default: "*.*.*"

  - name: isUki
    displayName: "Is the image UKI or not"
    type: string
    default: "false"

  - name: testSecureBoot
    displayName: "Test Secure Boot"
    type: boolean
    default: true

jobs:
  - job: RollbackTesting_${{ replace(parameters.flavor, '-', '_') }}
    displayName: Rollback Testing - ${{ parameters.flavor }}
    timeoutInMinutes: ${{ parameters.updateCheckTimeoutInMinutes }}
    pool:
      type: linux
      name: ${{ parameters.pool }}
      hostArchitecture: amd64

    variables:
      ob_outputDirectory: $(Pipeline.Workspace)/s/trident/deployment_logs_${{ parameters.flavor }}
      ob_artifactBaseName: "rollback-testing-${{ parameters.flavor }}"
      TEST_RESOURCE_GROUP: trident-vm-servicing-validation-$(Build.BuildId)

    steps:
      - template: ../common_tasks/checkout_trident.yml
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: current
          artifactName: image-${{ parameters.flavor }}-base
          targetPath: "$(Build.ArtifactStagingDirectory)/"
        displayName: Download Base Image

      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: current
          artifactName: image-${{ parameters.flavor }}-update-a
          targetPath: "$(Build.ArtifactStagingDirectory)"
        displayName: Download Update Image

      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: current
          artifactName: ssh-keys
          targetPath: "$(Build.ArtifactStagingDirectory)/ssh"
        displayName: Download SSH Keys

      - task: DownloadPipelineArtifact@2
        displayName: "Download go-tools"
        inputs:
          buildType: current
          artifactName: "go-tools"
          patterns: |
            netlisten
            storm-trident
          targetPath: "$(TRIDENT_SOURCE_DIR)/bin"

      - bash: |
          set -eux
          chmod +x $(TRIDENT_SOURCE_DIR)/bin/netlisten
          chmod +x $(TRIDENT_SOURCE_DIR)/bin/storm-trident
          cp $(Build.ArtifactStagingDirectory)/ssh/id_rsa* ~/.ssh/
          chmod -R 700 ~/.ssh/
          mkdir -p $(ob_outputDirectory)
          ls -l ~/.ssh/
        displayName: Set up SSH Keys and setup output directory

      - bash: |
          set -eux
          ./bin/storm-trident script build-extension-images --build-sysexts --num-clones 3
          mv ./test-sysext-*.raw $(Build.ArtifactStagingDirectory)/

          find $(Build.ArtifactStagingDirectory)
        displayName: "Create extensions for test"
        workingDirectory: $(TRIDENT_SOURCE_DIR)

      - template: common/mic-download-template.yaml@platform-pipelines
        parameters:
          buildType: ${{ parameters.micBuildType }}
          arch: amd64
          micVersion: ${{ parameters.micVersion }}

      - bash: |
          set -eux

          STORM_DYNAMIC_FLAGS=""
          if [ "${{ parameters.verboseLogging }}" == "True" ]; then
            STORM_DYNAMIC_FLAGS="$STORM_DYNAMIC_FLAGS --verbose"
          fi
          if [ "${{ parameters.flavor }}" != "uki" ]; then
            if [[ "${{ parameters.testSecureBoot }}" == 'true' ]]; then
              STORM_DYNAMIC_FLAGS="$STORM_DYNAMIC_FLAGS --secure-boot"
            fi
          fi
          if [ "${{ parameters.skipManualRollbackTesting }}" == "true" ]; then
            # skip manual rollback testing
            STORM_DYNAMIC_FLAGS="$STORM_DYNAMIC_FLAGS --skip-manual-rollbacks"
          fi
          if [ "${{ parameters.skipRuntimeUpdateTesting }}" == "true" ]; then
            # skip runtime update testing
            STORM_DYNAMIC_FLAGS="$STORM_DYNAMIC_FLAGS --skip-runtime-updates"
          fi
          if [ "${{ parameters.skipExtensionTesting }}" == "true" ]; then
            # Allow testing for non-extension scenarios
            STORM_DYNAMIC_FLAGS="$STORM_DYNAMIC_FLAGS --skip-extension-testing"
          fi
          if [ "${{ parameters.skipNetplanRuntimeTesting }}" == "true" ]; then
            # skip netplan runtime testing
            STORM_DYNAMIC_FLAGS="$STORM_DYNAMIC_FLAGS --skip-netplan-runtime-testing"
          fi
          if [[ "${{ parameters.micBuildType }}" == "dev" ]]; then
            STORM_DYNAMIC_FLAGS="$STORM_DYNAMIC_FLAGS --image-customizer-image imagecustomizer:dev"
          fi
          if [[ "${{ parameters.isUki }}" == "true" ]]; then
            STORM_DYNAMIC_FLAGS="$STORM_DYNAMIC_FLAGS --uki"
          fi

          sudo ./bin/storm-trident run rollback -a $STORM_DYNAMIC_FLAGS \
            --artifacts-dir $(Build.ArtifactStagingDirectory) \
            --output-path $(ob_outputDirectory) \
            --platform ${{ parameters.platform }} \
            --ssh-private-key-path $(SSH_PRIVATE_KEY_PATH) \
            --ssh-public-key-path $(SSH_PUBLIC_KEY_PATH) \
            --force-cleanup
        displayName: "Rollback test (${{ parameters.platform }})"
        workingDirectory: $(TRIDENT_SOURCE_DIR)
        timeoutInMinutes: 5

      - bash: |
          set -eux

          sudo zstd -T0 $(Build.ArtifactStagingDirectory)/booted.qcow2
          sudo mv $(Build.ArtifactStagingDirectory)/booted.qcow2.zst $(ob_outputDirectory)/
        workingDirectory: $(TRIDENT_SOURCE_DIR)
        condition: failed()
        displayName: "Publish logs and OS disk on failure"
        timeoutInMinutes: 5

      - bash: |
          set -eux
          sudo chmod -R 777 $(ob_outputDirectory)/
          sudo chown -R $USER:$USER $(ob_outputDirectory)/
          ls -lR $(ob_outputDirectory)/
        condition: always()
        displayName: "Ensure output directory permissions"
