parameters:
  - name: "stageType"
    displayName: "Pipeline configuration type"
    type: string

stages:
  - stage: DefineTests_E2E
    displayName: Define all E2E test matrices
    dependsOn:
      - BuildingTools
    jobs:
      - job: DefineTests
        displayName: Get List of tests to run
        timeoutInMinutes: 10
        pool:
          type: linux

        variables:
          ob_outputDirectory: $(Build.SourcesDirectory)/build
          ob_artifactBaseName: storm-e2e-select-tests

        steps:
          - task: DownloadPipelineArtifact@2
            displayName: "Download go-tools"
            inputs:
              buildType: current
              artifactName: "go-tools"
              patterns: |
                storm-trident
              targetPath: "$(Build.SourcesDirectory)/bin"
          - bash: |
              chmod +x ./bin/storm-trident
              ./bin/storm-trident script e2e-matrix "${{ parameters.stageType }}"
            name: matrices
            displayName: Matrix of Trident configurations for E2E Tests

  # Storm E2E Tests: VM HOST
  # All 18 VM host configurations are enabled and run via single storm-trident
  # invocations. Each scenario handles setup, install, validation, A/B updates,
  # metrics collection, and log publishing internally.
  - template: test_execution_template.yml
    parameters:
      hardwareType: "VM"
      runtimeType: "HOST"

  # VM CONTAINER and BM configurations are not yet supported by storm-trident.
  # BM requires BMC credential management and external provisioning (not implemented).
  # Container runtime support is pending (see setup.go, invert.py).
  # - template: test_execution_template.yml
  #   parameters:
  #     hardwareType: "VM"
  #     runtimeType: "CONTAINER"

  # - template: test_execution_template.yml
  #   parameters:
  #     hardwareType: "BM"
  #     runtimeType: "HOST"
  #     maxParallel: 1

  # - template: test_execution_template.yml
  #   parameters:
  #     hardwareType: "BM"
  #     runtimeType: "CONTAINER"
  #     maxParallel: 1
