parameters:
  - name: tridentRepoName
    type: string
    values:
      - self
      - trident

  - name: "stageType"
    displayName: "Pipeline configuration type"
    type: string

stages:
  - stage: DefineTests_E2E
    displayName: Define all E2E test matrices
    dependsOn:
      - BuildingTools
    jobs:
      - job: DefineTests
        displayName: Get List of tests to run
        timeoutInMinutes: 10
        pool:
          type: linux

        variables:
          ob_outputDirectory: $(Pipeline.Workspace)/s/trident/build
          ob_artifactBaseName: storm-e2e-select-tests

        steps:
          - template: ../common_tasks/checkout_trident.yml
            parameters:
              tridentRepoName: ${{ parameters.tridentRepoName }}
          - task: DownloadPipelineArtifact@2
            displayName: "Download go-tools"
            inputs:
              buildType: current
              artifactName: "go-tools"
              patterns: |
                storm-trident
              targetPath: "$(TRIDENT_SOURCE_DIR)/bin"
          - bash: |
              chmod +x ./bin/storm-trident
              ./bin/storm-trident script e2e-matrix "${{ parameters.stageType }}"
            name: matrices
            workingDirectory: $(TRIDENT_SOURCE_DIR)
            displayName: Matrix of Trident configurations for E2E Tests

  # TODO: enable once storm tests are ready
  - template: test_execution_template.yml
    parameters:
      hardwareType: "VM"
      runtimeType: "HOST"
      tridentRepoName: ${{ parameters.tridentRepoName }}

  # - template: test_execution_template.yml
  #   parameters:
  #     hardwareType: "VM"
  #     runtimeType: "CONTAINER"
  #     tridentRepoName: ${{ parameters.tridentRepoName }}

  # - template: test_execution_template.yml
  #   parameters:
  #     hardwareType: "BM"
  #     runtimeType: "HOST"
  #     maxParallel: 1
  #     tridentRepoName: ${{ parameters.tridentRepoName }}

  # - template: test_execution_template.yml
  #   parameters:
  #     hardwareType: "BM"
  #     runtimeType: "CONTAINER"
  #     maxParallel: 1
  #     tridentRepoName: ${{ parameters.tridentRepoName }}
