[package]
name = "trident_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
netplan-types = "0.4.0"
serde = { version = "1.0.185", features = ["derive"] }
serde_yaml = "0.9.25"
uuid = { version = "1.4.1", features = ["v4", "serde"] }
