parameters:
  - name: publishToDevFeed
    type: boolean
    default: false

  - name: tridentArtifactName
    type: string

  - name: codeCoverage
    type: boolean
    default: true

  - name: osModifierBranch
    type: string
    default: "submodule"

  - name: dependsOnStage
    type: string
    default: ''

stages:
  - stage: GetTridentBinaries_rpms
    displayName: Trident RPMs (Build)
    ${{ if ne(parameters.dependsOnStage, '') }}:
      dependsOn: ${{ parameters.dependsOnStage }}

    jobs:
      - job: CheckTrident
        displayName: Check
        pool:
          type: linux

        variables:
          - name: ob_outputDirectory
            value: "$(Build.SourcesDirectory)/trident/out"

        steps:
          - template: ../common_tasks/avoid-pypi-usage.yml
          - template: check.yml

      - job: TestTrident
        displayName: Unit Test
        pool:
          type: linux

        variables:
          - name: ob_outputDirectory
            value: "$(Build.SourcesDirectory)/trident/out"

        steps:
          - template: ../common_tasks/avoid-pypi-usage.yml
          # need newer rust for cargo-nextest, use rustup.yml to install
          - template: ../common_tasks/rustup.yml
          - template: ../common_tasks/cargo-auth.yml
          - template: unit-test.yml
            parameters:
              codeCoverage: ${{ parameters.codeCoverage }}
              unitTestCoverageBaseline: 70 # Unit tests

      - job: BuildTrident
        displayName: Build Trident 3.0 RPMs
        pool:
          type: linux

        variables:
          - name: ob_artifactBaseName
            value: ${{ parameters.tridentArtifactName }}
          - name: ob_outputDirectory
            value: "$(Build.SourcesDirectory)/out"
          - template: common/setup-registries-vars-template.yaml@platform-pipelines
            parameters:
              buildType: auto

        steps:
          - template: ../common_tasks/os-info.yml
          - template: ../common_tasks/avoid-pypi-usage.yml
          - template: ../common_tasks/cargo-auth.yml
          - template: ../common_tasks/build-osmodifier.yml
            parameters:
              osModifierBranch: ${{ parameters.osModifierBranch }}
          - template: release.yml
            parameters:
              targetArchitecture: "AMD64"
          - ${{ if eq(parameters.publishToDevFeed, true) }}:
              - template: publish-dev.yml

      - job: BuildTridentARM64
        displayName: Build Trident 3.0 RPMs for ARM64
        pool:
          type: linux
          name: mariner-hci-ARM64-1es-pool-westcentralus
          hostArchitecture: arm64

        variables:
          - name: ob_artifactBaseName
            value: ${{ parameters.tridentArtifactName }}-arm64
          - name: ob_outputDirectory
            value: "$(Build.SourcesDirectory)/out"
          - template: common/setup-registries-vars-template.yaml@platform-pipelines
            parameters:
              buildType: auto

        steps:
          - template: ../common_tasks/avoid-pypi-usage.yml
          - template: ../common_tasks/cargo-auth.yml
          - template: ../common_tasks/build-osmodifier.yml
            parameters:
              osModifierBranch: ${{ parameters.osModifierBranch }}
          - template: release.yml
            parameters:
              targetArchitecture: "ARM64"
