parameters:
  - name: tridentArtifactName
    type: string

  - name: codeCoverage
    type: boolean
    default: true

  - name: baseimgBuildType
    displayName: Base Image build type
    type: string
    values:
      - preview
      - release
    default: "release"

  - name: previewContainerImageBuildId
    type: string
    default: "latestFromBranch"

stages:
  - stage: GetTridentBinaries_rpms
    displayName: Trident RPMs (Build)

    jobs:
      - job: CheckTrident
        displayName: Check
        pool:
          type: linux

        variables:
          - name: ob_outputDirectory
            value: "$(Build.SourcesDirectory)/trident/out"

        steps:
          - template: check.yml

      - job: TestTrident
        displayName: Unit Test
        pool:
          type: linux

        variables:
          - name: ob_outputDirectory
            value: "$(Build.SourcesDirectory)/trident/out"

        steps:
          - template: ../common_tasks/cargo-auth.yml
            parameters:
              action: override
          - template: unit-test.yml

      - job: Coverage
        displayName: Evaluate Unit Test Code Coverage
        condition: eq(${{ parameters.codeCoverage }}, true)
        pool:
          type: linux

        variables:
          ob_outputDirectory: "$(Build.SourcesDirectory)/trident/out"

        steps:
          - template: ../common_tasks/cargo-auth.yml
            parameters:
              action: override
          - template: ../common_tasks/coverage.yml
            parameters:
              codeCoverageBaseline: 70 # Unit tests

      - job: BuildTrident
        displayName: Build Trident 3.0 RPMs
        pool:
          type: linux

        variables:
          - name: ob_artifactBaseName
            value: ${{ parameters.tridentArtifactName }}
          - name: ob_outputDirectory
            value: "$(Build.SourcesDirectory)/out"
          - template: common/setup-registries-vars-template.yaml@platform-pipelines
            parameters:
              buildType: auto

        steps:
          - template: ../common_tasks/cargo-auth.yml
          - template: ../common_tasks/build-osmodifier.yml
          - template: release.yml
            parameters:
              baseimgBuildType: ${{ parameters.baseimgBuildType }}
              previewContainerImageBuildId: ${{ parameters.previewContainerImageBuildId }}

      - job: BuildTridentARM64
        displayName: Build Trident 3.0 RPMs for ARM64
        pool:
          type: linux
          name: mariner-hci-ARM64-1es-pool-westcentralus
          hostArchitecture: arm64

        variables:
          - name: ob_artifactBaseName
            value: ${{ parameters.tridentArtifactName }}-arm64
          - name: ob_outputDirectory
            value: "$(Build.SourcesDirectory)/out"
          - template: common/setup-registries-vars-template.yaml@platform-pipelines
            parameters:
              buildType: auto

        steps:
          - template: ../common_tasks/cargo-auth.yml
          - template: ../common_tasks/build-osmodifier.yml
          - template: release.yml
            parameters:
              baseimgBuildType: ${{ parameters.baseimgBuildType }}
              previewContainerImageBuildId: ${{ parameters.previewContainerImageBuildId }}

      - job: BuildTrident2
        displayName: Build Trident 2.0 RPMs
        pool:
          type: linux

        variables:
          - name: ob_artifactBaseName
            value: ${{ parameters.tridentArtifactName }}2
          - name: ob_outputDirectory
            value: "$(Build.SourcesDirectory)/out"
          - template: common/setup-registries-vars-template.yaml@platform-pipelines
            parameters:
              buildType: auto

        steps:
          - template: ../common_tasks/cargo-auth.yml
            parameters:
              action: override
          - template: ../common_tasks/build-osmodifier.yml
          - template: release2.yml
