parameters:
  - name: "stageType"
    displayName: "Pipeline configuration type"
    type: string
    values:
      - pr
      - pr-e2e
      - pr-e2e-azure
      - ci
      - pre
      - rel
      - full-validation

  - name: codeCoverage
    type: boolean
    default: true

  - name: tridentArtifactName
    type: string

  - name: forceTridentRebuild
    type: boolean
    default: false

  - name: osModifierBranch
    type: string
    default: "submodule"

  - name: dependsOnStage
    type: string
    default: ''

  - name: targetArchitecture
    type: string
    values:
      - amd64
      - arm64 

stages:
  - ${{ if or(parameters.forceTridentRebuild, eq(parameters.stageType, 'pr'), eq(parameters.stageType, 'pr-e2e'), eq(parameters.stageType, 'ci'), eq(parameters.stageType, 'pr-e2e-azure')) }}:
      - template: build-source.yml
        parameters:
          ${{ if eq(parameters.stageType, 'pr') }}:
            publishToDevFeed: true
          tridentArtifactName: ${{ parameters.tridentArtifactName }}
          codeCoverage: ${{ parameters.codeCoverage }}
          osModifierBranch: ${{ parameters.osModifierBranch }}
          dependsOnStage: ${{ parameters.dependsOnStage }}
          targetArchitecture: ${{ parameters.targetArchitecture }}

  - ${{ elseif eq(parameters.targetArchitecture, 'amd64') }}:
      - template: ../download_staged/download-staged.yml
        parameters:
          artifactName: ${{ parameters.tridentArtifactName }}
          stageType: ${{ parameters.stageType }}
          packageName: rpms
