parameters:
  - name: "stageType"
    displayName: "Pipeline configuration type"
    type: string
    values:
      - pr
      - pr-e2e
      - pr-e2e-azure
      - ci
      - pre
      - rel

  - name: codeCoverage
    type: boolean
    default: true

  - name: tridentArtifactName
    type: string

  - name: baseimgBuildType
    displayName: Base Image build type
    type: string
    values:
      - preview
      - release
    default: "release"

  - name: previewContainerImageBuildId
    type: string
    default: "latestFromBranch"

  - name: previewContainerImageArm64BuildId
    type: string
    default: "latestFromBranch"

  - name: forceTridentRebuild
    type: boolean
    default: false

stages:
  - ${{ if or(parameters.forceTridentRebuild, eq(parameters.stageType, 'pr'), eq(parameters.stageType, 'pr-e2e'), eq(parameters.stageType, 'ci'), eq(parameters.stageType, 'pr-e2e-azure')) }}:
      - template: build-source.yml
        parameters:
          tridentArtifactName: ${{ parameters.tridentArtifactName }}
          codeCoverage: ${{ parameters.codeCoverage }}
          baseimgBuildType: ${{ parameters.baseimgBuildType }}
          previewContainerImageBuildId: ${{ parameters.previewContainerImageBuildId }}
          previewContainerImageArm64BuildId: ${{ parameters.previewContainerImageArm64BuildId }}

  - ${{ else }}:
      - template: ../download_staged/download-staged.yml
        parameters:
          artifactName: ${{ parameters.tridentArtifactName }}
          stageType: ${{ parameters.stageType }}
          packageName: rpms
