parameters:
  - name: buildPurpose
    type: string
    default: "post_merge"
    values:
      - daily
      - pullrequest
      - post_merge
      - validation
      - weekly

  - name: deploymentEnvironment
    type: string
    default: virtualMachine
    values:
      - bareMetal
      - virtualMachine

  - name: runtimeEnv
    displayName: "Runtime environment (host vs container)"
    type: string
    values:
      - host
      - container

  # Define whether to run tests using SecureBoot or not. This impacts both
  # which tests run (many encryption-related tests only run with SecureBoot enabled) and
  # how the test machines are configured.
  - name: testSecureBoot
    displayName: "Test Secure Boot"
    type: boolean
    default: true


jobs:
  - job: DefineTests
    displayName: Get List of tests to run
    timeoutInMinutes: 10
    pool:
      type: linux

    variables:
      ob_outputDirectory: /tmp/build
      ob_artifactBaseName: select_tests_${{ parameters.deploymentEnvironment }}_${{ parameters.runtimeEnv }}_$(System.JobAttempt)

    steps:
      - template: ../common_tasks/checkout_trident.yml
      - template: ../common_tasks/avoid-pypi-usage.yml
      - bash: |
          SKIP_ENCRYPTION_TESTS_ARG=""
          if [ "${{ parameters.testSecureBoot }}" == "False" ]; then
            SKIP_ENCRYPTION_TESTS_ARG="--skipEncryptionTests"
          fi
          python3 ./tests/e2e_tests/helpers/read_target_configurations.py \
              --configurations ./tests/e2e_tests/target-configurations.yaml \
              --env ${{ parameters.deploymentEnvironment }} \
              --runtimeEnv ${{ parameters.runtimeEnv }} \
              --purpose ${{ parameters.buildPurpose }} \
              $SKIP_ENCRYPTION_TESTS_ARG \
              --matrix-name matrixConfigurations
        name: setConfigurations
        displayName: Matrix of Trident configurations for E2E Tests
        workingDirectory: $(TRIDENT_SOURCE_DIR)
