parameters:
  - name: buildPurpose
    type: string
    default: "post_merge"
    values:
      - daily
      - pullrequest
      - post_merge
      - validation

  - name: deploymentEnvironment
    type: string
    default: virtualMachine
    values:
      - bareMetal
      - virtualMachine

  - name: runtimeEnv
    displayName: "Runtime environment (host vs container)"
    type: string
    values:
      - host
      - container

jobs:
  - job: DefineTests
    displayName: Get List of tests to run
    timeoutInMinutes: 10
    pool:
      type: linux

    variables:
      ob_outputDirectory: $(Build.SourcesDirectory)/build
      ob_artifactBaseName: select_tests_${{ parameters.runtimeEnv }}_$(System.JobAttempt)

    steps:
      - bash: |
          set -eux
          matrix=$(
              python3 ./e2e_tests/helpers/read_target_configurations.py \
                --configurations ./e2e_tests/target-configurations.yaml \
                --env ${{ parameters.deploymentEnvironment }} \
                --runtimeEnv ${{ parameters.runtimeEnv }} \
                --purpose ${{ parameters.buildPurpose }} \
              )
          
          set +x
          echo "##vso[task.setvariable variable=matrixConfigurations;isOutput=true]$matrix"
        name: setConfigurations
        displayName: Matrix of Trident configurations for E2E Tests
