jobs:
  - job: PrepareSSHKeys
    displayName: Prepare SSH Keys
    timeoutInMinutes: 5
    pool:
      type: linux

    variables:
      ob_outputDirectory: out/
      ob_artifactBaseName: "ssh-keys"

    steps:
      - task: PipAuthenticate@1
        displayName: Provision - Authenticate Pip
        inputs:
          artifactFeeds: 'mariner/Mariner-Pypi-Feed'

      - bash: |
          set -eux
          mkdir -p $(ob_outputDirectory)
          ssh-keygen -t rsa -b 2048 -f $(ob_outputDirectory)/id_rsa -q -N ""
        displayName: Generate SSH Keys
