parameters:
  - name: testingRun
    displayName: "Download prebuilt test artifacts"
    type: boolean
    default: false

  - name: baseimgBuildType
    displayName: Base Image build type
    type: string
    values:
      - preview
      - release
    default: "release"

  - name: previewContainerImageBuildId
    displayName: "Build Id of the pipeline run, default will select latest successful run from pipeline 2116 ([AMD64-6-OneBranch]-Prod-BuildImages) with tag 3.0-preview"
    type: string
    default: "latestFromBranch"

  - name: baseimgAzlVersion
    displayName: Base Image AZL version
    type: string
    default: "3.0"

  - name: updateIterationCount
    displayName: "Number of updates to test"
    type: number
    default: 1

  - name: rollbackTesting
    displayName: "Run rollback test"
    type: boolean
    default: true

  - name: workers
    displayName: "Number of workers to use"
    type: number
    default: 1

  - name: updateCheckTimeoutInMinutes
    displayName: "Timeout for checking runtime OS deployment in minutes"
    type: number
    default: 30

  - name: verboseLogging
    displayName: "Enable verbose logging"
    type: boolean
    default: false

  - name: includeAzure
    displayName: "Include Azure testing"
    type: boolean
    default: false

  - name: micBuildType
    displayName: MIC Build Type
    type: string
    values:
    - dev
    - preview
    - release
    default: release

  - name: micVersion
    displayName: MIC Version
    type: string
    default: "*.*.*"

stages:
  - stage: PrepareSSHKeys
    displayName: Prepare SSH Keys
    jobs:
      - template: generate-ssh-keys.yml

  - stage: BuildImagesQemu
    displayName: Build Base and Update Images for QEMU
    dependsOn:
      - PrepareSSHKeys
      - ${{ if eq(parameters.testingRun, true) }}:
          - DownloadTestingElements
      - ${{ else }}:
          - GetTridentBinaries_rpms

    jobs:
      - template: build-image.yml
        parameters:
          baseimgBuildType: ${{ parameters.baseimgBuildType }}
          label: "qemu-base"
          makeTarget: "build/trident-vm-verity-testimage.qcow2"
          baseimgType: qemu_guest
          baseimgAzlVersion: ${{ parameters.baseimgAzlVersion }}
          previewContainerImageBuildId: ${{ parameters.previewContainerImageBuildId }}
          micBuildType: ${{ parameters.micBuildType }}
          micVersion: ${{ parameters.micVersion }}

      - template: build-image.yml
        parameters:
          baseimgBuildType: ${{ parameters.baseimgBuildType }}
          label: "qemu-update-a"
          makeTarget: "trident-vm-verity-testimage"
          baseimgType: qemu_guest
          baseimgAzlVersion: ${{ parameters.baseimgAzlVersion }}
          previewContainerImageBuildId: ${{ parameters.previewContainerImageBuildId }}
          micBuildType: ${{ parameters.micBuildType }}
          micVersion: ${{ parameters.micVersion }}

      - template: build-image.yml
        parameters:
          baseimgBuildType: ${{ parameters.baseimgBuildType }}
          label: "qemu-update-b"
          makeTarget: "trident-vm-verity-testimage"
          baseimgType: qemu_guest
          baseimgAzlVersion: ${{ parameters.baseimgAzlVersion }}
          previewContainerImageBuildId: ${{ parameters.previewContainerImageBuildId }}
          micBuildType: ${{ parameters.micBuildType }}
          micVersion: ${{ parameters.micVersion }}

  - ${{ if eq(parameters.includeAzure, true) }}:
    - stage: BuildImagesAzure
      displayName: Build Base and Update Images for Azure
      dependsOn:
        - PrepareSSHKeys
        - ${{ if eq(parameters.testingRun, true) }}:
            - DownloadTestingElements
        - ${{ else }}:
            - GetTridentBinaries_rpms

      jobs:
        - template: build-image.yml
          parameters:
            baseimgBuildType: ${{ parameters.baseimgBuildType }}
            label: "azure-base"
            makeTarget: "build/trident-vm-verity-azure-testimage.vhd"
            baseimgType: core_selinux
            baseimgAzlVersion: ${{ parameters.baseimgAzlVersion }}
            previewContainerImageBuildId: ${{ parameters.previewContainerImageBuildId }}
            micBuildType: ${{ parameters.micBuildType }}
            micVersion: ${{ parameters.micVersion }}

        - template: build-image.yml
          parameters:
            baseimgBuildType: ${{ parameters.baseimgBuildType }}
            label: "azure-update-a"
            makeTarget: "trident-vm-verity-azure-testimage"
            baseimgType: core_selinux
            baseimgAzlVersion: ${{ parameters.baseimgAzlVersion }}
            previewContainerImageBuildId: ${{ parameters.previewContainerImageBuildId }}
            micBuildType: ${{ parameters.micBuildType }}
            micVersion: ${{ parameters.micVersion }}

        - template: build-image.yml
          parameters:
            baseimgBuildType: ${{ parameters.baseimgBuildType }}
            label: "azure-update-b"
            makeTarget: "trident-vm-verity-azure-testimage"
            baseimgType: core_selinux
            baseimgAzlVersion: ${{ parameters.baseimgAzlVersion }}
            previewContainerImageBuildId: ${{ parameters.previewContainerImageBuildId }}
            micBuildType: ${{ parameters.micBuildType }}
            micVersion: ${{ parameters.micVersion }}

  - stage: ServicingTesting
    displayName: Servicing Testing
    dependsOn:
      - BuildImagesQemu
      - ${{ if eq(parameters.includeAzure, true) }}:
        - BuildImagesAzure

    jobs:
      - template: testing-template.yml
        parameters:
          updateIterationCount: ${{ parameters.updateIterationCount }}
          rollbackTesting: ${{ parameters.rollbackTesting }}
          workers: ${{ parameters.workers }}
          updateCheckTimeoutInMinutes: ${{ parameters.updateCheckTimeoutInMinutes }}
          verboseLogging: ${{ parameters.verboseLogging }}
          platform: qemu

      - ${{ if eq(parameters.includeAzure, true) }}:
        - template: testing-template.yml
          parameters:
            updateIterationCount: ${{ parameters.updateIterationCount }}
            rollbackTesting: ${{ parameters.rollbackTesting }}
            workers: ${{ parameters.workers }}
            updateCheckTimeoutInMinutes: ${{ parameters.updateCheckTimeoutInMinutes }}
            verboseLogging: ${{ parameters.verboseLogging }}
            platform: azure
            pool: trident-ubuntu-official-1es-pool-eastus2
