parameters:
  - name: buildNetlaunch
    type: boolean
    default: true

  - name: buildIsogen
    type: boolean
    default: true

stages:
  - stage: BuildingTools
    displayName: Building Tools

    jobs:
      - job: BuildGoTools
        displayName: Build Go Tools
        timeoutInMinutes: 60
        pool:
          type: linux
          name: CAPKV_Pool
          hostArchitecture: amd64

        variables:
          argusToolkitSourceDirectory: $(Build.SourcesDirectory)/argus-toolkit

          ob_outputDirectory: $(Build.SourcesDirectory)/go-tools
          ob_artifactBaseName: go-tools

        steps:
          - ${{ if eq(parameters.buildNetlaunch, true) }}:
              - bash: |
                  set -eux
                  make bin/netlaunch
                  mkdir -p $(ob_outputDirectory)
                  mv bin/netlaunch $(ob_outputDirectory)
                workingDirectory: $(Build.SourcesDirectory)
                displayName: "Building netlaunch"

          - ${{ if eq(parameters.buildIsogen, true) }}:
              - checkout: argus-toolkit

              - template: ../common_tasks/install-clamav.yml

              - bash: |
                  set -eux
                  make build/isogen
                  mkdir -p $(ob_outputDirectory)
                  mv build/isogen $(ob_outputDirectory)
                workingDirectory: $(argusToolkitSourceDirectory)
                displayName: "Building Isogen tool"
