parameters:
  - name: buildNetlaunch
    type: boolean
    default: true

  - name: buildNetlisten
    type: boolean
    default: true

  - name: buildMiniproxy
    type: boolean
    default: true

  - name: buildMkcosi
    type: boolean
    default: true

  - name: buildStormTrident
    type: boolean
    default: true

  - name: buildVirtdeploy
    type: boolean
    default: true

stages:
  - stage: BuildingTools
    displayName: Building Tools

    jobs:
      - job: BuildGoTools
        displayName: Build Go Tools
        timeoutInMinutes: 60
        pool:
          type: linux
          name: trident-ubuntu-1es-pool-eastus2
          hostArchitecture: amd64

        variables:
          ob_outputDirectory: $(Pipeline.Workspace)/s/trident/go-tools
          ob_artifactBaseName: go-tools

        steps:
          - ${{ if eq(variables['Build.Repository.Name'], 'trident')}}:
              - checkout: self
                fetchDepth: 1
                path: s/trident
          - ${{ else }}:
              - checkout: trident
                fetchDepth: 1
                path: s/trident

          - template: ../common_tasks/avoid-pypi-usage.yml

          - ${{ if eq(parameters.buildNetlaunch, true) }}:
              - bash: |
                  set -eux
                  make bin/netlaunch
                  mkdir -p $(ob_outputDirectory)
                  mv bin/netlaunch $(ob_outputDirectory)
                workingDirectory: $(Pipeline.Workspace)/s/trident
                displayName: "Building netlaunch"

          - ${{ if eq(parameters.buildNetlaunch, true) }}:
              - bash: |
                  set -eux
                  make bin/netlisten
                  mkdir -p $(ob_outputDirectory)
                  mv bin/netlisten $(ob_outputDirectory)
                workingDirectory: $(Pipeline.Workspace)/s/trident
                displayName: "Building netlisten"

          - ${{ if eq(parameters.buildMiniproxy, true) }}:
              - bash: |
                  set -eux
                  make bin/miniproxy
                  mkdir -p $(ob_outputDirectory)
                  mv bin/miniproxy $(ob_outputDirectory)
                workingDirectory: $(Pipeline.Workspace)/s/trident
                displayName: "Building miniproxy"

          - ${{ if eq(parameters.buildMkcosi, true) }}:
              - bash: |
                  set -eux
                  make bin/mkcosi
                  mkdir -p $(ob_outputDirectory)
                  mv bin/mkcosi $(ob_outputDirectory)
                workingDirectory: $(Pipeline.Workspace)/s/trident
                displayName: "Building mkcosi"

          - ${{ if eq(parameters.buildStormTrident, true) }}:
              - bash: |
                  set -eux
                  make bin/storm-trident
                  mkdir -p $(ob_outputDirectory)
                  mv bin/storm-trident $(ob_outputDirectory)
                workingDirectory: $(Pipeline.Workspace)/s/trident
                displayName: "Building storm-trident"

          - ${{ if eq(parameters.buildVirtdeploy, true) }}:
              - bash: |
                  set -eux
                  make bin/virtdeploy
                  mkdir -p $(ob_outputDirectory)
                  mv bin/virtdeploy $(ob_outputDirectory)
                workingDirectory: $(Pipeline.Workspace)/s/trident
