parameters:
  - name: buildNetlaunch
    type: boolean
    default: true

  - name: buildNetlisten
    type: boolean
    default: true

  - name: buildMiniproxy
    type: boolean
    default: true

  - name: buildMkcosi
    type: boolean
    default: true

  - name: buildStormTrident
    type: boolean
    default: true

  - name: buildVirtdeploy
    type: boolean
    default: true

  - name: architecture
    displayName: System Architecture
    type: string
    values:
      - arm64
      - amd64
    default: amd64

stages:
  - stage: BuildingTools_${{ parameters.architecture }}
    displayName: Building Tools for ${{ parameters.architecture }}

    jobs:
      - job: BuildGoTools_${{ parameters.architecture }}
        displayName: Build Go Tools for ${{ parameters.architecture }}
        timeoutInMinutes: 10
        pool:
          ${{ if eq(parameters.architecture, 'amd64') }}:
            type: linux
            name: trident-ubuntu-1es-pool-eastus2
            hostArchitecture: amd64
          ${{ if eq(parameters.architecture, 'arm64') }}:
            type: linux
            name: azl3-hci-ARM64-1es-pool-westcentralus
            hostArchitecture: arm64

        variables:
          ${{ if eq(parameters.architecture, 'arm64') }}:
            artifactName: go-tools-arm64
          ${{ if eq(parameters.architecture, 'amd64') }}:
            artifactName: go-tools
          ob_outputDirectory: $(Build.SourcesDirectory)/$(artifactName)
          ob_artifactBaseName: $(artifactName)

        steps:
          - template: ../common_tasks/avoid-pypi-usage.yml
          - template: ../common_tasks/update-protoc.yml
            parameters:
              ${{ if eq(parameters.architecture, 'arm64') }}:
                protocArch: aarch_64
              ${{ if eq(parameters.architecture, 'amd64') }}:
                protocArch: x86_64
          - bash: |
              set -eux
              go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
              go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

              echo "Adding '$(go env GOPATH)/bin' to PATH for subsequent tasks"
              echo "##vso[task.prependpath]$(go env GOPATH)/bin"
            displayName: "Install protoc-gen-go"

          - ${{ if eq(parameters.buildNetlaunch, true) }}:
              - bash: |
                  set -eux
                  make bin/netlaunch
                  mkdir -p $(ob_outputDirectory)
                  mv bin/netlaunch $(ob_outputDirectory)
                workingDirectory: $(Build.SourcesDirectory)
                displayName: "Building netlaunch"

          - ${{ if eq(parameters.buildNetlaunch, true) }}:
              - bash: |
                  set -eux
                  make bin/netlisten
                  mkdir -p $(ob_outputDirectory)
                  mv bin/netlisten $(ob_outputDirectory)
                workingDirectory: $(Build.SourcesDirectory)
                displayName: "Building netlisten"

          - ${{ if eq(parameters.buildMiniproxy, true) }}:
              - bash: |
                  set -eux
                  make bin/miniproxy
                  mkdir -p $(ob_outputDirectory)
                  mv bin/miniproxy $(ob_outputDirectory)
                workingDirectory: $(Build.SourcesDirectory)
                displayName: "Building miniproxy"

          - ${{ if eq(parameters.buildMkcosi, true) }}:
              - bash: |
                  set -eux
                  make bin/mkcosi
                  mkdir -p $(ob_outputDirectory)
                  mv bin/mkcosi $(ob_outputDirectory)
                workingDirectory: $(Build.SourcesDirectory)
                displayName: "Building mkcosi"

          - ${{ if eq(parameters.buildStormTrident, true) }}:
              - bash: |
                  set -eux
                  make bin/storm-trident
                  mkdir -p $(ob_outputDirectory)
                  mv bin/storm-trident $(ob_outputDirectory)
                workingDirectory: $(Build.SourcesDirectory)
                displayName: "Building storm-trident"

          - ${{ if eq(parameters.buildVirtdeploy, true) }}:
              - bash: |
                  set -eux
                  make bin/virtdeploy
                  mkdir -p $(ob_outputDirectory)
                  mv bin/virtdeploy $(ob_outputDirectory)
                workingDirectory: $(Build.SourcesDirectory)
