parameters:
  - name: testingRun
    displayName: "Download prebuilt test artifacts"
    type: boolean
    default: false

  - name: architecture
    displayName: Architecture
    type: string
    values:
      - arm64
      - amd64
    default: amd64

stages:
  - stage: DirectStreaming_DeploymentTesting_${{ parameters.architecture }}
    displayName: Direct Streaming Deployment VM ${{ parameters.architecture }} Testing
    dependsOn:
      - ${{ if eq(parameters.testingRun, true) }}:
          - DownloadTestingElements
      - ${{ else }}:
          - BuildingTools_${{ parameters.architecture }}
          - BuildTridentContainerImage
          - BuildImagesForDirectStreaming_${{ parameters.architecture }}

    jobs:
      - job: DirectStreamingTesting_${{ parameters.architecture }}
        displayName: Direct Streaming Deployment Testing for ${{ parameters.architecture }}
        timeoutInMinutes: 50
        pool:
          ${{ if eq(parameters.architecture, 'amd64') }}:
            type: linux
            name: trident-ubuntu-1es-pool-eastus2
            hostArchitecture: amd64
          ${{ if eq(parameters.architecture, 'arm64') }}:
            type: linux
            # name: azl3-hci-ARM64-1es-pool-westcentralus
            # name: mariner-hci-ARM64-1es-pool-westcentralus
            name: trident-ubuntu-ARM64-1es-pool-westus2
            hostArchitecture: arm64

        variables:
          - name: tridentSourceDirectory
            value: $(Build.SourcesDirectory)
          - ${{ if eq(parameters.architecture, 'arm64') }}:
            - name: installerISOName
              value: trident-direct-streaming-installer-arm64
            - name: testImageName
              value: trident-direct-streaming-testimage-arm64
          - ${{ if eq(parameters.architecture, 'amd64') }}:
            - name: installerISOName
              value: trident-direct-streaming-installer
            - name: testImageName
              value: trident-direct-streaming-testimage
          - name: ob_outputDirectory
            value: $(tridentSourceDirectory)/deployment_logs
          - name: ob_artifactBaseName
            value: direct_streaming_deployment _${{ parameters.architecture }}_log_$(System.JobAttempt)
          - name: netlaunchPort
            value: 4000

        steps:
          # Download all test images
          - template: ../testing_common/download-test-images.yml
            parameters:
              installerISO: $(installerISOName)
              tridentTestImage: ${{ variables.testImageName }}
              tridentTestImageVerity: skip
              tridentTestImageUsrVerity: skip
              downloadTridentContainer: false
              ${{ if eq(parameters.architecture, 'arm64') }}:
                goToolsArtifactName: go-tools-arm64
              ${{ if eq(parameters.architecture, 'amd64') }}:
                goToolsArtifactName: go-tools

          - bash: |
              set -ex
              sudo apt update -y
              sudo apt install -y python3 python3-pip

              sudo snap install yq

            displayName: "Install pip and yq"
            retryCountOnTaskFailure: 3

          - template: ../testing_vm/netlaunch-prep.yml

          - bash: |
              set -eux

              # Disable virtlogd rollover by setting max_size to 0
              cat /etc/libvirt/virtlogd.conf
              echo "max_size = 0" | sudo tee -a /etc/libvirt/virtlogd.conf
              cat /etc/libvirt/virtlogd.conf
              sudo systemctl restart virtlogd.socket

              ./tools/virt-deploy create --mem 12 --disks 32,32
            workingDirectory: $(tridentSourceDirectory)
            displayName: "Creating virt-deploy VM"

          - bash: |
              set -euxo pipefail
              ISO_FILE=./artifacts/iso/$(installerISOName).iso
              COSI_FILE=./artifacts/test-image/regular.cosi
              HASH=$(./scripts/cosi-sha384.py $COSI_FILE)
              sudo ./bin/storm-trident helper direct-streaming -a \
                  --log-dir $(ob_outputDirectory) \
                  --netlaunch-config-file ./tools/vm-netlaunch.yaml \
                  --cosi-file $COSI_FILE \
                  --cosi-metadata-sha384 $HASH \
                  --iso-file $ISO_FILE \
                  --port ${{variables.netlaunchPort}} \
                  --enable-secure-boot

            workingDirectory: $(tridentSourceDirectory)
            displayName: "🚀 Run netlaunch for testing"
            timeoutInMinutes: 20

          - bash: |
              set -eux
              ./bin/storm-trident script capture-screenshot \
                  --screenshot-filename "direct-streaming.png" \
                  --artifacts-folder "$(ob_outputDirectory)"
            displayName: "📷 Capture screenshot: direct streaming"
            condition: succeededOrFailed()

          - bash: |
              set -eux
              sudo ./bin/storm-trident helper display-logs -a \
                  --serial-log-artifact-file-name "direct-streaming-target-os-A-serial.log" \
                  --trident-trace-log-file "$(tridentSourceDirectory)/logstream-full.log" \
                  --artifacts-folder "$(ob_outputDirectory)"
            displayName: "📄 Display direct streaming logs"
            condition: succeededOrFailed()
