steps:
  - bash: |
      ./read-base-image-config-artifact-if-exists.sh $(Build.BuildId)
    workingDirectory: $(Build.SourcesDirectory)/.pipelines/templates/stages/base_image_config
    displayName: "Read Base Image Config artifact into variables"
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

  - bash: |
      echo "base image config runtime variables:"
      echo "BASEIMG_BUILD_TYPE = $(BASEIMG_BUILD_TYPE)"
      echo "BASE_IMAGE_PIPELINE_BUILD_ID = $(BASE_IMAGE_PIPELINE_BUILD_ID)"
      echo "BASE_IMAGE_ARM64_PIPELINE_BUILD_ID = $(BASE_IMAGE_ARM64_PIPELINE_BUILD_ID)"
    displayName: "Output Base Image Config runtime variables"
