parameters:
  - name: architecture
    type: string
    values:
      - arm64
      - amd64
    default: arm64

  - name: testAzureLinuxStreamingImage
    type: boolean
    default: true

  - name: testUbuntuStreamingImage
    type: boolean
    default: true

  - name: micBuildType
    displayName: MIC Build Type
    type: string
    values:
      - dev
      - preview
      - release
    default: release

  - name: micVersion
    displayName: MIC Version
    type: string
    default: "*.*.*"

  - name: testFairwaterStreamingImage
    type: boolean
    default: false

  - name: ubuntuVersions
    type: object
    values:
      - "2204"
      - "2404"
    default:
      - "2204"
      - "2404"

stages:
  - ${{ if or(parameters.testAzureLinuxStreamingImage, parameters.testUbuntuStreamingImage) }}:
    - stage: BuildInstallerForDirectStreaming_${{ parameters.architecture }}
      displayName: Build ${{ parameters.architecture }} Installer for Direct Streaming
      dependsOn:
        - ${{ if eq(parameters.architecture, 'arm64') }}:
          - GetTridentBinaries_rpms_arm64
          - BuildingTools_arm64
        - ${{ if eq(parameters.architecture, 'amd64') }}:
          - GetTridentBinaries_rpms_amd64
          - BuildingTools
        - PrepareSSHKeys
      jobs:
        # Build Trident direct streaming installer ISO
        - template: stages/trident_images/build-image.yml
          parameters:
            labelPrefix: "" # No prefix for this image
            architecture: ${{ parameters.architecture }}
            label: "trident-direct-streaming-installer-${{ parameters.architecture }}"
            makeTarget: "artifacts/trident-direct-streaming-installer-${{ parameters.architecture }}.iso"
            ${{ if eq(parameters.architecture, 'arm64') }}:
              baseimgType: core_arm64
            ${{ if eq(parameters.architecture, 'amd64') }}:
              baseimgType: baremetal
            # Need rcp-agent from go tools
            downloadGoTools: true
            timeoutInMinutes: 30

  - ${{ if parameters.testAzureLinuxStreamingImage }}:
    - stage: BuildImagesForDirectStreaming_azurelinux_${{ parameters.architecture }}
      displayName: Build ${{ parameters.architecture }} azurelinux Images for Direct Streaming
      dependsOn:
        - ${{ if eq(parameters.architecture, 'arm64') }}:
          - GetTridentBinaries_rpms_arm64
          - BuildingTools_arm64
        - ${{ if eq(parameters.architecture, 'amd64') }}:
          - GetTridentBinaries_rpms_amd64
          - BuildingTools
        - PrepareSSHKeys
      jobs:
        # Build direct streaming COSI VHD
        - template: stages/trident_images/build-image.yml
          parameters:
            labelPrefix: "" # No prefix for this image
            architecture: ${{ parameters.architecture }}
            micBuildType: ${{ parameters.micBuildType }}
            micVersion: ${{ parameters.micVersion }}
            label: "azurelinux-direct-streaming-testimage-${{ parameters.architecture }}"
            makeTarget: "artifacts/azurelinux-direct-streaming-testimage-${{ parameters.architecture }}.cosi"
            ${{ if eq(parameters.architecture, 'arm64') }}:
              baseimgType: core_arm64
            ${{ if eq(parameters.architecture, 'amd64') }}:
              baseimgType: baremetal
            timeoutInMinutes: 30

    # Run netlaunch test to validate direct streaming installer
    - template: stages/direct-streaming/netlaunch-testing.yml
      parameters:
        architecture: ${{ parameters.architecture }}
        buildImageStage: BuildImagesForDirectStreaming_azurelinux_${{ parameters.architecture }}
        testImageName: azurelinux-direct-streaming-testimage-${{ parameters.architecture }}
        streamingImageScenario: azurelinux

  - ${{ if parameters.testUbuntuStreamingImage }}:
    - ${{ each ubuntuVersion in parameters.ubuntuVersions }}:
      - stage: BuildImagesForDirectStreaming_ubuntu_${{ubuntuVersion}}_${{ parameters.architecture }}
        displayName: Build ${{ parameters.architecture }} ubuntu ${{ubuntuVersion}} Images for Direct Streaming
        dependsOn:
          - ${{ if eq(parameters.architecture, 'arm64') }}:
            - GetTridentBinaries_rpms_arm64
            - BuildingTools_arm64
          - ${{ if eq(parameters.architecture, 'amd64') }}:
            - GetTridentBinaries_rpms_amd64
            - BuildingTools
          - PrepareSSHKeys
        jobs:
          # Build direct streaming COSI VHD
          - template: stages/trident_images/build-image.yml
            parameters:
              labelPrefix: "" # No prefix for this image
              architecture: ${{ parameters.architecture }}
              micBuildType: ${{ parameters.micBuildType }}
              micVersion: ${{ parameters.micVersion }}
              label: "ubuntu-direct-streaming-testimage-${{ubuntuVersion}}-${{ parameters.architecture }}"
              makeTarget: "artifacts/ubuntu-direct-streaming-testimage-${{ubuntuVersion}}-${{ parameters.architecture }}.cosi"
              baseimgType: ubuntu_${{ubuntuVersion}}_${{ parameters.architecture }}
              timeoutInMinutes: 30
      # Run netlaunch test to validate direct streaming installer
      - template: stages/direct-streaming/netlaunch-testing.yml
        parameters:
          architecture: ${{ parameters.architecture }}
          buildImageStage: BuildImagesForDirectStreaming_ubuntu_${{ubuntuVersion}}_${{ parameters.architecture }}
          testImageName: ubuntu-direct-streaming-testimage-${{ubuntuVersion}}-${{ parameters.architecture }}
          streamingImageScenario: ubuntu

  - ${{ if and(parameters.testFairwaterStreamingImage, eq(parameters.architecture, 'arm64')) }}:
    - stage: BuildImagesForDirectStreaming_fairwater_${{ parameters.architecture }}
      displayName: Build ${{ parameters.architecture }} fairwater Images for Direct Streaming
      dependsOn:
        - GetTridentBinaries_rpms_arm64
        - BuildingTools_arm64
        - PrepareSSHKeys
      jobs:
        # Build direct streaming COSI VHD
        - template: stages/trident_images/build-image.yml
          parameters:
            labelPrefix: "" # No prefix for this image
            architecture: ${{ parameters.architecture }}
            # TODO: need newest IC to overcome fstab issues with IC 1.2,
            #       use dev and main for now to get the most recent.
            micBuildType: dev
            micVersion: "main"
            label: "fairwater-direct-streaming-testimage-2404-${{ parameters.architecture }}"
            makeTarget: "artifacts/fairwater-direct-streaming-testimage-2404-${{ parameters.architecture }}.cosi"
            baseimgType: "fairwater_2404_${{ parameters.architecture }}"
            timeoutInMinutes: 30
    # Run netlaunch test to validate direct streaming installer
    - template: stages/direct-streaming/netlaunch-testing.yml
      parameters:
        architecture: ${{ parameters.architecture }}
        buildImageStage: BuildImagesForDirectStreaming_fairwater_${{ parameters.architecture }}
        testImageName: fairwater-direct-streaming-testimage-2404-${{ parameters.architecture }}
        streamingImageScenario: fairwater
