parameters:
  - name: architecture
    type: string
    values:
      - arm64
      - amd64
    default: arm64
  - name: testAzureLinuxStreamingImage
    type: boolean
    default: true
  - name: testUbuntuStreamingImage
    type: boolean
    default: true

stages:
  - stage: BuildInstallerForDirectStreaming_${{ parameters.architecture }}
    displayName: Build ${{ parameters.architecture }} Installer for Direct Streaming
    dependsOn:
      - GetTridentBinaries_rpms_${{ parameters.architecture }}
      - PrepareSSHKeys
      - BuildingTools_${{ parameters.architecture }}
    jobs:
      # Build Trident direct streaming installer ISO
      - template: stages/trident_images/build-image.yml
        parameters:
          labelPrefix: "" # No prefix for this image
          architecture: ${{ parameters.architecture }}
          label: "trident-direct-streaming-installer-${{ parameters.architecture }}"
          makeTarget: "artifacts/trident-direct-streaming-installer-${{ parameters.architecture }}.iso"
          ${{ if eq(parameters.architecture, 'arm64') }}:
            baseimgType: core_arm64
          ${{ if eq(parameters.architecture, 'amd64') }}:
            baseimgType: baremetal

  - ${{ if parameters.testAzureLinuxStreamingImage }}:
    - stage: BuildImagesForDirectStreaming_azurelinux_${{ parameters.architecture }}
      displayName: Build ${{ parameters.architecture }} azurelinux Images for Direct Streaming
      dependsOn:
        - GetTridentBinaries_rpms_${{ parameters.architecture }}
        - PrepareSSHKeys
        - BuildingTools_${{ parameters.architecture }}
      jobs:
        # Build direct streaming COSI VHD
        - template: stages/trident_images/build-image.yml
          parameters:
            labelPrefix: "" # No prefix for this image
            architecture: ${{ parameters.architecture }}
            micBuildType: dev
            # TODO: merge this branch or adjust trident code to handle what is in main.
            micVersion: "user/bfjelds/cosi1.2-adjustment"
            label: "azurelinux-direct-streaming-testimage-${{ parameters.architecture }}"
            makeTarget: "artifacts/azurelinux-direct-streaming-testimage-${{ parameters.architecture }}.cosi"
            ${{ if eq(parameters.architecture, 'arm64') }}:
              baseimgType: core_arm64
            ${{ if eq(parameters.architecture, 'amd64') }}:
              baseimgType: baremetal

    # Run netlaunch test to validate direct streaming installer
    - template: stages/direct-streaming/netlaunch-testing.yml
      parameters:
        architecture: ${{ parameters.architecture }}
        streamingImageDistro: azurelinux

  - ${{ if parameters.testUbuntuStreamingImage }}:
    - stage: BuildImagesForDirectStreaming_ubuntu_${{ parameters.architecture }}
      displayName: Build ${{ parameters.architecture }} ubuntu Images for Direct Streaming
      dependsOn:
        - GetTridentBinaries_rpms_${{ parameters.architecture }}
        - PrepareSSHKeys
        - BuildingTools_${{ parameters.architecture }}
      jobs:
        # Build direct streaming COSI VHD
        - template: stages/trident_images/build-image.yml
          parameters:
            labelPrefix: "" # No prefix for this image
            architecture: ${{ parameters.architecture }}
            micBuildType: dev
            micVersion: "user/bfjelds/cosi1.2-adjustment"
            label: "ubuntu-direct-streaming-testimage-${{ parameters.architecture }}"
            makeTarget: "artifacts/ubuntu-direct-streaming-testimage-${{ parameters.architecture }}.cosi"
            ${{ if eq(parameters.architecture, 'arm64') }}:
              baseimgType: core_arm64
            ${{ if eq(parameters.architecture, 'amd64') }}:
              baseimgType: baremetal

    # Run netlaunch test to validate direct streaming installer
    - template: stages/direct-streaming/netlaunch-testing.yml
      parameters:
        architecture: ${{ parameters.architecture }}
        streamingImageDistro: ubuntu

