parameters:
  - name: pipelineArchitecture
    type: string
    values:
      - arm64
      - amd64
    default: amd64

  - name: targetArchitecture
    type: string
    values:
      - arm64
      - amd64
    default: amd64

  - name: testAzureLinuxStreamingImage
    type: boolean
    default: true

  - name: testUbuntuStreamingImage
    type: boolean
    default: true

  - name: micBuildType
    displayName: MIC Build Type
    type: string
    values:
      - dev
      - preview
      - release
    default: release

  - name: micVersion
    displayName: MIC Version
    type: string
    default: "*.*.*"

  - name: testGB200StreamingImage
    type: boolean
    default: false

  - name: ubuntuVersions
    type: object
    values:
      - "2204"
      - "2404"
    default:
      - "2204"
      - "2404"

  - name: dependsOnStage
    type: string
    default: ""

  # Define whether to run tests using SecureBoot or not. This impacts both
  # which tests run (many encryption-related tests only run with SecureBoot enabled) and
  # how the test machines are configured.
  - name: testSecureBoot
    type: boolean
    default: true

stages:
  - ${{ if or(parameters.testAzureLinuxStreamingImage, parameters.testUbuntuStreamingImage) }}:
    - stage: BuildInstallerForDirectStreaming_${{ parameters.targetArchitecture }}
      displayName: Build ${{ parameters.targetArchitecture }} Installer for Direct Streaming
      dependsOn:
        - ${{ if eq(parameters.pipelineArchitecture, 'arm64') }}:
          - BuildingTools_arm64
        - ${{ if eq(parameters.pipelineArchitecture, 'amd64') }}:
          - BuildingTools
        - ${{ if eq(parameters.targetArchitecture, 'arm64') }}:
          - GetTridentBinaries_rpms_arm64
        - ${{ if eq(parameters.targetArchitecture, 'amd64') }}:
          - GetTridentBinaries_rpms_amd64
        - PrepareSSHKeys
        - ${{ if ne(parameters.dependsOnStage, '') }}:
          - ${{ parameters.dependsOnStage }}
      jobs:
        # Build Trident direct streaming installer ISO
        - template: stages/trident_images/build-image.yml
          parameters:
            labelPrefix: "" # No prefix for this image
            pipelineArchitecture: ${{ parameters.pipelineArchitecture }}
            targetArchitecture: ${{ parameters.targetArchitecture }}
            label: "trident-direct-streaming-installer-${{ parameters.targetArchitecture }}"
            makeTarget: "artifacts/trident-direct-streaming-installer-${{ parameters.targetArchitecture }}.iso"
            ${{ if eq(parameters.targetArchitecture, 'arm64') }}:
              baseimgType: core_arm64
            ${{ if eq(parameters.targetArchitecture, 'amd64') }}:
              baseimgType: baremetal
            # Need rcp-agent from go tools
            downloadGoTools: true
            timeoutInMinutes: 30

  - ${{ if parameters.testAzureLinuxStreamingImage }}:
    - stage: BuildImagesForDirectStreaming_azurelinux_${{ parameters.targetArchitecture }}
      displayName: Build ${{ parameters.targetArchitecture }} azurelinux Images for Direct Streaming
      dependsOn:
        - ${{ if eq(parameters.targetArchitecture, 'arm64') }}:
          - GetTridentBinaries_rpms_arm64
        - ${{ if eq(parameters.targetArchitecture, 'amd64') }}:
          - GetTridentBinaries_rpms_amd64
        - ${{ if eq(parameters.pipelineArchitecture, 'arm64') }}:
          - BuildingTools_arm64
        - ${{ if eq(parameters.pipelineArchitecture, 'amd64') }}:
          - BuildingTools
        - PrepareSSHKeys
        - ${{ if ne(parameters.dependsOnStage, '') }}:
          - ${{ parameters.dependsOnStage }}
      jobs:
        # Build direct streaming COSI VHD
        - template: stages/trident_images/build-image.yml
          parameters:
            labelPrefix: "" # No prefix for this image
            pipelineArchitecture: ${{ parameters.pipelineArchitecture }}
            targetArchitecture: ${{ parameters.targetArchitecture }}
            micBuildType: ${{ parameters.micBuildType }}
            micVersion: ${{ parameters.micVersion }}
            label: "azurelinux-direct-streaming-testimage-${{ parameters.targetArchitecture }}"
            makeTarget: "artifacts/azurelinux-direct-streaming-testimage-${{ parameters.targetArchitecture }}.cosi"
            ${{ if eq(parameters.targetArchitecture, 'arm64') }}:
              baseimgType: core_arm64
            ${{ if eq(parameters.targetArchitecture, 'amd64') }}:
              baseimgType: baremetal
            timeoutInMinutes: 30

    # Run netlaunch test to validate direct streaming installer
    - template: stages/direct-streaming/netlaunch-testing.yml
      parameters:
        targetArchitecture: ${{ parameters.targetArchitecture }}
        buildImageStage: BuildImagesForDirectStreaming_azurelinux_${{ parameters.targetArchitecture }}
        testImageName: azurelinux-direct-streaming-testimage-${{ parameters.targetArchitecture }}
        streamingImageScenario: azurelinux
        testSecureBoot: ${{ parameters.testSecureBoot }}

  - ${{ if parameters.testUbuntuStreamingImage }}:
    - ${{ each ubuntuVersion in parameters.ubuntuVersions }}:
      - stage: BuildImagesForDirectStreaming_ubuntu_${{ubuntuVersion}}_${{ parameters.targetArchitecture }}
        displayName: Build ${{ parameters.targetArchitecture }} ubuntu ${{ubuntuVersion}} Images for Direct Streaming
        dependsOn:
          - ${{ if eq(parameters.pipelineArchitecture, 'arm64') }}:
            - BuildingTools_arm64
          - ${{ if eq(parameters.pipelineArchitecture, 'amd64') }}:
            - BuildingTools
          - PrepareSSHKeys
          - ${{ if ne(parameters.dependsOnStage, '') }}:
            - ${{ parameters.dependsOnStage }}
        jobs:
          # Build direct streaming COSI VHD
          - template: stages/trident_images/build-image.yml
            parameters:
              labelPrefix: "" # No prefix for this image
              pipelineArchitecture: ${{ parameters.pipelineArchitecture }}
              targetArchitecture: ${{ parameters.targetArchitecture }}
              micBuildType: ${{ parameters.micBuildType }}
              micVersion: ${{ parameters.micVersion }}
              label: "ubuntu-direct-streaming-testimage-${{ubuntuVersion}}-${{ parameters.targetArchitecture }}"
              makeTarget: "artifacts/ubuntu-direct-streaming-testimage-${{ubuntuVersion}}-${{ parameters.targetArchitecture }}.cosi"
              baseimgType: ubuntu_${{ubuntuVersion}}_${{ parameters.targetArchitecture }}
              downloadTrident: false
              timeoutInMinutes: 30
      # Run netlaunch test to validate direct streaming installer
      - template: stages/direct-streaming/netlaunch-testing.yml
        parameters:
          targetArchitecture: ${{ parameters.targetArchitecture }}
          buildImageStage: BuildImagesForDirectStreaming_ubuntu_${{ubuntuVersion}}_${{ parameters.targetArchitecture }}
          testImageName: ubuntu-direct-streaming-testimage-${{ubuntuVersion}}-${{ parameters.targetArchitecture }}
          streamingImageScenario: ubuntu
          testSecureBoot: ${{ parameters.testSecureBoot }}

  - ${{ if and(parameters.testGB200StreamingImage, eq(parameters.targetArchitecture, 'arm64')) }}:
    - stage: BuildImagesForDirectStreaming_gb200_${{ parameters.targetArchitecture }}
      displayName: Build ${{ parameters.targetArchitecture }} gb200 Images for Direct Streaming
      dependsOn:
        - ${{ if eq( parameters.pipelineArchitecture, "arm64") }}:
          - BuildingTools_arm64
        - ${{ if eq( parameters.pipelineArchitecture, "amd64") }}:
          - BuildingTools
        - PrepareSSHKeys
        - ${{ if ne(parameters.dependsOnStage, '') }}:
          - ${{ parameters.dependsOnStage }}
      jobs:
        # Build direct streaming COSI VHD
        - template: stages/trident_images/build-image.yml
          parameters:
            labelPrefix: "" # No prefix for this image
            pipelineArchitecture: ${{ parameters.pipelineArchitecture }}
            targetArchitecture: ${{ parameters.targetArchitecture }}
            # TODO: need newest IC to overcome fstab issues with IC 1.2,
            #       use dev and main for now to get the most recent.
            # micBuildType: ${{ parameters.micBuildType }}
            # micVersion: ${{ parameters.micVersion }}
            micBuildType: dev
            micVersion: main
            label: "gb200-direct-streaming-testimage-2404-${{ parameters.targetArchitecture }}"
            makeTarget: "artifacts/gb200-direct-streaming-testimage-2404-${{ parameters.targetArchitecture }}.cosi"
            baseimgType: "gb200_2404_${{ parameters.targetArchitecture }}"
            downloadTrident: false
            timeoutInMinutes: 60

    # Run netlaunch test to validate direct streaming installer
    - template: stages/direct-streaming/netlaunch-testing.yml
      parameters:
        targetArchitecture: ${{ parameters.targetArchitecture }}
        buildImageStage: BuildImagesForDirectStreaming_gb200_${{ parameters.targetArchitecture }}
        testImageName: gb200-direct-streaming-testimage-2404-${{ parameters.targetArchitecture }}
        streamingImageScenario: gb200
        testSecureBoot: ${{ parameters.testSecureBoot }}
