parameters:
  - name: streamingImageDistro
    type: string
    values:
      - ubuntu
      - azurelinux
    default: azurelinux
  - name: architecture
    type: string
    values:
      - arm64
      - amd64
    default: arm64

stages:
  - stage: BuildImagesForDirectStreaming_${{ parameters.streamingImageDistro }}_${{ parameters.architecture }}
    displayName: Build ${{ parameters.architecture }} ${{ parameters.streamingImageDistro }} Images for Direct Streaming
    dependsOn:
      - GetTridentBinaries_rpms_${{ parameters.architecture }}
      - PrepareSSHKeys
      - BuildingTools_${{ parameters.architecture }}
      - BuildInstallerForDirectStreaming_${{ parameters.architecture }}
    jobs:
      # Build direct streaming COSI VHD
      - template: stages/trident_images/build-image.yml
        parameters:
          labelPrefix: "" # No prefix for this image
          architecture: ${{ parameters.architecture }}
          downloadGoTools: true
          ${{ if eq(parameters.streamingImageDistro, 'ubuntu') }}:
            micBuildType: dev
          label: "${{ parameters.streamingImageDistro }}-direct-streaming-testimage-${{ parameters.architecture }}"
          makeTarget: "artifacts/${{ parameters.streamingImageDistro }}-direct-streaming-testimage-${{ parameters.architecture }}.cosi"
          ${{ if eq(parameters.architecture, 'arm64') }}:
            baseimgType: core_arm64
          ${{ if eq(parameters.architecture, 'amd64') }}:
            baseimgType: baremetal

  # Run netlaunch test to validate direct streaming installer
  - template: stages/direct-streaming/netlaunch-testing.yml
    parameters:
      architecture: ${{ parameters.architecture }}
      streamingImageDistro: ${{ parameters.streamingImageDistro }}

