parameters:
  - name: architecture
    type: string
    values:
      - arm64
      - amd64
    default: arm64

stages:
  - stage: BuildInstallerForDirectStreaming_${{ parameters.architecture }}
    displayName: Build ${{ parameters.architecture }} Installer for Direct Streaming
    dependsOn:
      - GetTridentBinaries_rpms_${{ parameters.architecture }}
      - PrepareSSHKeys
      - BuildingTools_${{ parameters.architecture }}
    jobs:
      # Build Trident direct streaming installer ISO
      - template: stages/trident_images/build-image.yml
        parameters:
          labelPrefix: "" # No prefix for this image
          architecture: ${{ parameters.architecture }}
          downloadGoTools: true
          label: "trident-direct-streaming-installer-${{ parameters.architecture }}"
          ${{ if eq(parameters.architecture, 'arm64') }}:
            makeTarget: "artifacts/trident-direct-streaming-installer-arm64.iso"
            baseimgType: core_arm64
          ${{ if eq(parameters.architecture, 'amd64') }}:
            makeTarget: "artifacts/trident-direct-streaming-installer.iso"
            baseimgType: baremetal
