parameters:
  - name: "stageType"
    displayName: "Pipeline configuration type"
    type: string
    default: ci
    values:
      - pr-e2e
      - pr-e2e-azure
      - ci
      - pre
      - rel
      - full-validation

  - name: baseimgBuildType
    displayName: Base Image build type
    type: string
    values:
      - dev
      - preview
      - release
    default: "release"

  - name: baseImagePipelineBuildId
    type: string
    default: "latestFromBranch"

  - name: baseImageArm64PipelineBuildId
    type: string
    default: "latestFromBranch"

  - name: blockPublishing
    displayName: "Block publishing to artifact feed"
    type: boolean
    default: false

  - name: forceTridentRebuild
    displayName: "Force trident rebuild rather than downloading previously built."
    type: boolean
    default: false

  - name: includeAzure
    displayName: "Include Azure testing"
    type: boolean
    default: false

  - name: micBuildType
    displayName: MIC Build Type
    type: string
    values:
      - dev
      - preview
      - release
    default: release

  - name: micVersion
    displayName: MIC Version
    type: string
    default: "*.*.*"

stages:
  # Trident Build/Download
  - template: stages/trident_rpms/trident-stage.yml
    parameters:
      stageType: ${{ parameters.stageType }}
      tridentArtifactName: trident-binaries
      codeCoverage: false
      baseimgBuildType: ${{ parameters.baseimgBuildType }}
      baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}
      baseImageArm64PipelineBuildId: ${{ parameters.baseImageArm64PipelineBuildId }}
      forceTridentRebuild: ${{ parameters.forceTridentRebuild }}

  # Build tools (Go stuff)
  - template: stages/building_tools/building-tools.yml

  # Makefile validation, only for CI and PR-E2E
  - ${{ if or(eq(parameters.stageType, 'ci'), eq(parameters.stageType, 'pr-e2e'), eq(parameters.stageType, 'pr-e2e-azure')) }}:
      - template: stages/validate_makefile/dev-build.yml

  # Build Trident container image
  - template: stages/build_docker_image/trident-container.yml
    parameters:
      baseimgBuildType: ${{ parameters.baseimgBuildType }}
      baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}

  # Build Trident installer ISO (host)
  - template: stages/build_image/trident-testimg.yml
    parameters:
      imageName: build/trident-installer-testimage.iso
      outputArtifactName: trident-installer-testimage
      baseimgBuildType: ${{ parameters.baseimgBuildType }}
      baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}
      micBuildType: ${{ parameters.micBuildType }}
      micVersion: ${{ parameters.micVersion }}

  # Build Trident split (stage and finalize separated) installer ISO (host)
  - template: stages/build_image/trident-testimg.yml
    parameters:
      imageName: build/trident-split-installer-testimage.iso
      outputArtifactName: trident-split-installer-testimage
      baseimgBuildType: ${{ parameters.baseimgBuildType }}
      baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}
      micBuildType: ${{ parameters.micBuildType }}
      micVersion: ${{ parameters.micVersion }}

  # Build Trident installer ISO (container)
  - template: stages/build_image/trident-testimg.yml
    parameters:
      imageName: build/trident-container-installer-testimage.iso
      outputArtifactName: trident-container-installer-testimage
      baseimgBuildType: ${{ parameters.baseimgBuildType }}
      baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}
      runtimeEnv: "container"
      micBuildType: ${{ parameters.micBuildType }}
      micVersion: ${{ parameters.micVersion }}

  # Build Trident test image (regular)
  - template: stages/build_image/trident-testimg.yml
    parameters:
      imageName: build/trident-testimage.cosi
      outputArtifactName: trident-testimage
      baseimgBuildType: ${{ parameters.baseimgBuildType }}
      baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}
      mkcosiTemplate: "regular"
      micBuildType: ${{ parameters.micBuildType }}
      micVersion: ${{ parameters.micVersion }}

  # Build Trident test image (container)
  - template: stages/build_image/trident-testimg.yml
    parameters:
      imageName: build/trident-container-testimage.cosi
      outputArtifactName: trident-container-testimage
      baseimgBuildType: ${{ parameters.baseimgBuildType }}
      baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}
      runtimeEnv: "container"
      mkcosiTemplate: "regular"
      micBuildType: ${{ parameters.micBuildType }}
      micVersion: ${{ parameters.micVersion }}

  # Build Trident test image for verity (host)
  - template: stages/build_image/trident-testimg.yml
    parameters:
      imageName: build/trident-verity-testimage.cosi
      outputArtifactName: trident-verity-testimage
      baseimgBuildType: ${{ parameters.baseimgBuildType }}
      baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}
      mkcosiTemplate: "verity"
      micBuildType: ${{ parameters.micBuildType }}
      micVersion: ${{ parameters.micVersion }}

  # Build Trident test image for verity (container)
  - template: stages/build_image/trident-testimg.yml
    parameters:
      imageName: build/trident-container-verity-testimage.cosi
      outputArtifactName: trident-container-verity-testimage
      baseimgBuildType: ${{ parameters.baseimgBuildType }}
      baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}
      runtimeEnv: "container"
      mkcosiTemplate: "verity"
      micBuildType: ${{ parameters.micBuildType }}
      micVersion: ${{ parameters.micVersion }}

  - ${{ if or(parameters.forceTridentRebuild, eq(parameters.stageType, 'pr-e2e'), eq(parameters.stageType, 'ci'), eq(parameters.stageType, 'pr-e2e-azure')) }}:
      # Build USB-ISO
      - template: stages/trident_usb_iso/trident-usb-iso.yml
        parameters:
          baseimgBuildType: ${{ parameters.baseimgBuildType }}
          baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}
          micBuildType: ${{ parameters.micBuildType }}
          micVersion: ${{ parameters.micVersion }}
  - ${{ else }}:
      # Download USB-ISO from previous
      - template: stages/download_staged/download-staged.yml
        parameters:
          stageType: ${{ parameters.stageType }}
          artifactName: azl-installer
          packageName: usb-iso

  # dom0 is failing for not known reasons ... comment out for now to unblock, longterm this may
  # be removed from trident pipelines alltogether in favor of being only test-images
  # - ${{ if or(eq(parameters.stageType, 'ci'), eq(parameters.stageType, 'pr-e2e')) }}:
  #   # Build Trident test image (dom0: mshv+ch)
  #   - template: stages/build_image/trident-mshvch-dom0-testimg.yml

  # Test Servicing on VMs
  - template: stages/testing_servicing/vm-testing.yml
    parameters:
      baseimgBuildType: ${{ parameters.baseimgBuildType }}
      baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}
      includeQemu: true
      includeAzure: ${{ parameters.includeAzure }}
      micBuildType: ${{ parameters.micBuildType }}
      micVersion: ${{ parameters.micVersion }}
      verboseLogging: true

  # TESTING stages for PRERELEASE
  - ${{ if eq(parameters.stageType, 'pre') }}:
      # Functional Testing
      - template: stages/testing_functional/functional-testing.yml

      # VM Testing (host, daily)
      - template: stages/testing_vm/netlaunch-testing.yml
        parameters:
          buildPurpose: "daily"
          runtimeEnv: "host"

      # BM Testing (host, daily)
      - template: stages/testing_baremetal/baremetal-testing.yml
        parameters:
          buildPurpose: "daily"
          runtimeEnv: "host"

      # BM Testing (container, daily)
      - template: stages/testing_baremetal/baremetal-testing.yml
        parameters:
          buildPurpose: "daily"
          runtimeEnv: "container"
          extraDependsOn: "BaremetalDeploymentTesting_host"

      # VM Testing (container, daily)
      - template: stages/testing_vm/netlaunch-testing.yml
        parameters:
          buildPurpose: "daily"
          runtimeEnv: "container"

  # TESTING stages for full validation matrix host/container and bm/bm
  - ${{ if eq(parameters.stageType, 'full-validation') }}:
      # Functional Testing
      - template: stages/testing_functional/functional-testing.yml

      # VM Testing (host, weekly)
      - template: stages/testing_vm/netlaunch-testing.yml
        parameters:
          buildPurpose: "weekly"
          runtimeEnv: "host"

      # VM Testing (container, weekly)
      - template: stages/testing_vm/netlaunch-testing.yml
        parameters:
          buildPurpose: "weekly"
          runtimeEnv: "container"

      # BM Testing (host, weekly)
      - template: stages/testing_baremetal/baremetal-testing.yml
        parameters:
          buildPurpose: "weekly"
          runtimeEnv: "host"

      # BM Testing (container, weekly)
      - template: stages/testing_baremetal/baremetal-testing.yml
        parameters:
          buildPurpose: "weekly"
          runtimeEnv: "container"
          extraDependsOn: "BaremetalDeploymentTesting_host"

  # TESTING stages for CI
  - ${{ if eq(parameters.stageType, 'ci') }}:
      # Functional Testing
      - template: stages/testing_functional/functional-testing.yml

      # VM Testing (host, post_merge)
      - template: stages/testing_vm/netlaunch-testing.yml
        parameters:
          buildPurpose: "post_merge"
          runtimeEnv: "host"

      # VM Testing (container, post_merge)
      - template: stages/testing_vm/netlaunch-testing.yml
        parameters:
          buildPurpose: "post_merge"
          runtimeEnv: "container"

  # TESTING stages for PR-E2E
  - ${{ if eq(parameters.stageType, 'pr-e2e') }}:
      # Functional Testing (short version)
      - template: stages/testing_functional/functional-testing.yml
        parameters:
          buildPurpose: "validation"

      # VM Testing (host, pullrequest)
      - template: stages/testing_vm/netlaunch-testing.yml
        parameters:
          buildPurpose: "pullrequest"
          runtimeEnv: "host"

      # VM Testing (container, pullrequest)
      - template: stages/testing_vm/netlaunch-testing.yml
        parameters:
          buildPurpose: "pullrequest"
          runtimeEnv: "container"

  # PUBLISHING
  #
  # Only enabled for PRERELEASE and CI unless blockPublishing is set to true.
  - ${{ if eq(parameters.blockPublishing, false) }}:
      - ${{ if or(eq(parameters.stageType, 'pre'), eq(parameters.stageType, 'ci')) }}:
          - template: stages/publishing/publish.yml
            parameters:
              stageType: ${{ parameters.stageType }}
