parameters:
  - name: "stageType"
    displayName: "Controls whether this is a pre-release or a CI run."
    type: string
    default: ci
    values:
      - ci
      - pre
      - rel

  - name: blockPublishing
    displayName: "Block publishing to artifact feed."
    type: boolean
    default: false

stages:
  - template: stages/trident_rpms/trident-stage.yml
    parameters:
      stageType: ${{ parameters.stageType }}
      tridentArtifactName: trident-binaries
      codeCoverage: false

  - ${{ if eq(parameters.stageType, 'ci') }}:
      - template: stages/validate_makefile/dev-build.yml

  - template: stages/build_image/trident-testimg.yml
    parameters:
      imageName: build/trident-installer-testimage.iso
      outputArtifactName: trident-installer-testimage

  - template: stages/build_image/trident-testimg.yml
    parameters:
      imageName: build/trident-container-installer-testimage.iso
      outputArtifactName: trident-container-installer-testimage

  - template: stages/build_image/trident-testimg.yml
    parameters:
      imageName: trident-testimage
      outputArtifactName: trident-testimage

  - template: stages/build_image/trident-testimg.yml
    parameters:
      imageName: trident-verity-testimage
      outputArtifactName: trident-verity-testimage

  - template: stages/building_tools/building-tools.yml
  
  - template: stages/build_docker_image/trident-container.yml

  - template: stages/deployment_testing/servicing/vm-testing.yml

  - ${{ if eq(parameters.blockPublishing, false) }}:
      - template: stages/deployment_testing/functional_testing/functional-testing.yml
      - template: stages/publishing/publish.yml
        parameters:
          stageType: ${{ parameters.stageType }}
  - ${{ else }}:
      - template: stages/deployment_testing/functional_testing/functional-testing.yml
        parameters:
          buildPurpose: "validation"

  - ${{ if eq(parameters.stageType, 'pre') }}:
      - template: stages/deployment_testing/vm/netlaunch-testing.yml
        parameters:
          buildPurpose: "daily"
          runtimeEnv: "host"
  
      - template: stages/deployment_testing/baremetal/baremetal-testing.yml
        parameters:
          buildPurpose: "daily"
          runtimeEnv: "host"

      - template: stages/deployment_testing/vm/netlaunch-testing.yml
        parameters:
          buildPurpose: "daily"
          installerISO: trident-container-installer-testimage
          runtimeEnv: "container"

  - ${{ else }}:
      - template: stages/deployment_testing/vm/netlaunch-testing.yml
        parameters:
          buildPurpose: "post_merge"
          installerISO: trident-installer-testimage
          runtimeEnv: "host"
          
      - template: stages/deployment_testing/vm/netlaunch-testing.yml
        parameters:
          buildPurpose: "post_merge"
          installerISO: trident-container-installer-testimage
          runtimeEnv: "container"
