# Template meant for use in the release pipeline.

parameters:
  - name: specificVersion
    type: string
    displayName: |
      Specific version of the package to download, leave empty to download latest.
    default: ""

  - name: skipPublishing
    type: boolean
    displayName: "Skip publishing stage"
    default: false

  - name: sourceCommit
    type: string
    displayName: "The commit hash of the source code to package."
    default: ""

stages:
  - template: stages/download_staged/download-staged.yml
    parameters:
      stageType: rel
      artifactName: trident-binaries
      specificVersion: ${{ parameters.specificVersion }}
      packageName: rpms
      targetArchitecture: amd64

  - template: stages/download_staged/download-staged.yml
    parameters:
      stageType: rel
      artifactName: trident-binaries
      specificVersion: ${{ parameters.specificVersion }}
      packageName: rpms
      targetArchitecture: arm64

  - ${{ if ne(parameters.skipPublishing, true) }}:
      - template: stages/publishing/publish.yml
        parameters:
          stageType: rel

  - template: stages/publishing/release-artifacts.yml
    parameters:
      sourceCommit: ${{ parameters.sourceCommit }}
