# TRIDENT PLATFORM CICD TEMPLATE
# This template is used by the platform-cicd-preview pipeline to
# build and test trident deployment scenarios for a specified AZL
# preview build.

parameters:
  - name: baremetalTestsEnabled
    type: boolean
    default: false

  - name: baseImageArtifactStage
    type: string

  - name: targetArchitecture
    type: string
    values:
      - amd64
      - arm64

  - name: tridentBuildOptions
    displayName: "Trident Build Options"
    type: string
    default: prebuilt
    values:
      - default
      - forceBuild
      - prebuilt

  - name: testSecureBoot
    displayName: "Test Secure Boot"
    type: boolean
    default: true

  - name: micVersion
    displayName: MIC Version
    type: string
    default: "*.*.*"

  - name: acrSubscriptionConnection
    type: string
    default: trident-dev-acr-write-umi-ECF
    values:
      - maritimus-dev-acr-write-umi
      - trident-dev-acr-write-umi-ECF

stages:
  - ${{ if eq( parameters.targetArchitecture, 'amd64') }}:
      - template: e2e-template.yml
        parameters:
          stageType: azl-validation
          baremetalTestsEnabled: ${{ parameters.baremetalTestsEnabled }}
          baseImageArtifactStage: ${{ parameters.baseImageArtifactStage }}
          tridentBuildOptions: ${{ parameters.tridentBuildOptions }}
          testSecureBoot: ${{ parameters.testSecureBoot }}
          micBuildType: dev
          micVersion: ${{ parameters.micVersion }}
          acrSubscriptionConnection: ${{ parameters.acrSubscriptionConnection }}

  - ${{ if eq( parameters.targetArchitecture, 'arm64') }}:
      - template: e2e-arm64-template.yml
        parameters:
          stageType: azl-validation
          tridentBuildOptions: ${{ parameters.tridentBuildOptions }}
          baseImageArtifactStage: ${{ parameters.baseImageArtifactStage }}
