# TRIDENT PLATFORM CICD TEMPLATE
# This template is used by the platform-cicd-preview pipeline to
# build and test trident deployment scenarios for a specified AZL
# preview build.

parameters:
  - name: baremetalTestsEnabled
    type: boolean
    default: false

  - name: baseImageArtifactStage
    type: string
  
  - name: targetArchitecture
    type: string
    values:
      - amd64
      - arm64

  - name: tridentBuildOptions
    displayName: "Trident Build Options"
    type: string
    default: prebuilt
    values:
      - default
      - forceBuild
      - prebuilt

  - name: testSecureBoot
    displayName: "Test Secure Boot"
    type: boolean
    default: true

stages:
  - ${{ if eq( parameters.targetArchitecture, 'amd64') }}:
    - template: e2e-template.yml
      parameters:
        stageType: azl-validation
        baremetalTestsEnabled: ${{ parameters.baremetalTestsEnabled }}
        baseImageArtifactStage: ${{ parameters.baseImageArtifactStage }}
        tridentBuildOptions: ${{ parameters.tridentBuildOptions }}
        testSecureBoot: ${{ parameters.testSecureBoot }}

  - ${{ if eq( parameters.targetArchitecture, 'arm64') }}:
    - template: e2e-arm64-template.yml
      parameters:
        stageType: azl-validation
        tridentBuildOptions: ${{ parameters.tridentBuildOptions }}
        baseImageArtifactStage: ${{ parameters.baseImageArtifactStage }}
