# TRIDENT PLATFORM CICD TEMPLATE
# This template is used by the platform-cicd-preview pipeline to
# build and test Trident deployment scenarios for a specified AZL
# preview build.

parameters:
  - name: micBuildType
    displayName: MIC Build Type
    type: string
    values:
    - dev
    - preview
    - release
    default: release

  - name: micVersion
    displayName: MIC Version
    type: string
    default: "*.*.*"

  - name: osModifierBranch
    displayName: Branch to use for OS Modifier (specify 'submodule' to use trident's current submodule)
    type: string
    default: "main"

  - name: baseImageArtifactStage
    type: string

stages:
    - template: e2e-extended-template.yml
      parameters:
        stageType: ci
        blockPublishing: true
        forceTridentRebuild: true
        micBuildType: ${{ parameters.micBuildType }}
        micVersion: ${{ parameters.micVersion }}
        osModifierBranch: ${{ parameters.osModifierBranch }}
        baseImageArtifactStage: ${{ parameters.baseImageArtifactStage }}
