# TRIDENT PLATFORM CICD TEMPLATE
# This template is used by the platform-cicd-preview pipeline to
# build and test trident deployment scenarios for a specified AZL
# preview build.

parameters:
  - name: baremetalTestsEnabled
    type: boolean
    default: false

  - name: baseImageArtifactStage
    type: string
  
  - name: targetArchitecture
    type: string
    values:
      - amd64
      - arm64

stages:
  - ${{ if eq( parameters.targetArchitecture, 'amd64') }}:
    - template: e2e-template.yml
      parameters:
        stageType: pre
        blockPublishing: true
        forceTridentRebuild: true
        forceFunctionalTestImageRebuild: true
        baremetalTestsEnabled: ${{ parameters.baremetalTestsEnabled }}
        baseImageArtifactStage: ${{ parameters.baseImageArtifactStage }}

  - ${{ if eq( parameters.targetArchitecture, 'arm64') }}:
    - template: e2e-arm64-template.yml
      parameters:
        stageType: pre
        blockPublishing: true
        forceTridentRebuild: true
        baseImageArtifactStage: ${{ parameters.baseImageArtifactStage }}
