# TRIDENT PLATFORM CICD TEMPLATE
# This template is used by the platform-cicd-preview pipeline to
# build and test trident deployment scenarios for a specified AZL
# preview build.

parameters:
  - name: runBaremetalTests
    type: boolean
    default: false

  - name: baseImageArtifactStage
    type: string

stages:
    - template: e2e-template.yml
      parameters:
        stageType: pre
        blockPublishing: true
        forceTridentRebuild: true
        runBaremetalTests: ${{ parameters.runBaremetalTests }}
        baseImageArtifactStage: ${{ parameters.baseImageArtifactStage }}
