parameters:
- name: tridentRepo
  type: string
  default: self

- name: tridentArtifactSource
  type: string
  default: current # If specific, trident won't build and instead the artifact will be downloaded in other stage.

- name: publishUniversalFeed
  type: boolean
  default: false

- name: codeCoverage
  type: boolean
  default: true

stages:
- stage: Trident
  displayName: Trident RPMs

  jobs:
  - job: TestTrident
    displayName: Check and Unit Test
    condition: eq('${{ parameters.tridentArtifactSource }}', 'current')
    pool:
      type: linux

    variables:
      ob_outputDirectory: '$(Build.SourcesDirectory)/trident/out'

    steps:
    - checkout: ${{ parameters.tridentRepo }}

    - template: test-build.yml
      parameters:
         tridentSourceDirectory: $(Build.SourcesDirectory)/trident

  - job: Coverage
    displayName: Evaluate Unit Test Code Coverage
    condition: and(eq('${{ parameters.tridentArtifactSource }}', 'current'),eq(${{ parameters.codeCoverage }}, true))
    pool:
      type: linux

    variables:
      ob_outputDirectory: '$(Build.SourcesDirectory)/trident/out'

    steps:
    - checkout: ${{ parameters.tridentRepo }}

    - template: ../common_tasks/coverage.yml
      parameters:
         tridentSourceDirectory: $(Build.SourcesDirectory)/trident
         codeCoverageBaseline: 65 # Unit tests

  - job: BuildTrident
    displayName: Build Release Artifacts
    condition: eq('${{ parameters.tridentArtifactSource }}', 'current')
    pool:
      type: linux

    variables:
      ob_outputDirectory: '$(Build.SourcesDirectory)/trident/out'
      tridentSourceDirectory: $(Build.SourcesDirectory)/trident
      emu_package_name: ''
      emu_package_version: ''

    steps:
    - checkout: ${{ parameters.tridentRepo }}

    - template: ../common_tasks/download-emu.yml
      parameters:
         tridentSourceDirectory: $(Build.SourcesDirectory)/trident

    - template: release.yml
      parameters:
         tridentSourceDirectory: $(Build.SourcesDirectory)/trident
         publishUniversalFeed: ${{ parameters.publishUniversalFeed }}
