hostConfiguration:
  storage:
    disks:
      - id: os
        device: /dev/disk/by-path/pci-0000:00:1f.2-ata-2
        partitionTableType: gpt
        partitions:
          - id: esp
            type: esp
            size: 1G
          - id: root-a
            type: root
            size: 8G
          - id: root-b
            type: root
            size: 8G
          - id: web-a-e
            type: linux-generic
            size: 1G
          - id: web-b-e
            type: linux-generic
            size: 1G
          - id: trident
            type: linux-generic
            size: 1G
      - id: disk2
        device: /dev/disk/by-path/pci-0000:00:1f.2-ata-3
        partitionTableType: gpt
        partitions: []
    encryption:
      volumes:
        - id: web-a
          deviceName: web-a
          targetId: web-a-e
        - id: web-b
          deviceName: web-b
          targetId: web-b-e
    abUpdate:
      volumePairs:
        - id: web
          volumeAId: web-a
          volumeBId: web-b
        - id: root
          volumeAId: root-a
          volumeBId: root-b
    filesystems:
      - deviceId: web
        type: ext4
        mountPoint:
          path: /web
          options: defaults
      - deviceId: esp
        type: vfat
        source:
          type: image
          url: http://NETLAUNCH_HOST_ADDRESS/files/esp.rawzst
          sha256: ignored
          format: raw-zst
        mountPoint:
          path: /boot/efi
          options: umask=0077
      - deviceId: root
        type: ext4
        source:
          type: image
          url: http://NETLAUNCH_HOST_ADDRESS/files/root.rawzst
          sha256: ignored
          format: raw-zst
        mountPoint:
          path: /
          options: defaults
      - deviceId: trident
        type: ext4
        mountPoint:
          path: /var/lib/trident
          options: defaults
  scripts:
    postConfigure:
      - name: testing-privilege
        runOn:
          - clean-install
          - ab-update
        content: echo 'testing-user ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/testing-user
  os:
    network:
      version: 2
      ethernets:
        vmeths:
          match:
            name: enp*
          dhcp4: true
    users:
      - name: testing-user
        sshPublicKeys: []
        sshMode: key-only
