parameters:
  - name: "imageName"
    type: string

  - name: "registry"
    displayName: "Container registry to push to"
    type: string
    default: "maritimuspublic"

stages:
  - stage: PushTridentTestImg_${{ replace(parameters.imageName, '-', '_') }}
    displayName: Push ${{ parameters.imageName }} to ACR
    dependsOn:
      - TridentTestImg_${{ replace(parameters.imageName, '-', '_') }}

    jobs:
      - job: LoginToACR
        displayName: Login
        timeoutInMinutes: 20
        pool:
          type: linux

        steps:
          - template: .pipelines/templates/common_tasks/acr-login.yml@test-images
            parameters:
              azureSubscription: CoreOS_AzureLinux_Polar_Staging
              acr: ${{ parameters.registry }}
