parameters:
  - name: "imageName"
    type: string

  - name: "registry"
    displayName: "Container registry to push to"
    type: string
    default: "maritimuspublic"

stages:
  - stage: PushTridentTestImg_${{ replace(parameters.imageName, '-', '_') }}
    displayName: Push ${{ parameters.imageName }} to ACR
    dependsOn:
      - TridentTestImg_${{ replace(parameters.imageName, '-', '_') }}

    variables:
      ob_outputDirectory: $(Pipeline.Workspace)/s/output
      ob_artifactBaseName: ${{ parameters.imageName }}

    jobs:
      - job: LoginToAcr
        displayName: Login
        timeoutInMinutes: 20
        pool:
          type: linux

        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              containerRegistry: ${{ parameters.registry }}
              command: login
