parameters:
  - name: "repository"
    displayName: "Repository containing COSI images"
    type: string
    default: regular

  - name: "registry"
    type: string
    default: maritimuspublic

  - name: "imageName"
    type: string
    default: trident-testimage

stages:
  - stage: DeleteFromAcr
    displayName: Delete images from ACR
    condition: always()
    dependsOn:
      - TridentTestImg_${{ replace(parameters.imageName, '-', '_') }}
      - DeploymentTesting_host

    jobs:
      - job: DeleteFromAcr
        displayName: Delete ${{ parameters.imageName }} from ${{ parameters.registry }} ACR
        pool:
          type: linux

        variables:
          - name: ob_outputDirectory
            value: $(Build.SourcesDirectory)/build

        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: maritimus-staging-eastus-cr-service-connection
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -eux

                # Login to ACR
                az acr login -n ${{ parameters.registry }}

                # Delete repository with COSI images
                az acr repository delete --name ${{ parameters.registry }} --repository ${{ parameters.repository }} --yes
            displayName: "Log into ACR and delete repository"
