parameters:
  - name: "hostRepository"
    displayName: "Repository containing COSI images"
    type: string
    default: regular

  - name: "containerRepository"
    displayName: "Repository containing COSI images"
    type: string
    default: regular

  - name: "registry"
    type: string
    default: maritimuspublic

  - name: baseImagePipelineBuildId
    displayName: "Build Id of the pipeline run, default will select latest successful run from pipeline 2116 ([AMD64-6-OneBranch]-Prod-BuildImages) with tag 3.0-preview"
    type: string
    default: "latestFromBranch"

stages:
  - stage: DeleteFromAcr
    displayName: Delete from ACR
    condition: always()
    dependsOn:
      - TridentTestImg_${{ replace(parameters.hostRepository, '-', '_') }}
      - TridentTestImg_${{ replace(parameters.containerRepository, '-', '_') }}
      - DeploymentTesting_host
      - DeploymentTesting_container

    jobs:
      - job: DeleteFromAcr
        displayName: Delete images from ${{ parameters.registry }} ACR
        pool:
          type: linux

        variables:
          - name: ob_outputDirectory
            value: $(Build.SourcesDirectory)/build

        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: maritimus-staging-eastus-cr-service-connection
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -eux

                # Login to ACR
                az acr login -n ${{ parameters.registry }}

                host_repository_name=${{ parameters.hostRepository }}_${{ parameters.baseImagePipelineBuildId }}
                container_repository_name=${{ parameters.containerRepository }}_${{ parameters.baseImagePipelineBuildId }}

                # Delete repository with COSI images
                az acr repository delete --name ${{ parameters.registry }} --repository ${{ parameters.hostRepository }} --yes
                az acr repository delete --name ${{ parameters.registry }} --repository ${{ parameters.containerRepository }} --yes
            displayName: "Log into ACR and delete repository"
