hostConfiguration:
  storage:
    disks:
      - id: os
        device: /dev/disk/by-path/pci-0000:00:1f.2-ata-2
        partitionTableType: gpt
        partitions:
          - id: esp
            type: esp
            size: 1G
          - id: root-a
            type: root
            size: 8G
          - id: root-b
            type: root
            size: 8G
          - id: web-a-e-1
            type: linux-generic
            size: 1G
          - id: web-a-e-2
            type: linux-generic
            size: 1G
          - id: web-b-e-1
            type: linux-generic
            size: 1G
          - id: web-b-e-2
            type: linux-generic
            size: 1G
          - id: trident
            type: linux-generic
            size: 1G
      - id: disk2
        device: /dev/disk/by-path/pci-0000:00:1f.2-ata-3
        partitionTableType: gpt
        partitions: []
    raid:
      software:
        - id: web-a-e
          name: web-a-e
          level: raid1
          devices:
            - web-a-e-1
            - web-a-e-2
          metadataVersion: "1.2"
        - id: web-b-e
          name: web-b-e
          level: raid1
          devices:
            - web-b-e-1
            - web-b-e-2
          metadataVersion: "1.2"
    encryption:
      volumes:
        - id: web-a
          deviceName: web-a
          targetId: web-a-e
        - id: web-b
          deviceName: web-b
          targetId: web-b-e
    abUpdate:
      volumePairs:
        - id: web
          volumeAId: web-a
          volumeBId: web-b
        - id: root
          volumeAId: root-a
          volumeBId: root-b
    mountPoints:
      - path: /boot/efi
        targetId: esp
        filesystem: vfat
        options: ["umask=0077"]
      - path: /
        targetId: root
        filesystem: ext4
        options: ["defaults"]
      - path: /web
        targetId: web
        filesystem: ext4
        options: ["defaults"]
      - path: /var/lib/trident
        targetId: trident
        filesystem: ext4
        options: ["defaults"]
    images:
      - url: http://NETLAUNCH_HOST_ADDRESS/files/esp.rawzst
        sha256: ignored
        format: raw-zst
        targetId: esp
      - url: http://NETLAUNCH_HOST_ADDRESS/files/root.rawzst
        sha256: ignored
        format: raw-zst
        targetId: root
  trident:
    selfUpgrade: false
  os:
    network:
      ethernets:
        vmeths:
          match:
            name: enp*
          dhcp4: true
      version: 2
    users:
      - name: testing-user
        sshPublicKeys: []
        sshMode: key-only
  scripts:
    postConfigure:
      - name: testing-privilege
        servicingType:
          - clean-install
        content: 'echo "testing-user ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/testing-user'
