flowchart TD
ks[\Input Kickstart File\]-->load

subgraph Setsail
direction TB
load[Kickstart Loader]
load-->kslines[\Loaded Kickstart File\]
kslines-->pre[Preprocessor]
pre-->ppks[\Preprocessed Kickstart File\]

ppks-->pp1
ppks-->pp2

subgraph pp1["Parser First Pass"]
direction LR
p1[Reduced Parser]-->prescripts[\"%pre scripts"\]
prescripts-->run[["Run %pre scripts"]]
end

pp2[Parser Second Pass]

pp1-.->pp2

pp2-->data[\Parsed Data\]

tr[Translator]

data-->tr

end

tr-->hc[\HostConfiguration\]