stages:
- stage: ProvisioningOSTemplate
  displayName: Provisioning OS Template
  dependsOn: Trident

  jobs:
  - job: BuildProvisioningISOTemplate
    displayName: Build
    timeoutInMinutes: 20
    pool:
      type: linux
      name: CAPKV_Pool
      hostArchitecture: amd64

    variables:
      argusToolkitSourceDirectory: $(Build.SourcesDirectory)/argus-toolkit

      ob_outputDirectory: $(argusToolkitSourceDirectory)/build
      ob_artifactBaseName: provisioning-os-template

    steps:
    - checkout: argus-toolkit

    - template: ../common_tasks/install-clamav.yml

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: current
        artifactName: trident-binaries
        branchName: 'refs/heads/main'
        targetPath: '$(System.ArtifactsDirectory)/trident'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          set -eux
          # Copy trident, trident-service and trident-provisioning rpms to the
          # artifacts/trident directory.
          mkdir -p $(argusToolkitSourceDirectory)/artifacts/trident
          cp $(System.ArtifactsDirectory)/trident/trident-*.rpm $(argusToolkitSourceDirectory)/artifacts/trident
        workingDirectory: $(argusToolkitSourceDirectory)
      displayName: "Moving trident rpms to artifacts directory"

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          set -eux
          mkdir -p $(argusToolkitSourceDirectory)/build

          # Use default value of MARINER_GIT_REF from the argus-toolkit.
          mariner_git_ref=$(
              grep \
                  'MARINER_GIT_REF ?= [^ ]*' \
                  $(argusToolkitSourceDirectory)/Makefile | \
              sed 's/MARINER_GIT_REF ?= //')

          $(argusToolkitSourceDirectory)/prov-builder/build.sh \
              $(argusToolkitSourceDirectory)/artifacts/trident \
              $(argusToolkitSourceDirectory)/build \
              $mariner_git_ref
        workingDirectory: $(argusToolkitSourceDirectory)
      displayName: "Build Provisioning OS ISO Template"
