parameters:
  - name: buildPurpose
    type: string
    default: "AUTO"
    values:
      - AUTO
      - daily
      - pullrequest
      - post_merge
      - validation

  - name: stageDependencies
    type: object
    default:
    - BuildingTools
    - TridentTestImg_trident_installer_testimage
    - TridentTestImg_trident_testimage
    - TridentTestImg_trident_verity_testimage
    - TridentTestImg_containerhost_testimage

  - name: updateRuntimeOSTrident
    type: boolean
    default: false

stages:
  - stage: DeploymentTesting
    displayName: Deployment Testing
    dependsOn: ${{ parameters.stageDependencies }}

    jobs:
      - template: ../common_tasks/get-tests.yml
        parameters:
          buildPurpose: ${{ parameters.buildPurpose }}
          deploymentEnvironment: virtualMachine

      - job: Testing
        dependsOn: DefineTests
        timeoutInMinutes: 25
        pool:
          type: linux
          name: Trident_Ubuntu
          hostArchitecture: amd64

        strategy:
          matrix: $[ dependencies.DefineTests.outputs['setConfigurations.matrixConfigurations'] ]

        variables:
          buildPurpose: $[ dependencies.DefineTests.outputs['setBuildPurpose.buildPurpose'] ]
          tridentConfigurationName: $(configuration)

          tridentSourceDirectory: $(Build.SourcesDirectory)
          argusToolkitSourceDirectory: $(Build.SourcesDirectory)/argus-toolkit

          tridentConfigPath: $(tridentSourceDirectory)/e2e_tests/trident_configurations/$(tridentConfigurationName)
          ob_outputDirectory: $(tridentSourceDirectory)/deployment_logs
          ob_artifactBaseName: $(tridentConfigurationName)_deployment_log_$(System.JobAttempt)

        steps:
          - checkout: argus-toolkit
            fetchDepth: 1

          - template: netlaunch-prep.yml

          - template: ../common_tasks/trident-prep.yml
            parameters:
              tridentSourceDirectory: $(tridentSourceDirectory)
              tridentConfigPath: $(tridentConfigPath)
              updateRuntimeOSTrident: ${{ parameters.updateRuntimeOSTrident }}

          - bash: |
              set -eux
              sg libvirt "./virt-deploy create -d 32,32"
              sg libvirt "./virt-deploy run"
            workingDirectory: $(argusToolkitSourceDirectory)
            displayName: "Running sushy tools for testing deployment with BMC"

          - bash: |
              set -eux

              # rerun is expected to fail
              IGNORE_FAILURE_FLAG=""
              if [ ${{ variables['tridentConfigurationName'] }} == 'rerun' ]; then
                IGNORE_FAILURE_FLAG="--ignore-failure"
              fi

              echo "Netlaunch output:" > ./deployment.log
              ./bin/netlaunch \
                  --iso $(System.ArtifactsDirectory)/trident-installer-testimage.iso \
                  --config $(argusToolkitSourceDirectory)/vm-netlaunch.yaml \
                  --trident $(tridentConfigPath)/trident-config.yaml \
                  --servefolder ./artifacts/test-image \
                  --logstream $IGNORE_FAILURE_FLAG \
              2>&1 | tee -a ./deployment.log

              mkdir -p $(ob_outputDirectory)
              cp ./deployment.log $(ob_outputDirectory)/deployment-netlaunch.log

              $(tridentSourceDirectory)/e2e_tests/helpers/check_netlaunch.py ./deployment.log || [ ${{ variables['tridentConfigurationName'] }} == 'rerun' ]

              sudo virsh list
              sudo virsh dumpxml virtdeploy-vm-0

            timeoutInMinutes: 7
            workingDirectory: $(tridentSourceDirectory)
            displayName: "Run netlaunch for testing"

          - bash: |
              set -eux
              echo -e '\n\n\n' >> ./deployment.log
              printf '%.0s-' {1..90} >> ./deployment.log
              echo -e '\n\n\n' >> ./deployment.log

              vm_name="$(jq .virtualmachines[0].name ./virt-deploy-metadata.json)"
              log=$(eval echo /tmp/"$vm_name"-serial0.log)

              until [ -f "$log" ]
              do
                  sleep 0.1
              done

              echo "$log": | tee -a ./deployment.log
              sudo tail -f -n +1 "$log" | tee -a ./deployment.log &
              PID=$!

              if [ "$(Agent.JobStatus)" != "Canceled" ]; then
                while true
                do
                  if tail ./deployment.log | grep -v "localhost login:" | grep -P -m 1 "^[a-zA-Z0-9_-]+ login:"
                  then
                      kill $PID
                      break
                  else
                      sleep 0.5
                  fi
                done
                echo "Successful Runtime OS deployment"
              fi
            timeoutInMinutes: 5
            condition: succeededOrFailed()
            workingDirectory: $(argusToolkitSourceDirectory)
            displayName: "Check Runtime OS deployment"

          - bash: |
              set -eux
              if [[ -f $(argusToolkitSourceDirectory)/deployment.log ]]; then
                mkdir -p $(ob_outputDirectory)
                sudo cp $(argusToolkitSourceDirectory)/deployment.log \
                            $(ob_outputDirectory)/deployment.log
              fi
            workingDirectory: $(tridentSourceDirectory)
            condition: succeededOrFailed()
            displayName: "Publish deployment.log"

          - template: ../common_tasks/e2e-test-run.yml
            parameters:
              buildPurpose: $(buildPurpose)
              deploymentEnvironment: virtualMachine
              tridentConfigurationName: $(tridentConfigurationName)
              hostIp: $(jq -r '.virtualmachines[0].ip' $(argusToolkitSourceDirectory)/virt-deploy-metadata.json)
              tridentConfigPath: $(tridentConfigPath)
              sshKeyPath: $(tridentSourceDirectory)/e2e_tests/helpers/key
              userName: testing-user
              artifactsDirectory: artifacts/test-image

          - bash: |
              set -eux
              sudo virsh shutdown virtdeploy-vm-0
              sudo cp /var/lib/libvirt/images/virtdeploy-pool/virtdeploy-vm-0-0-volume.qcow2 $(ob_outputDirectory)/
              sudo zstd -T0 $(ob_outputDirectory)/virtdeploy-vm-0-0-volume.qcow2
            workingDirectory: $(tridentSourceDirectory)
            condition: failed()
            displayName: "Publish OS disk"

      - job: FunctionalTests
        displayName: Functional Tests
        timeoutInMinutes: 45
        pool:
          type: linux
          name: Trident_Ubuntu
          hostArchitecture: amd64

        variables:
          ob_outputDirectory: $(Build.SourcesDirectory)/build
          argusToolkitSourceDirectory: $(Build.SourcesDirectory)/argus-toolkit

        steps:
          - checkout: argus-toolkit
            fetchDepth: 1
          - checkout: platform-tests
            fetchDepth: 1

          - template: netlaunch-prep.yml

          - bash: |
              set -eux

              sudo apt install -y protobuf-compiler clang bc
              sudo apt remove python3-openssl
              pip install pytest assertpy paramiko pyopenssl
            displayName: Install dependencies
            retryCountOnTaskFailure: 3

          - bash: |
              set -eux

              ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -q -N ""
            displayName: Set up SSH Keys
            retryCountOnTaskFailure: 3

          - template: ../../common_tasks/rustup.yml

          - bash: |
              set -eux

              # Copy files from platform-tests to functional_tests
              cp platform-tests/tools/marinerhci_test_tools/node_interface.py functional_tests/
              cp platform-tests/tools/marinerhci_test_tools/ssh_node.py functional_tests/

              # Run the core of the functional tests, which means only
              # rebuilding the test binaries and invoking pytest. The regular
              # target is meant for local use and does extra setup not required
              # here.
              sg libvirt "make functional-test-core INSTALLER_ISO_PATH=$(System.ArtifactsDirectory)/trident-installer-testimage.iso ARGUS_TOOLKIT_PATH=argus-toolkit"
            displayName: Execute Functional Tests

          - template: ../../common_tasks/coverage.yml
            parameters:
              codeCoverageBaseline: 79 # Unit + functional tests
              executeUnitTests: true
              installNativeDependencies: false
              rustup: false

          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: "JUnit"
              testResultsFiles: "$(Build.SourcesDirectory)/target/trident_functional_tests.xml"

          - bash: |
              set -eux

              sg libvirt "make patch-functional-test INSTALLER_ISO_PATH=$(System.ArtifactsDirectory)/trident-installer-testimg.iso ARGUS_TOOLKIT_PATH=argus-toolkit"
            displayName: Rerun Functional Tests
