parameters:
  - name: imageName
    type: string

  - name: baseimgBuildType
    displayName: Base Image build type
    type: string
    values:
      - dev
      - preview
      - release
    default: "release"

  - name: baseImagePipelineBuildId
    displayName: "Build Id of the pipeline run, default will select latest successful run from pipeline 2116 ([AMD64-6-OneBranch]-Prod-BuildImages) with tag 3.0-preview"
    type: string
    default: "latestFromBranch"

  - name: runtimeEnv
    displayName: "Runtime environment (host vs container)"
    type: string
    default: "host"
    values:
      - host
      - container

  - name: micBuildType
    displayName: MIC Build Type
    type: string
    values:
      - dev
      - preview
      - release
    default: release

  - name: micVersion
    displayName: MIC Version
    type: string
    default: "*.*.*"

  - name: clones
    displayName: "Number of clones to generate"
    type: number
    default: 2

  - name: dependsOnTrident
    type: boolean
    default: true

stages:
  - stage: TridentTestImg_${{ replace(parameters.imageName, '-', '_') }}
    displayName: Build ${{ parameters.imageName }}
    dependsOn:
      - ${{ if and(eq(parameters.runtimeEnv, 'host'), parameters.dependsOnTrident) }}:
          - GetTridentBinaries_rpms
      - ${{ else }}: []

    jobs:
      - job: BuildTridentTestImg
        displayName: Build
        timeoutInMinutes: 20
        pool:
          type: linux

        variables:
          ob_outputDirectory: $(Pipeline.Workspace)/s/output
          ob_artifactBaseName: ${{ parameters.imageName }}
          BASEIMG_AZURE_LINUX_VERSION: "3.0"

        steps:
          - template: ../common_tasks/avoid-pypi-usage.yml

          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: current
              artifactName: trident-binaries
              targetPath: "$(Build.ArtifactStagingDirectory)/trident"
            displayName: Download Trident RPMs
            condition: and(eq('${{ parameters.runtimeEnv }}', 'host'), eq('${{ parameters.dependsOnTrident }}', true))

          - template: ../common_tasks/find-base-image-version.yml
            parameters:
              baseimgBuildType: ${{ parameters.baseimgBuildType }}
              baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}

          - template: .pipelines/templates/build-image.yml@test-images
            parameters:
              imageName: ${{ parameters.imageName }}
              clones: ${{ parameters.clones }}
              baseimgBuildType: ${{ parameters.baseimgBuildType }}
              baseimgVersion: $(baseimgVersion)
              azureLinuxVersion: ${{ variables.BASEIMG_AZURE_LINUX_VERSION }}
              micBuildType: ${{ parameters.micBuildType }}
              micVersion: ${{ parameters.micVersion }}
