parameters:
  - name: imageName
    type: string

  - name: runtimeEnv
    displayName: "Runtime environment (host vs container)"
    type: string
    default: "host"
    values:
      - host
      - container

  - name: micBuildType
    displayName: MIC Build Type
    type: string
    values:
      - dev
      - preview
      - release
    default: release

  - name: micVersion
    displayName: MIC Version
    type: string
    default: "*.*.*"

  - name: clones
    displayName: "Number of clones to generate"
    type: number
    default: 2

  - name: dependsOnTrident
    type: boolean
    default: true

  - name: dependsOnStage
    type: string
    default: ''

stages:
  - stage: TridentTestImg_${{ replace(parameters.imageName, '-', '_') }}
    displayName: Build ${{ parameters.imageName }}
    ${{ if and(eq(parameters.runtimeEnv, 'host'), parameters.dependsOnTrident) }}:
      dependsOn:
        - GetTridentBinaries_rpms_amd64_amd64
    ${{ elseif ne(parameters.dependsOnStage, '') }}:
      dependsOn:
        - ${{ parameters.dependsOnStage }}

    jobs:
      - job: BuildTridentTestImg
        displayName: Build
        timeoutInMinutes: 20
        pool:
          type: linux

        variables:
          ob_outputDirectory: $(Pipeline.Workspace)/s/output
          ob_artifactBaseName: ${{ parameters.imageName }}
          BASEIMG_AZURE_LINUX_VERSION: "3.0"

        steps:
          - template: ../common_tasks/avoid-pypi-usage.yml

          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: current
              artifactName: trident-binaries
              targetPath: "$(Build.ArtifactStagingDirectory)/trident"
            displayName: Download Trident RPMs
            condition: and(eq('${{ parameters.runtimeEnv }}', 'host'), eq('${{ parameters.dependsOnTrident }}', true))

          - template: ../common_tasks/find-base-image-version.yml
          - template: .pipelines/templates/build-image.yml@test-images
            parameters:
              imageName: ${{ parameters.imageName }}
              clones: ${{ parameters.clones }}
              baseimgBuildType: $(BASEIMG_BUILD_TYPE)
              baseimgVersion: $(BASEIMG_VERSION)
              azureLinuxVersion: ${{ variables.BASEIMG_AZURE_LINUX_VERSION }}
              micBuildType: ${{ parameters.micBuildType }}
              micVersion: ${{ parameters.micVersion }}
