parameters:
- name: imageName
  type: string

- name: outputArtifactName
  type: string

stages:
- stage: TridentTestImg_${{ replace(parameters.outputArtifactName, '-', '_') }}
  displayName: Build ${{ parameters.outputArtifactName }}
  dependsOn: Trident

  jobs:
  - job: BuildTridentTestImg
    displayName: Build
    timeoutInMinutes: 20
    pool:
      type: linux

    variables:
      ob_outputDirectory: $(Pipeline.Workspace)/s/test-images/output
      ob_artifactBaseName: ${{ parameters.outputArtifactName }}
      micBuildType: "preview"
      micVersion: "*.*.*"
      baseimgBuildType: "release"
      baseimgVersion: "*.*.*"
      baseimgAzureLinuxVersion: "2.0"

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: current
        artifactName: trident-binaries
        targetPath: "$(Build.ArtifactStagingDirectory)/trident"
      displayName: Download Trident RPMs

    - template: .pipelines/templates/trident-testimg-template.yml@test-images
      parameters:        
        target: ${{ parameters.imageName }}
        outputDirectory: ${{ variables.ob_outputDirectory }}
        testImagesRepo: test-images
        micBuildType: ${{ variables.micBuildType }}
        micVersion: ${{ variables.micVersion }}
        baseimgBuildType: ${{ variables.baseimgBuildType }}
        baseimgVersion: ${{ variables.baseimgVersion }}
        baseimgAzureLinuxVersion: ${{ variables.baseimgAzureLinuxVersion }}
        downloadTrident: false
   