parameters:
- name: imageName
  type: string

- name: outputArtifactName
  type: string

stages:
- stage: TridentTestImg_${{ replace(parameters.outputArtifactName, '-', '_') }}
  displayName: Build ${{ parameters.outputArtifactName }}
  dependsOn: Trident

  jobs:
  - job: BuildTridentTestImg
    displayName: Build
    timeoutInMinutes: 15
    pool:
      type: linux

    variables:
      ob_outputDirectory: $(Build.SourcesDirectory)/test-images/output
      ob_artifactBaseName: ${{ parameters.outputArtifactName }}
      mic_package: DEFAULT
      mic_version: DEFAULT
      mic_commit: DEFAULT
      baseimg_package: DEFAULT
      baseimg_version: DEFAULT

    steps:
    - checkout: test-images
      fetchDepth: 1

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: current
        artifactName: trident-binaries
        targetPath: '$(Build.SourcesDirectory)/test-images/base/trident'
        branchName: 'refs/heads/main'
      displayName: Download Trident RPMs

    - template: .pipelines/templates/trident-testimg-template.yml@test-images
      parameters:
        tridentImgSourceDirectory: $(Build.SourcesDirectory)/test-images
        outputDirectory: ${{ variables.ob_outputDirectory }}
        mic_package: ${{ variables.mic_package }}
        mic_version: ${{ variables.mic_version }}
        mic_commit: ${{ variables.mic_commit }}
        baseimg_package: ${{ variables.baseimg_package }}
        baseimg_version: ${{ variables.baseimg_version }}
        target: ${{ parameters.imageName }}
