parameters:
  - name: imageName
    type: string

  - name: outputArtifactName
    type: string

  - name: baseimgBuildType
    displayName: Base Image build type
    type: string
    values:
      - dev
      - preview
      - release
    default: "release"

  - name: baseImagePipelineBuildId
    displayName: "Build Id of the pipeline run, default will select latest successful run from pipeline 2116 ([AMD64-6-OneBranch]-Prod-BuildImages) with tag 3.0-preview"
    type: string
    default: "latestFromBranch"

  - name: runtimeEnv
    displayName: "Runtime environment (host vs container)"
    type: string
    default: "host"
    values:
      - host
      - container

  - name: mkcosiTemplate
    type: string
    default: "none"
    values:
      - none
      - regular
      - verity

  - name: micBuildType
    displayName: MIC Build Type
    type: string
    values:
    - dev
    - preview
    - release
    default: release

  - name: micVersion
    displayName: MIC Version
    type: string
    default: "*.*.*"


stages:
  - stage: TridentTestImg_${{ replace(parameters.outputArtifactName, '-', '_') }}
    displayName: Build ${{ parameters.outputArtifactName }}
    dependsOn:
      - ${{ if eq(parameters.runtimeEnv, 'host') }}:
          - GetTridentBinaries_rpms
      - ${{ else }}: []

    jobs:
      - job: BuildTridentTestImg
        displayName: Build
        timeoutInMinutes: 20
        pool:
          type: linux

        variables:
          ob_outputDirectory: $(Pipeline.Workspace)/s/test-images/output
          ob_artifactBaseName: ${{ parameters.outputArtifactName }}
          BASEIMG_AZURE_LINUX_VERSION: "3.0"

        steps:
          - task: PipAuthenticate@1
            displayName: Provision - Authenticate Pip
            inputs:
              artifactFeeds: 'mariner/Mariner-Pypi-Feed'

          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: current
              artifactName: trident-binaries
              targetPath: "$(Build.ArtifactStagingDirectory)/trident"
            displayName: Download Trident RPMs
            condition: eq('${{ parameters.runtimeEnv }}', 'host')

          - template: ../common_tasks/find-base-image-version.yml
            parameters:
              baseimgBuildType: ${{ parameters.baseimgBuildType }}
              baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}

          - template: .pipelines/templates/trident-testimg-template.yml@test-images
            parameters:
              target: ${{ parameters.imageName }}
              outputDirectory: ${{ variables.ob_outputDirectory }}
              testImagesRepo: test-images
              micBuildType: ${{ parameters.micBuildType }}
              micVersion: ${{ parameters.micVersion }}
              baseimgBuildType: ${{ parameters.baseimgBuildType }}
              baseimgVersion: $(baseimgVersion)
              baseimgAzureLinuxVersion: ${{ variables.BASEIMG_AZURE_LINUX_VERSION }}
              downloadTrident: false
