//! Trident gRPC server implementation.
//!
//! This module contains the implementation of the gRPC server for Trident's
//! services. It defines the `TridentServer` struct which implements the gRPC
//! service interface generated by Tonic from the protobuf definitions.

use std::{panic, sync::Arc, time::SystemTime};

use log::{error, info, warn};
use prost_types::Timestamp;
use tokio::{
    sync::{
        mpsc::{self, UnboundedSender},
        OwnedRwLockWriteGuard, RwLock,
    },
    task::JoinHandle,
};
use tokio_util::sync::CancellationToken;
use tonic::{Response, Status};

use trident_api::{
    error::{InvalidInputError, TridentError, TridentResultExt},
    primitives::hash::Sha384Hash,
};
use trident_proto::v1::{
    servicing_response::Response as ResponseType, ServicingKind, ServicingResponse, Started,
};

use crate::{
    agentconfig::AgentConfig,
    datastore::DataStore,
    logging::{logfwd::LogForwarder, operation_context},
    server::{activitytracker::ActivityTracker, support::stream::StreamWithLock},
    ExitKind, Logstream, TraceStream,
};

#[cfg(feature = "grpc-preview")]
use tokio::sync::OwnedRwLockReadGuard;

#[cfg(feature = "grpc-preview")]
use tonic::Code;

#[cfg(feature = "grpc-preview")]
use trident_api::error::ErrorKind;

mod datastore;
mod services;
mod servicingmgr;

use servicingmgr::RebootDecision;
pub(super) use servicingmgr::ServicingManager;

pub(super) struct TridentServer {
    log_forwarder: LogForwarder,
    tracker: ActivityTracker,
    servicing_manager: ServicingManager,
    rwlock: Arc<RwLock<()>>,
    agent_config: AgentConfig,
    logstream: Logstream,
    tracestream: TraceStream,
}

/// This is the stream type for all servicing responses.
type ServicingResponseStream = StreamWithLock<Result<ServicingResponse, Status>, ()>;

impl TridentServer {
    pub(super) fn new(
        servicing_manager: ServicingManager,
        log_forwarder: LogForwarder,
        tracker: ActivityTracker,
        agent_config: AgentConfig,
        logstream: Logstream,
        tracestream: TraceStream,
    ) -> Self {
        TridentServer {
            log_forwarder,
            tracker,
            servicing_manager,
            rwlock: Arc::new(RwLock::new(())),
            agent_config,
            logstream,
            tracestream,
        }
    }

    /// Sets up log forwarding from the internal log forwarder to the gRPC
    /// streaming response.
    ///
    /// Internally spawns a background task that listens for log records from
    /// the internal [`LogForwarder`] and sends them over the provided gRPC
    /// channel as [`ServicingResponse`] messages. On success, this function
    /// returns a [`JoinHandle`] for the spawned task together with a
    /// [`CancellationToken`] that can be used by the caller to request
    /// shutdown of the forwarding task.
    ///
    /// # Errors
    ///
    /// Returns an internal gRPC [`Status`] error if the log forwarder sender
    /// channel cannot be installed (i.e. if
    /// [`LogForwarder::set_sender`](crate::LogForwarder::set_sender) returns
    /// an error). In that case, no background task is spawned and no log
    /// records will be forwarded for this stream.
    ///
    /// # Task lifecycle
    ///
    /// The spawned task runs until one of the following occurs:
    /// * The provided cancellation token is cancelled.
    /// * The internal log channel is closed and `recv` returns `None`.
    /// * Sending a log record on `grpc_log_tx` fails.
    ///
    /// When the task terminates for any reason, it attempts to clear the
    /// sender from the internal [`LogForwarder`] so that subsequent streams
    /// can install their own sender if needed.
    fn setup_log_forwarding(
        &self,
        grpc_log_tx: UnboundedSender<Result<ServicingResponse, Status>>,
    ) -> Result<(JoinHandle<()>, CancellationToken), Status> {
        // Set up log forwarding task
        let log_token = CancellationToken::new();
        let (log_tx, mut log_rx) = mpsc::unbounded_channel();

        // Set the sender in the log forwarder
        if self.log_forwarder.set_sender(log_tx).is_err() {
            error!("Failed to set log forwarder sender channel");
            return Err(Status::internal("Failed to set log forwarder"));
        }

        // Spawn log forwarding task
        let log_token_clone = log_token.clone();
        let log_forwarder_clone = self.log_forwarder.clone();
        let handle = tokio::spawn(async move {
            loop {
                tokio::select! {
                    _ = log_token_clone.cancelled() => {
                        break;
                    }

                    channel_msg = log_rx.recv() => {
                        let Some(log_record) = channel_msg else {
                            break;
                        };

                        if let Err(err) = grpc_log_tx.send(Ok(ServicingResponse {
                            timestamp: Some(Timestamp::from(SystemTime::now())),
                            response: Some(ResponseType::Log(log_record.into())),
                        })) {
                            error!("Failed to send log message in streaming response: {}", err);
                            break;
                        }
                    }
                }
            }

            log_forwarder_clone.clear_sender().unwrap_or_else(|err| {
                error!("Failed to clear log forwarder sender channel: {}", err);
            });
        });

        // Return the handle and cancellation token
        Ok((handle, log_token))
    }

    /// Tries to acquire a read lock on the server's RwLock. If the lock
    /// cannot be acquired, returns a gRPC Status indicating that the server is
    /// busy.
    ///
    /// Intentionally fires no telemetry (`command_start`/`command_error`) for
    /// this rejection, unlike `reject_invalid_argument`/`reject_invalid_field`/
    /// `reject_invalid_config`: a connection-lock contention failure isn't a
    /// distinct servicing outcome the way a malformed request is -- it's
    /// pure admission control, happens before `refresh_installation_id` would
    /// even run, and (unlike a bad request) the caller is expected to retry
    /// the exact same request rather than fix anything, so a low-value,
    /// high-volume `command_error` stream isn't worth adding here.
    #[cfg(feature = "grpc-preview")]
    fn try_acquire_read_lock(&self) -> Result<OwnedRwLockReadGuard<()>, Status> {
        self.rwlock.clone().try_read_owned().map_err(|_| {
            warn!("Trident is busy, cannot acquire read connection lock");
            Status::unavailable("Trident is busy")
        })
    }

    /// Tries to acquire a write lock on the server's RwLock. If the lock
    /// cannot be acquired, returns a gRPC Status indicating that the server is
    /// busy.
    ///
    /// See the telemetry note on [`Self::try_acquire_read_lock`]: this
    /// rejection is intentionally untelemetered for the same reason.
    fn try_acquire_write_lock(&self) -> Result<OwnedRwLockWriteGuard<()>, Status> {
        self.rwlock.clone().try_write_owned().map_err(|_| {
            warn!("Trident is busy, cannot acquire write connection lock");
            Status::unavailable("Trident is busy")
        })
    }

    /// Handles a servicing request by acquiring the necessary locks,
    /// setting up log forwarding, and spawning the provided servicing task.
    ///
    /// On success, returns a gRPC streaming response (`Response<ServicingResponseStream>`)
    /// that yields log messages and the final result of the servicing task.
    ///
    /// If the required read/write locks cannot be acquired (for example, when the
    /// server is busy), this returns an error `Status` such as `Status::unavailable`.
    /// It may also return other error `Status` values if log forwarding or task
    /// setup fails. In all error cases, no servicing task is spawned and no stream
    /// of responses is produced.
    /// Re-checks for a persisted installation ID before a request fires its
    /// own `command_start` (via `run_command`). The daemon-startup pre-warm
    /// in `server_main` only ever runs once, and deliberately skips itself
    /// when the datastore doesn't exist yet (see there for why) -- so a
    /// daemon that starts before the host is ever installed, then serves a
    /// request some time after a *different* path (e.g. a concurrent CLI
    /// invocation, or an earlier servicing request on this same daemon)
    /// has since created the datastore, would otherwise still be missing
    /// it. Called from both `servicing_request` and `reading_request`, so
    /// read-only RPCs (e.g. `get_servicing_state`) don't keep reporting a
    /// stale/missing installation ID indefinitely just because they never
    /// happen to run after a write request has warmed it.
    ///
    /// `name` identifies the requests that can create a brand-new
    /// datastore, per `DataStore::may_initialize_datastore_for_command`:
    /// install/update stage requests (not their finalize-only variants,
    /// which cannot themselves stage anything), plus `stream_disk` -- a
    /// direct-streaming install path (see
    /// `services/streaming.rs`/`tools/pkg/netlaunch`) used when no Host
    /// Configuration/datastore exists yet either. For those, delegates to
    /// `TraceStream::mint_and_attach_installation_id`, mirroring the
    /// CLI's pre-warm, so this request's own command_start carries an ID
    /// instead of being permanently unattributed on a fresh
    /// install/stream_disk. Every other request just delegates to
    /// [`Self::refresh_installation_id_readonly`].
    ///
    /// Known limitation (tracked, not fixed here): `TraceStream`'s
    /// installation-ID cache is a process-lifetime cache with no
    /// invalidation. If the on-disk datastore this daemon process is
    /// bound to is ever deleted and replaced by a *different*
    /// installation (e.g. an out-of-band host reset that leaves the same
    /// daemon process running instead of restarting it), every telemetry
    /// event emitted for the rest of this process's lifetime keeps
    /// carrying the old, now-stale installation ID -- this cache is never
    /// re-read once warmed, so it can't notice the replacement.
    /// Deliberately not fixed with an invalidation scheme (e.g. keying the
    /// cache off the datastore's path/inode/mtime) in this pass: a host
    /// reset is expected to restart the daemon process (which naturally
    /// clears this cache), so the failure mode requires an unusual
    /// operational sequence, and the added complexity/testing surface of
    /// a real invalidation design isn't justified without a concrete
    /// report of this happening. Revisit if a genuine
    /// reset-without-restart scenario is ever confirmed.
    fn refresh_installation_id(&self, name: &str) {
        if !DataStore::may_initialize_datastore_for_command(name) {
            return self.refresh_installation_id_readonly();
        }
        let minted = AgentConfig::load().and_then(|agent_config| {
            let mut ds = DataStore::open_or_create(agent_config.datastore_path())?;
            self.tracestream.mint_and_attach_installation_id(&mut ds)
        });
        if let Err(e) = minted {
            warn!("Failed to mint installation ID: {e:?}");
        }
    }

    /// Same as [`Self::refresh_installation_id`], but never allowed to
    /// create a datastore regardless of what a command name would
    /// otherwise permit. Used by the `reject_*` helpers: a rejected
    /// request (missing/invalid field, unparsable Host Configuration)
    /// never actually begins staging or finalizing anything, so it must
    /// never leave a fresh datastore behind, even for an
    /// otherwise-create-permitted command name like `install` (see
    /// `DataStore::may_initialize_datastore_for_command`) -- unlike
    /// `refresh_installation_id`, called only once a request has passed
    /// its own pre-dispatch validation and is genuinely proceeding.
    ///
    /// Related, narrower known limitation: the cache read inside
    /// `TraceStream::attach_installation_id_if_present` and the eventual
    /// cache write it may lead to are not fenced by a single lock
    /// spanning both -- concurrent requests can each observe the cache as
    /// empty and both proceed to look up/mint the ID. This is harmless
    /// when they agree on the same value (the common case), and its only
    /// known bad outcome is a narrow attribution gap on the very first
    /// request of a specific concurrent-first-request race, not a
    /// correctness bug in persisted state. Not worth a dedicated lock for
    /// that blast radius; revisit if it proves reachable more broadly.
    fn refresh_installation_id_readonly(&self) {
        if let Ok(agent_config) = AgentConfig::load() {
            self.tracestream
                .attach_installation_id_if_present(agent_config.datastore_path());
        }
    }

    fn servicing_request<F>(
        &self,
        name: &'static str,
        reboot_decision: RebootDecision,
        f: F,
    ) -> Result<Response<ServicingResponseStream>, Status>
    where
        F: FnOnce() -> Result<(ExitKind, Option<Sha384Hash>, Option<ServicingKind>), TridentError>
            + Send
            + panic::UnwindSafe
            + 'static,
    {
        info!("Received servicing request '{}'", name);

        // Try to acquire the connection lock in write mode
        let guard = self.try_acquire_write_lock()?;

        self.refresh_installation_id(name);

        // Same `HostNotProvisioned` invariant the CLI's shared dispatch
        // enforces (see `main.rs`): a request that cannot itself
        // stage/initialize a new install or update (per
        // `DataStore::may_initialize_datastore_for_command`) must never
        // reach `Trident::new`'s own datastore-open call on a host that
        // has no datastore yet -- e.g. `commit`, `rollback`,
        // `rollback_stage`, `rollback_finalize`, and `rebuild_raid`, none
        // of which are create-permitted, sent to a daemon that has never
        // serviced a real install/update. Computed here (while the write
        // lock from `try_acquire_write_lock` above is already held, and
        // after `refresh_installation_id`, which needs the same
        // create-permission check to decide mint-vs-migrate), and
        // captured into `f` below so the rejection still fires
        // `command_start`/`command_error` like any other servicing
        // outcome, instead of short-circuiting before telemetry runs.
        let host_provisioned = DataStore::may_initialize_datastore_for_command(name)
            || self.agent_config.datastore_path().exists();

        // Tag every metric/tracing event `f` fires (on whatever thread it
        // ultimately runs on -- see `spawn_servicing_task`, which runs it
        // via `tokio::task::spawn_blocking`, giving it a dedicated OS
        // thread for its whole duration) with `command`/`operation_id`, the
        // same way the CLI path does for its own dispatch. `name` already
        // matches the CLI's own command-naming convention (see
        // `command_name` in `main.rs`) for stage/finalize granularity.
        //
        // If `f` decides a reboot is needed, also capture this operation's
        // context (while it's still installed) via `save_reboot_operation`,
        // so `server::reboot` -- which runs later, after this whole
        // request and even the daemon's main event loop have returned --
        // can tag `trident_system_reboot` with this same servicing
        // operation's identity instead of leaving it untagged.
        let f = move || {
            operation_context::run_command(name, || {
                if !host_provisioned {
                    return Err(TridentError::new(InvalidInputError::HostNotProvisioned))
                        .message("Datastore file does not exist");
                }
                let result = f();
                if let Ok((ExitKind::NeedsReboot, ..)) = &result {
                    operation_context::save_reboot_operation();
                }
                result
            })
        };

        // Create the gRPC response channel
        let (tx, rx) = mpsc::unbounded_channel();

        // Try to acquire the servicing lock. Rejected here, after
        // `refresh_installation_id` above but before the `run_command`
        // closure `f` (built above) ever runs, this is intentionally
        // untelemetered for the same reason as the connection-lock
        // rejections in `try_acquire_read_lock`/`try_acquire_write_lock`:
        // it's admission control, not a distinct servicing outcome, and
        // the caller is expected to retry rather than fix anything.
        let Some(servicing_guard) = self.servicing_manager.try_lock_servicing() else {
            warn!("Request '{}' blocked because servicing is active", name);
            return Err(Status::unavailable("Servicing is active"));
        };

        // Set up log forwarding. Logs will be sent over the gRPC channel.
        let (log_fwd_handle, log_fwd_token) = self.setup_log_forwarding(tx.clone())?;

        // All prerequisites are met, send start response
        if let Err(err) = tx.send(Ok(ServicingResponse {
            timestamp: Some(Timestamp::from(SystemTime::now())),
            response: Some(ResponseType::Started(Started {})),
        })) {
            error!("Failed to send start response: {}", err);
            return Err(Status::internal("Failed to start processing"));
        }

        // Create a clone of the activity tracker to move into the task
        let tracker_clone = self.tracker.clone();

        let logstream = self.logstream.clone();
        let tracestream = self.tracestream.clone();
        let manager = self.servicing_manager.clone();

        // Spawn the servicing task
        tokio::spawn(async move {
            // Spawn the servicing task and await its completion
            let completed_message = manager
                .spawn_servicing_task(reboot_decision, servicing_guard, tracker_clone, f)
                .await;

            // Reset logstream and tracestream server URLs, in case they were set.
            if let Err(e) = logstream.clear_server() {
                error!("Failed to clear logstream server: {}", e);
            }
            if let Err(e) = tracestream.clear_server() {
                error!("Failed to clear tracestream server: {}", e);
            }

            if let Some(ref err) = completed_message.error {
                error!("Servicing request '{}' failed: {}", name, err.message);
            } else {
                info!("Servicing request '{}' completed successfully", name);
            }

            // Stop log forwarding
            log_fwd_token.cancel();

            // Await the log forwarding task to finish to ensure all relevant
            // logs have been sent.
            if let Err(err) = log_fwd_handle.await {
                error!("Log forwarder task failed: {}", err);
            }

            // Send the final status response
            if let Err(err) = tx.send(Ok(ServicingResponse {
                timestamp: Some(Timestamp::from(SystemTime::now())),
                response: Some(ResponseType::Completed(completed_message)),
            })) {
                error!("Failed to send control response: {}", err);
            }

            // Close the gRPC channel by dropping the sender. Only two senders
            // exist: this one and the one in the log forwarder, which has
            // already been stopped.
            drop(tx);

            info!("Request '{}' completed", name);
        });

        // Return the streaming response with the lock guard
        Ok(Response::new(StreamWithLock::new(rx, guard)))
    }

    /// Handles a read-only request by acquiring the necessary locks and
    /// executing the provided function.
    ///
    /// This helper:
    /// - Tries to acquire the connection lock in read mode.
    /// - Tries to acquire the servicing read lock, returning
    ///   [`Status::unavailable`] if servicing is currently active.
    /// - Executes the provided function `f` once the locks are held.
    ///
    /// On success, this returns `Ok(Response::new(result))`, where `result` is
    /// the value produced by `f`. If `f` returns an error, the error is logged
    /// and converted into a [`Status::internal`] error. Failures to acquire the
    /// underlying locks are returned as appropriate [`Status`] errors.
    #[cfg(feature = "grpc-preview")]
    async fn reading_request<F, R>(&self, name: &'static str, f: F) -> Result<Response<R>, Status>
    where
        F: FnOnce() -> Result<R, TridentError> + Send + 'static,
        R: Send + 'static,
    {
        info!("Received read request '{}'", name);
        // Try to acquire the connection lock in read mode. We hold a reference
        // to the lock guard to ensure it lives through the duration of the
        // request.
        let _guard = self.try_acquire_read_lock()?;

        // Try to acquire the servicing read lock. Same intentional
        // telemetry gap as the connection-lock rejections in
        // `try_acquire_read_lock`/`try_acquire_write_lock` and the
        // servicing-lock rejection in `servicing_request`: this rejects
        // before `refresh_installation_id` below even runs, it's admission
        // control rather than a distinct read outcome, and the caller is
        // expected to retry rather than fix anything.
        let Some(servicing_guard) = self.servicing_manager.try_lock_reading() else {
            warn!(
                "Read request '{}' blocked because servicing is active",
                name
            );
            return Err(Status::unavailable("Servicing is active"));
        };

        self.refresh_installation_id(name);

        // Same `HostNotProvisioned` gate as `servicing_request` (see the
        // comment there): read requests reach this same `Trident`
        // construction path and must be rejected identically on an
        // unprovisioned host, e.g. `check_rollback`. Computed while the
        // read lock above is held, and captured into `f` below so the
        // rejection still fires `command_start`/`command_error`.
        let host_provisioned = DataStore::may_initialize_datastore_for_command(name)
            || self.agent_config.datastore_path().exists();

        // Tag every metric/tracing event `f` fires (on the dedicated OS
        // thread `spawn_reading_task` runs it on, via
        // `tokio::task::spawn_blocking`) with `command`/`operation_id`, and
        // fire `command_start`/`command_error`, the same way
        // `servicing_request` does for write requests -- without this,
        // read requests (e.g. `get_servicing_state`, `check_rollback`)
        // fired neither event despite returning `TridentError` on failure
        // just like servicing requests do.
        //
        // Known remaining gap: an RPC that encodes a domain-level failure
        // in an `Ok` response instead of returning `Err(TridentError)` (if
        // any -- none currently do) would still not get a command_error,
        // since that only fires on `Err`.
        let f = move || {
            operation_context::run_command(name, || {
                if !host_provisioned {
                    return Err(TridentError::new(InvalidInputError::HostNotProvisioned))
                        .message("Datastore file does not exist");
                }
                f()
            })
        };

        // Execute the reading function
        Ok(Response::new(
            ServicingManager::spawn_reading_task(servicing_guard, f)
                .await
                .map_err(|e| {
                    error!("Reading request '{name}' failed: {e:?}");
                    trident_error_to_status(e)
                })?,
        ))
    }
}

#[cfg(feature = "grpc-preview")]
fn trident_error_to_status(err: TridentError) -> Status {
    let code = match err.kind() {
        ErrorKind::ExecutionEnvironmentMisconfiguration(_) => Code::FailedPrecondition,
        ErrorKind::HealthChecks(_) => Code::Unknown,
        ErrorKind::Initialization(_) => Code::FailedPrecondition,
        ErrorKind::Internal(_) => Code::Internal,
        ErrorKind::InvalidInput(_) => Code::InvalidArgument,
        ErrorKind::Servicing(_) => Code::Unknown,
        ErrorKind::UnsupportedConfiguration(_) => Code::FailedPrecondition,
    };

    Status::new(code, format!("{err:?}"))
}
