hostConfiguration:
  storage:
    disks:
      - id: os
        device: /dev/disk/by-path/pci-0000:00:1f.2-ata-2
        partitionTableType: gpt
        partitions:
          - id: esp
            type: esp
            size: 1G
          - id: boot-a
            type: xbootldr
            size: 200M
          - id: root-a
            type: root
            size: 8G
          - id: root-hash-a
            type: root-verity
            size: 1G
          - id: trident-overlay-a
            type: linux-generic
            size: 100M
          - id: var-a
            type: linux-generic
            size: 1G
          - id: boot-b
            type: xbootldr
            size: 200M
          - id: root-b
            type: root
            size: 8G
          - id: root-hash-b
            type: root-verity
            size: 1G
          - id: trident-overlay-b
            type: linux-generic
            size: 100M
          - id: var-b
            type: linux-generic
            size: 1G
          - id: trident
            type: linux-generic
            size: 100M
          - id: home
            type: linux-generic
            size: 100M
      - id: disk2
        device: /dev/disk/by-path/pci-0000:00:1f.2-ata-3
        partitionTableType: gpt
        partitions: []
    abUpdate:
      volumePairs:
        - id: boot
          volumeAId: boot-a
          volumeBId: boot-b
        - id: root
          volumeAId: root-a
          volumeBId: root-b
        - id: root-hash
          volumeAId: root-hash-a
          volumeBId: root-hash-b
        - id: trident-overlay
          volumeAId: trident-overlay-a
          volumeBId: trident-overlay-b
        - id: var
          volumeAId: var-a
          volumeBId: var-b
    filesystems:
      - deviceId: home
        type: ext4
        mountPoint:
          path: /home
          options: defaults
      - deviceId: trident
        type: ext4
        mountPoint:
          path: /var/lib/trident
          options: defaults
      - deviceId: var
        type: ext4
        source:
          type: image
          url: http://NETLAUNCH_HOST_ADDRESS/files/verity_var.rawzst
          sha256: ignored
          format: raw-zst
        mountPoint:
          path: /var
          options: defaults
      - deviceId: boot
        type: ext4
        source:
          type: image
          url: http://NETLAUNCH_HOST_ADDRESS/files/verity_boot.rawzst
          sha256: ignored
          format: raw-zst
        mountPoint:
          path: /boot
          options: defaults
      - deviceId: esp
        type: vfat
        source:
          type: image
          url: http://NETLAUNCH_HOST_ADDRESS/files/verity_esp.rawzst
          sha256: ignored
          format: raw-zst
        mountPoint:
          path: /boot/efi
          options: umask=0077
      - deviceId: trident-overlay
        type: ext4
        mountPoint:
          path: /var/lib/trident-overlay
          options: defaults
    verityFilesystems:
      - name: root
        dataDeviceId: root
        hashDeviceId: root-hash
        dataImage:
          url: http://NETLAUNCH_HOST_ADDRESS/files/verity_root.rawzst
          sha256: ignored
          format: raw-zst
        hashImage:
          url: http://NETLAUNCH_HOST_ADDRESS/files/verity_roothash.rawzst
          sha256: ignored
          format: raw-zst
        type: ext4
        mountPoint:
          path: /
          options: defaults,ro
  scripts:
    postConfigure:
      - name: overlay
        runOn:
          - clean-install
          - ab-update
        content: |
          mkdir -p /var/lib/trident-overlay/etc-rw/upper
          mkdir -p /var/lib/trident-overlay/etc-rw/work
  os:
    network:
      version: 2
      ethernets:
        vmeths:
          match:
            name: enp*
          dhcp4: true
    users:
      - name: testing-user
        sshPublicKeys: []
        secondaryGroups:
          - wheel
        sshMode: key-only
