hostConfiguration:
  storage:
    disks:
      - id: os
        device: /dev/disk/by-path/pci-0000:00:1f.2-ata-2
        partitionTableType: gpt
        partitions:
          - id: esp
            type: esp
            size: 1G
          - id: boot-a
            type: xbootldr
            size: 200M
          - id: root-a
            type: root
            size: 8G
          - id: root-hash-a
            type: root-verity
            size: 1G
          - id: trident-overlay-a
            type: linux-generic
            size: 100M
          - id: var-a
            type: linux-generic
            size: 1G
          - id: boot-b
            type: xbootldr
            size: 200M
          - id: root-b
            type: root
            size: 8G
          - id: root-hash-b
            type: root-verity
            size: 1G
          - id: trident-overlay-b
            type: linux-generic
            size: 100M
          - id: var-b
            type: linux-generic
            size: 1G
          - id: trident
            type: linux-generic
            size: 100M
          - id: home
            type: linux-generic
            size: 100M
          - id: run
            type: linux-generic
            size: 1G
      - id: disk2
        device: /dev/disk/by-path/pci-0000:00:1f.2-ata-3
        partitionTableType: gpt
        partitions: []
    abUpdate:
      volumePairs:
      - id: boot
        volumeAId: boot-a
        volumeBId: boot-b
      - id: root
        volumeAId: root-a
        volumeBId: root-b
      - id: root-hash
        volumeAId: root-hash-a
        volumeBId: root-hash-b
      - id: trident-overlay
        volumeAId: trident-overlay-a
        volumeBId: trident-overlay-b
      - id: var
        volumeAId: var-a
        volumeBId: var-b
    mountPoints:
      - path: /boot/efi
        targetId: esp
        filesystem: vfat
        options: ["umask=0077"]
      - path: /boot
        targetId: boot
        filesystem: ext4
        options: ["defaults"]
      - path: /
        targetId: verity-root
        filesystem: ext4
        options: ["defaults", "ro"]
      - path: /var/lib/trident
        targetId: trident
        filesystem: ext4
        options: ["defaults"]
      - path: /var/lib/trident-overlay
        targetId: trident-overlay
        filesystem: ext4
        options: ["defaults"]
      - path: /home
        targetId: home
        filesystem: ext4
        options: ["defaults"]
      - path: /var
        targetId: var
        filesystem: ext4
        options: ["defaults"]
      - path: /run
        targetId: run
        filesystem: ext4
        options: ["defaults"]
    images:
      - url: file:///trident_cdrom/data/verity_esp.rawzst
        sha256: ignored
        format: raw-zst
        targetId: esp
      - url: file:///trident_cdrom/data/verity_boot.rawzst
        sha256: ignored
        format: raw-zst
        targetId: boot
      - url: file:///trident_cdrom/data/verity_root.rawzst
        sha256: ignored
        format: raw-zst
        targetId: root
      - url: file:///trident_cdrom/data/verity_roothash.rawzst
        sha256: ignored
        format: raw-zst
        targetId: root-hash
      - url: file:///trident_cdrom/data/verity_var.rawzst
        sha256: ignored
        format: raw-zst
        targetId: var
    verity:
      - id: verity-root
        deviceName: root
        dataTargetId: root
        hashTargetId: root-hash
  os:
    network:
      ethernets:
        vmeths:
          match:
            name: enp*
          dhcp4: true
      version: 2
    users:
      - name: testing-user
        secondaryGroups: [wheel]
        sshPublicKeys: []
        sshMode: key-only
  scripts:
    postConfigure:
    - content: |
        mkdir -p /var/lib/trident-overlay/etc-rw/upper
        mkdir -p /var/lib/trident-overlay/etc-rw/work
      name: overlay
      servicingType:
      - clean-install
      - ab-update
