parameters:
  - name: baseimgBuildType
    displayName: Base Image build type
    type: string
    values:
      - dev
      - preview
      - release
    default: "release"
  
  - name: previewContainerImageBuildId
    type: string
    default: "latestFromBranch"

stages:
  - stage: BuildTridentContainerImage
    displayName: Build Docker Image
    dependsOn: GetTridentBinaries_rpms

    jobs:
      - job: BuildImage
        displayName: Build Image
        pool:
          type: linux

        variables:
          ob_outputDirectory: "$(Build.SourcesDirectory)/trident/out"
          ob_artifactBaseName: "trident-docker-image"

        steps:
          - script: |
              set -eux
              mkdir -p bin/RPMS
            displayName: Prepare to build docker image
            retryCountOnTaskFailure: 3

          - task: DownloadPipelineArtifact@2
            displayName: "Download Trident rpms"
            inputs:
              buildType: current
              artifactName: "trident-binaries"
              patterns: "**/*.rpm"
              targetPath: "$(Build.SourcesDirectory)/bin/RPMS/x86_64"

          - ${{ if eq(parameters.baseimgBuildType, 'preview') }}:
            - template: ../common_tasks/preview-container.yml
              parameters:
                dockerfilePath: $(Build.SourcesDirectory)/Dockerfile.runtime
                dockerBuildContext: $(Build.SourcesDirectory)
                ${{ if eq(parameters.previewContainerImageBuildId, 'latestFromBranch') }}:
                  runVersion: ${{ parameters.previewContainerImageBuildId }}
                ${{ else }}:
                  runVersion: specific
                  previewContainerImageBuildId: ${{ parameters.previewContainerImageBuildId }}

          - script: |
              set -euxo pipefail

              mkdir -p $(ob_outputDirectory)
              DOCKER_BUILDKIT=1 docker build -f Dockerfile.runtime --progress plain -t trident/trident:latest .
              docker save trident/trident:latest | gzip > $(ob_outputDirectory)/trident-container.tar.gz
            workingDirectory: $(Build.SourcesDirectory)
            displayName: Build Docker image
