parameters:
  - name: dependsOnStage
    type: string
    default: ""

  - name: distro
    type: string
    default: "azl3"
    values:
      - azl3
      - azl4

stages:
  - stage: BuildTridentContainerImage
    displayName: Build Docker Image
    dependsOn:
      - GetTridentBinaries_rpms_amd64
      - ${{ if ne(parameters.dependsOnStage, '') }}:
          - ${{ parameters.dependsOnStage }}

    jobs:
      - job: BuildImage
        displayName: Build Image
        pool:
          type: linux

        variables:
          ob_outputDirectory: "/tmp/trident-docker-image"
          ob_artifactBaseName: "trident-docker-image"

        steps:
          - template: ../common_tasks/checkout_trident.yml
          - template: ../common_tasks/avoid-pypi-usage.yml

          - script: |
              set -eux
              mkdir -p bin/RPMS
            displayName: Prepare to build docker image
            retryCountOnTaskFailure: 3
            workingDirectory: $(TRIDENT_SOURCE_DIR)

          - task: DownloadPipelineArtifact@2
            displayName: "Download Trident rpms"
            inputs:
              buildType: current
              artifactName: "trident-binaries"
              patterns: "**/*${{ parameters.distro }}*.rpm"
              targetPath: "$(TRIDENT_SOURCE_DIR)/bin/RPMS/x86_64"

          - template: ../common_tasks/preview-container.yml
            parameters:
              dockerfilePath: $(TRIDENT_SOURCE_DIR)/packaging/docker/Dockerfile.runtime
              tridentSourceDirectory: $(TRIDENT_SOURCE_DIR)

          - script: |
              set -euxo pipefail

              AZL_IMAGE="$(DISTRO=${{ parameters.distro }} make azl-version-vars | grep AZL_IMAGE | cut -d '=' -f2)"
              RPM_PACKAGES="$(DISTRO=${{ parameters.distro }} make azl-version-vars | grep RPM_PACKAGES | cut -d '=' -f2)"

              mkdir -p $(ob_outputDirectory)
              DOCKER_BUILDKIT=1 docker build -f \
                  packaging/docker/Dockerfile.runtime \
                  --progress plain \
                  -t trident/trident:latest \
                  . \
                  --build-arg AZL_IMAGE="$AZL_IMAGE" \
                  --build-arg RPM_PACKAGES="$RPM_PACKAGES"

              docker save trident/trident:latest | gzip > $(ob_outputDirectory)/trident-container.tar.gz
            workingDirectory: $(TRIDENT_SOURCE_DIR)
            displayName: Build Docker image
