parameters:
- name: tridentRepo
  type: string
  default: self

stages:
- stage: MakefileValidation
  displayName: Validate Makefile targets

  jobs:
  - job: Make
    displayName: make
    timeoutInMinutes: 30
    pool:
      type: linux
      name: CAPKV_Pool
      hostArchitecture: amd64

    variables:
      ob_outputDirectory: $(Build.SourcesDirectory)/build
      tridentSourceDirectory: $(Build.SourcesDirectory)/trident
      emu_package_name: ''
      emu_package_version: ''

    steps:
    - checkout: self
    - checkout: ${{ parameters.tridentRepo }}

    - template: ../common_tasks/install-clamav.yml

    - template: ../common_tasks/download-emu.yml
      parameters:
         tridentSourceDirectory: $(tridentSourceDirectory)

    - script: |
        set -eux
        sudo apt install -y protobuf-compiler clang-7 bc
      displayName: Install native dependencies

    - template: ../common_tasks/rustup.yml

    - bash: |
        set -eux
        make bin/trident-rpms.tar.gz docker-build validate-configs generate-mermaid-diagrams
      workingDirectory: $(tridentSourceDirectory)
      displayName: Invoke make