internalParams:
  uki: true
image:
  url: http://NETLAUNCH_HOST_ADDRESS/files/usrverity.cosi
  sha384: ignored
storage:
  disks:
    - id: os
      device: /dev/disk/by-path/pci-0000:00:1f.2-ata-2
      partitionTableType: gpt
      partitions:
        - id: esp
          type: esp
          size: 1G
        - id: boot-a
          type: xbootldr
          size: 200M
        - id: boot-b
          type: xbootldr
          size: 200M
        - id: root-data-a-1
          type: root
          size: 4G
        - id: root-data-b-1
          type: root
          size: 4G
        - id: root-data-a-2
          type: root
          size: 4G
        - id: root-data-b-2
          type: root
          size: 4G
        - id: root-hash-a-1
          type: root-verity
          size: 1G
        - id: root-hash-b-1
          type: root-verity
          size: 1G
        - id: root-hash-a-2
          type: root-verity
          size: 1G
        - id: root-hash-b-2
          type: root-verity
          size: 1G
        - id: web-a-e-1
          type: linux-generic
          size: 1G
        - id: web-a-e-2
          type: linux-generic
          size: 1G
        - id: web-b-e-1
          type: linux-generic
          size: 1G
        - id: web-b-e-2
          type: linux-generic
          size: 1G
        - id: home
          type: linux-generic
          size: 100M
        - id: trident-overlay-a-1
          type: linux-generic
          size: 100M
        - id: trident-overlay-b-1
          type: linux-generic
          size: 100M
        - id: trident-overlay-a-2
          type: linux-generic
          size: 100M
        - id: trident-overlay-b-2
          type: linux-generic
          size: 100M
        - id: trident
          type: linux-generic
          size: 100M
        - id: var
          type: linux-generic
          size: 1G
    - id: disk2
      device: /dev/disk/by-path/pci-0000:00:1f.2-ata-3
      partitionTableType: gpt
      partitions: []
  encryption:
    volumes:
      - id: web-a
        deviceName: web-a
        deviceId: web-a-e
      - id: web-b
        deviceName: web-b
        deviceId: web-b-e
  raid:
    software:
      - id: web-a-e
        name: web-a-e
        level: raid1
        devices:
          - web-a-e-1
          - web-a-e-2
      - id: web-b-e
        name: web-b-e
        level: raid1
        devices:
          - web-b-e-1
          - web-b-e-2
      - id: root-data-a
        name: root-data-a
        level: raid1
        devices:
          - root-data-a-1
          - root-data-a-2
      - id: root-data-b
        name: root-data-b
        level: raid1
        devices:
          - root-data-b-1
          - root-data-b-2
      - id: root-hash-a
        name: root-hash-a
        level: raid1
        devices:
          - root-hash-a-1
          - root-hash-a-2
      - id: root-hash-b
        name: root-hash-b
        level: raid1
        devices:
          - root-hash-b-1
          - root-hash-b-2
      - id: trident-overlay-a
        name: trident-overlay-a
        level: raid1
        devices:
          - trident-overlay-a-1
          - trident-overlay-a-2
      - id: trident-overlay-b
        name: trident-overlay-b
        level: raid1
        devices:
          - trident-overlay-b-1
          - trident-overlay-b-2
  abUpdate:
    volumePairs:
      - id: boot
        volumeAId: boot-a
        volumeBId: boot-b
      - id: root-data
        volumeAId: root-data-a
        volumeBId: root-data-b
      - id: root-hash
        volumeAId: root-hash-a
        volumeBId: root-hash-b
      - id: trident-overlay
        volumeAId: trident-overlay-a
        volumeBId: trident-overlay-b
      - id: web
        volumeAId: web-a
        volumeBId: web-b
  verity:
    - id: root
      name: root
      dataDeviceId: root-data
      hashDeviceId: root-hash
  filesystems:
    - deviceId: web
      source: new
      mountPoint:
        path: /web
        options: defaults
    - deviceId: home
      source: new
      mountPoint: /home
    - deviceId: esp
      mountPoint:
        path: /boot/efi
        options: umask=0077
    - deviceId: trident-overlay
      source: new
      mountPoint: /var/lib/trident-overlay
    - deviceId: boot
      mountPoint: /boot
    - deviceId: trident
      source: new
      mountPoint: /var/lib/trident
    - deviceId: var
      mountPoint: /var
    - deviceId: root
      mountPoint:
        path: /
        options: defaults,ro
scripts:
  preServicing:
    - name: rerun-trident-with-memory-limit
      runOn:
        - clean-install
      content: |
        systemctl status trident | grep Memory
        if [ ! -f "/run/already-run" ]; then
          echo "Setting memory limit for trident-install.service"
          systemctl set-property trident-install.service MemoryMax=64M
          systemd-run --property=After=trident-install.service --no-block systemctl start trident-install.service
          touch "/run/already-run"
          exit 1
        fi
os:
  selinux:
    mode: permissive
  network:
    version: 2
    ethernets:
      vmeths:
        match:
          name: enp*
        dhcp4: true
  users:
    - name: testing-user
      sshPublicKeys: []
      secondaryGroups:
        - wheel
      sshMode: key-only
