stages:
  - stage: MakefileValidation
    displayName: Validate Makefile targets

    jobs:
      - job: Make
        displayName: make
        timeoutInMinutes: 30
        pool:
          type: linux
          name: Trident_Ubuntu
          hostArchitecture: amd64

        variables:
          ob_outputDirectory: $(Build.SourcesDirectory)/build
          emu_package_name: ""
          emu_package_version: ""

        steps:
          - template: ../common_tasks/download-emu.yml

          - script: |
              set -eux
              sudo apt install -y protobuf-compiler clang bc
            displayName: Install native dependencies
            retryCountOnTaskFailure: 3

          - template: ../common_tasks/rustup.yml

          - bash: |
              set -eux
              make bin/trident-rpms.tar.gz docker-build validate-configs generate-mermaid-diagrams
            displayName: Invoke make
          
          - script: |
              set -eux

              make check-pipelines BRANCH=$(Build.SourceBranch)
            displayName: "Validating pipeline templates work"
            workingDirectory: $(Build.SourcesDirectory)
            env:
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
