stages:
  - stage: MakefileValidation
    displayName: Validate Makefile targets

    jobs:
      - job: Make
        displayName: make
        timeoutInMinutes: 30
        pool:
          type: linux
          name: CAPKV_Pool
          hostArchitecture: amd64

        variables:
          ob_outputDirectory: $(Build.SourcesDirectory)/build
          emu_package_name: ""
          emu_package_version: ""

        steps:
          - template: ../common_tasks/install-clamav.yml

          - template: ../common_tasks/download-emu.yml

          - script: |
              set -eux
              sudo apt install -y protobuf-compiler clang-7 bc
            displayName: Install native dependencies

          - template: ../common_tasks/rustup.yml

          - bash: |
              set -eux
              make bin/trident-rpms.tar.gz docker-build validate-configs generate-mermaid-diagrams
            displayName: Invoke make

          - task: AzureCLI@2
            displayName: "Validating pipeline templates work"
            inputs:
              azureSubscription: CoreOS_ECF_Kubernetes_dev (b8a0db63-c5fa-4198-8e2a-f9d6ff52465e)
              scriptType: "bash"
              workingDirectory: $(Build.SourcesDirectory)
              scriptLocation: inlineScript
              inlineScript: |
                set -eux
                make check-pipelines BRANCH=$(Build.SourceBranch)
