stages:
  - stage: MakefileValidation
    displayName: Validate Makefile targets

    jobs:
      - job: Make
        displayName: make
        timeoutInMinutes: 30
        pool:
          type: linux
          name: trident-ubuntu-1es-pool-eastus2
          hostArchitecture: amd64

        variables:
          ob_outputDirectory: $(Build.SourcesDirectory)/build

        steps:
          - template: ../common_tasks/download-osmodifier.yml

          - script: |
              set -eux
              sudo apt install -y protobuf-compiler clang bc
            displayName: Install native dependencies
            retryCountOnTaskFailure: 3

          - task: CargoAuthenticate@0
            displayName: "Authenticate with Cargo"
            inputs:
              configFile: .cargo/config.toml

          - template: ../common_tasks/rustup.yml

          - bash: |
              set -eux
              # Disabled `generate-mermaid-diagrams` due to #9055
              make validate-configs
              make bin/trident-rpms.tar.gz
              make docker-build
            displayName: Invoke make

          - script: |
              set -eux

              make check-pipelines BRANCH=$(Build.SourceBranch)
            displayName: "Validating pipeline templates work"
            workingDirectory: $(Build.SourcesDirectory)
            env:
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
