graph TD
classDef Purple fill:#f9f,stroke:#333,stroke-width:4px;
L0[Call to baremetal-deploy.yml] --> L1[Copy Trident YAML to input directory] 
subgraph baremetal-deploy.yml in platform-tests repository
    L1 --> L2[Create patched Installer.iso from the installer.iso that has been downloaded]
    L2 --> L3[Create BMC Config file specific to pass to deploy.py script - platform-tests/bare-metal/scripts/create_baremetal_config.py]
    L3 --> L4[Boot baremetal lab machine - .pipelines/templates/stages/testing_baremetal/deploy_on_bm.py]
    class L3 Purple; 
end
subgraph Legend
    LE1[Code in platform-tests repo]
    class LE1 Purple;
end