graph TD;
    classDef Red fill:#FF9999,stroke:#333,stroke-width:4px;
    classDef Amber fill:#FFDEAD,stroke:#333,stroke-width:4px;
    classDef Green fill:#BDFFA4,stroke:#333,stroke-width:4px;
    A[Call to .pipelines/stages/update_host_config/baremetal/update_host_config.py] --> B[Parse command line arguments];
    subgraph .pipelines/stages/update_host_config/baremetal/update_host_config.py in trident
      B --> C[Adding OAM IP to Ethernet Interface  - eno*]
      C --> D[Setting DHCP4 Configuration - dhcp4:true];
      subgraph Updating os disks in trident.yaml
        D --> E[Updating os disks device in trident.yaml - from /dev/disk/by-path/...];
        E --> F[Finding and Updating OS Disk];
      end
      subgraph Updating image paths in trident.yaml
        F --> G[Updating image paths in trident.yaml - from file:/// to http://];
        G --> H[Finding and Parsing Image URLs];
        H --> I[Extracting Image Name];
        I --> J[Constructing New Image URL];
        J --> K[Replacing Image URL in Configuration];
      end
      subgraph Adding mariner_user in trident.yaml different from testing_user used in e2e tests
        K --> L[Adding mariner_user username in trident.yaml - Required for SSH access from Azure Devops VM];
        L --> M[Adding SSH Key for 'mariner_user' username. This is different from the testing_user used for the e2e tests];
      end
      M --> N[Final trident.yaml content post all the updates];
      class D,E,F Amber;
      class G,H,I,J,K Green;
      class L,M Red;
    end
    subgraph Legend
        direction LR
        LE2[Updating OS Disks in trident.yaml]
        LE3[Updating image paths in trident.yaml]
        LE4[Adding mariner_user username to trident.yaml]
        class LE2 Amber;
        class LE3 Green;
        class LE4 Red;
    end