parameters:
  - name: runtimeEnv
    displayName: "Runtime environment (host vs container)"
    type: string
    default: "host"
    values:
      - host
      - container

  - name: micBuildType
    displayName: MIC Build Type
    type: string
    values:
      - dev
      - preview
      - release
    default: release

  - name: micVersion
    displayName: MIC Version
    type: string
    default: "*.*.*"

  - name: clones
    displayName: "Number of clones to generate"
    type: number
    default: 2

  - name: dependsOnStage
    type: string
    default: ''

stages:
  # Build installer tools
  - template: build-installer-tools.yml

  - stage: AzureLinux_Installer_ISO
    displayName: Build azl-installer-iso
    dependsOn:
      - BuildInstallerTools
      - GetTridentBinaries_rpms_amd64
      - ${{ if ne(parameters.dependsOnStage, '') }}:
        - ${{ parameters.dependsOnStage }}

    jobs:
      - job: BuildAzLInstallerISO
        displayName: Build azl-installer-iso
        timeoutInMinutes: 20
        pool:
          type: linux

        variables:
          ob_outputDirectory: $(Pipeline.Workspace)/s/output
          ob_artifactBaseName: azl-installer-iso
          BASEIMG_AZURE_LINUX_VERSION: "3.0"

        steps:
          - template: ../common_tasks/avoid-pypi-usage.yml

          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: current
              artifactName: trident-binaries
              targetPath: "$(Build.ArtifactStagingDirectory)/trident"
            displayName: Download Trident RPMs

          - task: DownloadPipelineArtifact@2
            displayName: "Download trident-testimage"
            inputs:
              buildType: current
              artifactName: trident-testimage
              targetPath: "$(System.ArtifactsDirectory)/testimage"

          - template: ../common_tasks/find-base-image-version.yml
          
          - template: ../build_image/build-image-template.yml
            parameters:
              imageName: azl-installer
              baseimgBuildType: $(BASEIMG_BUILD_TYPE)
              baseimgVersion: $(BASEIMG_VERSION)
              azureLinuxVersion: ${{ variables.BASEIMG_AZURE_LINUX_VERSION }}
              micBuildType: ${{ parameters.micBuildType }}
              micVersion: ${{ parameters.micVersion }}



          