parameters:
- name: argusRepo
  type: string
  default: argus-toolkit

- name: tridentRepo
  type: string
  default: self

- name: installerISOPipeline
  type: string
  default: ''

- name: downloadBuildType
  type: string
  default: current

- name: updateRuntimeOSTrident
  type: boolean
  default: false

stages:
- stage: DeploymentTesting
  displayName: Deployment Testing
  dependsOn: InstallerISO

  jobs:
  - job: DefineTests
    displayName: Define Tests
    timeoutInMinutes: 5
    pool:
      type: linux

    variables:
      ob_outputDirectory: $(Build.SourcesDirectory)/build
      tridentSourceDirectory: $(Build.SourcesDirectory)/trident

    steps:
    - checkout: ${{ parameters.tridentRepo }}

    - bash: |
        set -eux
        tests=""
        for dir in */; do
          dir=${dir%*/}
          tests+=", \"$dir\" : {\"test\": \"$dir\"}"
        done
        tests="{${tests:2}}"
        echo "##vso[task.setvariable variable=listOfTests;isOutput=true]$tests"
      workingDirectory: $(tridentSourceDirectory)/e2e_tests/trident_configurations
      name: setTests
      displayName: Set concurrent tests

  - job: Testing
    dependsOn: DefineTests
    timeoutInMinutes: 15
    pool:
      type: linux
      name: CAPKV_Pool
      hostArchitecture: amd64

    strategy:
      matrix:
        $[ dependencies.DefineTests.outputs['setTests.listOfTests'] ]

    variables:
      tridentSourceDirectory: $(Build.SourcesDirectory)/trident
      argusToolkitSourceDirectory: $(Build.SourcesDirectory)/argus-toolkit

      tridentConfigPath: $(tridentSourceDirectory)/e2e_tests/trident_configurations/$(test)
      ob_outputDirectory: $(tridentSourceDirectory)/deployment_logs
      ob_artifactBaseName: $(test)_deployment_log_$(System.JobAttempt)

    steps:
    - checkout: self
    - checkout: ${{ parameters.tridentRepo }}
    - checkout: ${{ parameters.argusRepo }}

    - template: netlaunch-prep.yml
      parameters:
         downloadBuildType: ${{ parameters.downloadBuildType}}
         installerISOPipeline: ${{ parameters.installerISOPipeline }}

    - bash: |
        set -eux
        sudo snap install yq
      workingDirectory: $(tridentSourceDirectory)
      displayName: "Installing dependencies"

    - bash: |
        set -eux
        sudo yq eval '.host-configuration.management.self-upgrade = true' trident-config.yaml -i
      condition: eq(${{ parameters.updateRuntimeOSTrident }}, true)
      workingDirectory: $(tridentConfigPath)
      displayName: "Update trident in Runtime OS"

    - bash: |
        set -eux
        sg libvirt "./virt-deploy create"
        sg libvirt "./virt-deploy run"
      workingDirectory: $(argusToolkitSourceDirectory)
      displayName: "Running sushy tools for testing deployment with BMC"

    - bash: |
        set -eux
        sudo python3 $(tridentSourceDirectory)/e2e_tests/tests/helpers/add_key.py \
            --keypath $(tridentSourceDirectory)/e2e_tests/tests/helpers/key \
            --tridentconfig $(tridentConfigPath)/trident-config.yaml
        sudo openssl rsa -in $(tridentSourceDirectory)/e2e_tests/tests/helpers/key \
            -out $(tridentSourceDirectory)/e2e_tests/tests/helpers/key
        sudo chmod 600 $(tridentSourceDirectory)/e2e_tests/tests/helpers/key
      workingDirectory: $(tridentSourceDirectory)
      displayName: "Setting keys to ssh for testing"

    - bash: |
        set -eux

        echo "Netlaunch output:" >> ./deployment.log
        $(argusToolkitSourceDirectory)/build/netlaunch \
            --iso $(System.ArtifactsDirectory)/installer-iso/installer-iso/installer.iso \
            --config $(argusToolkitSourceDirectory)/vm-netlaunch.yaml \
            --trident $(tridentConfigPath)/trident-config.yaml \
            --logstream \
        2>&1 | tee -a ./deployment.log
        $(tridentSourceDirectory)/e2e_tests/check_netlaunch.py ./deployment.log
      timeoutInMinutes: 5
      workingDirectory: $(argusToolkitSourceDirectory)
      displayName: "Run netlaunch for testing"

    - bash: |
        set -eux
        echo -e '\n\n\n' >> ./deployment.log
        printf '%.0s-' {1..90} >> ./deployment.log
        echo -e '\n\n\n' >> ./deployment.log

        vm_name="$(jq .virtualmachines[0].name ./virt-deploy-metadata.json)"
        log=$(eval echo /tmp/"$vm_name"-serial0.log)

        until [ -f "$log" ]
        do
            sleep 0.1
        done

        echo "$log": | tee -a ./deployment.log
        sudo tail -f -n +1 "$log" | tee -a ./deployment.log &
        PID=$!

        if [ "$(Agent.JobStatus)" != "Canceled" ]; then
          while true
          do
            if tail ./deployment.log | grep -v "localhost login:" | grep -P -m 1 "^[a-zA-Z0-9_-]+ login:"
            then
                kill $PID
                break
            else
                sleep 0.5
            fi
          done
          echo "Successful Runtime OS deployment"
        fi
      timeoutInMinutes: 5
      condition: succeededOrFailed()
      workingDirectory: $(argusToolkitSourceDirectory)
      displayName: "Check Runtime OS deployment"

    - bash: |
        set -eux
        mkdir -p deployment_logs
        sudo cp $(argusToolkitSourceDirectory)/deployment.log \
                    $(ob_outputDirectory)/deployment.log
      workingDirectory: $(tridentSourceDirectory)
      displayName: "Publish deployment.log"

    - bash: |
        set -eux
        sudo pip3 install pytest
        sudo pip3 install fabric
      workingDirectory: $(tridentSourceDirectory)
      displayName: "Installing dependencies for E2E tests"

    - bash: |
        set -eux
        host_ip="$(jq -r '.virtualmachines[0].ip' $(argusToolkitSourceDirectory)/virt-deploy-metadata.json)"
        sudo python3 -u -m pytest \
            --capture=no \
            --junit-xml=$(test)_trident_e2e_tests_$(System.JobAttempt).junit.xml \
            --host $host_ip \
            --tridentconfig $(tridentConfigPath)/trident-config.yaml
      workingDirectory: $(tridentSourceDirectory)/e2e_tests/tests
      displayName: "Trident E2E tests"
      
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: $(tridentSourceDirectory)/e2e_tests/tests/$(test)_trident_e2e_tests_$(System.JobAttempt).junit.xml
        testRunTitle: trident_e2e_tests
      displayName: Publish test results


  - job: FunctionalTests
    displayName: Functional Tests
    timeoutInMinutes: 15
    pool:
      type: linux
      name: CAPKV_Pool
      hostArchitecture: amd64

    variables:
      ob_outputDirectory: $(Build.SourcesDirectory)/build
      argusToolkitSourceDirectory: $(Build.SourcesDirectory)/argus-toolkit
      tridentSourceDirectory: $(Build.SourcesDirectory)/trident

    steps:
    - checkout: self
    - checkout: ${{ parameters.tridentRepo }}
    - checkout: ${{ parameters.argusRepo }}
    - checkout: k8s-tests

    - template: netlaunch-prep.yml
      parameters:
         downloadBuildType: ${{ parameters.downloadBuildType}}
         installerISOPipeline: ${{ parameters.installerISOPipeline }}

    - bash: |
        set -eux

        sudo apt install -y protobuf-compiler clang-7 bc
        sudo apt remove python3-openssl
        pip install pytest assertpy paramiko pyopenssl
        ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -q -N ""
      displayName: Install dependencies

    - bash: |
        set -eux

        sg libvirt "make functional-test INSTALLER_ISO_PATH=$(System.ArtifactsDirectory)/installer-iso/installer-iso/installer.iso"
      workingDirectory: $(tridentSourceDirectory)
      displayName: Execute Functional Tests

    - template: coverage.yml
      parameters:
         tridentSourceDirectory: $(tridentSourceDirectory)
         codeCoverageBaseline: 64 # Unit + functional tests
         executeUnitTests: false
         installNativeDependencies: false

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: "$(tridentSourceDirectory)/target/trident_functional_tests.xml"
