parameters:
  - name: "debug"
    displayName: "Enable debug output"
    type: boolean
    default: false

schedules:
  - cron: "0 12 * * *"
    displayName: Daily build
    always: true
    branches:
      include:
        - main

trigger: none

variables:
  - name: CDP_DEFINITION_BUILD_COUNT
    value: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  - name: system.debug
    value: ${{ parameters.debug }}
  # ENABLE_PRS_DELAYSIGN: 0
  # ROOT: $(Build.SourcesDirectory)
  # REPOROOT: $(Build.SourcesDirectory)
  # OUTPUTROOT: $(REPOROOT)\out
  - name: LinuxContainerImage
    value: "mcr.microsoft.com/onebranch/cbl-mariner/build:2.0" # Docker image which is used to build the project https://aka.ms/obpipelines/containers
  - name: DEBIAN_FRONTEND
    value: noninteractive

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

    - repository: argus-toolkit
      type: git
      name: argus-toolkit
      ref: refs/heads/main

    - repository: platform-tests
      type: git
      name: platform-tests
      ref: refs/heads/main

    - repository: platform-pipelines
      type: git
      name: platform-pipelines
      ref: refs/heads/main

    - repository: test-images
      type: git
      name: test-images

    - repository: afo-telemetry
      name: afo-telemetry
      type: git
      ref : refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    globalSdl: # https://aka.ms/obpipelines/sdl
      tsa:
        # Break build on SDL failures instead of filing bugs.
        enabled: false # onebranch publish all sdl results to TSA. If TSA is disabled all SDL tools will forced into 'break' build mode.
      # credscan:
      #   suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      policheck:
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
      # suppression:
      #   suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress
      disableLegacyManifest: true
    featureFlags:
      runOnHost: true
      EnableCDPxPAT: false

    stages:
      - template: templates/pipeline-selector.yml
        parameters:
          targetStage: pre
