parameters:
  - name: "debug"
    displayName: "Enable debug output"
    type: boolean
    default: false

  - name: targetStage
    type: string
    default: "ci"
    values:
      - "pr"
      - "pr-e2e"
      - "ci"
      - "pre"
      - "rel"
    displayName: "Stage to run"

trigger: none

variables:
  - name: CDP_DEFINITION_BUILD_COUNT
    value: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  - name: system.debug
    value: ${{ parameters.debug }}
  # ENABLE_PRS_DELAYSIGN: 0
  # ROOT: $(Build.SourcesDirectory)
  # REPOROOT: $(Build.SourcesDirectory)
  # OUTPUTROOT: $(REPOROOT)\out
  - name: DEBIAN_FRONTEND
    value: noninteractive
  - group: bot # added for access to dom0 RPMs

resources:
  repositories:
    - repository: argus-toolkit
      type: git
      name: argus-toolkit
      ref: refs/heads/main

    - repository: platform-tests
      type: git
      name: platform-tests
      ref: refs/heads/main

    - repository: platform-pipelines
      type: git
      name: platform-pipelines
      ref: refs/heads/main

    - repository: test-images
      type: git
      name: test-images
      ref: refs/heads/main

    - repository: platform-telemetry
      name: platform-telemetry
      type: git
      ref: refs/heads/main

extends:
  template: templates/MockOB.yml
  parameters:
    stages:
      - template: templates/pipeline-selector.yml
        parameters:
          targetStage: ${{ parameters.targetStage }}
          blockPublishing: true
