parameters:
- name: tridentStage
  type: string
  default: ''

- name: argusRepo
  type: string
  default: argus-toolkit

- name: tridentPipeline
  type: string
  default: ''

- name: downloadBuildType
  type: string
  default: current

- name: artifactName
  type: string
  default: drop_Trident_BuildTrident

- name: provOSArtifactSource
  type: string
  default: current # If specific, job won't run and instead the artifact will be downloaded in other stage.

stages:
- stage: ProvisioningOSTemplate
  displayName: Provisioning OS ISO Template
  dependsOn: ${{ parameters.tridentStage }}

  jobs:
  - job: BuildProvisioningISOTemplate
    displayName: Build
    condition: eq('${{ parameters.provOSArtifactSource }}', 'current')
    timeoutInMinutes: 20
    pool:
      type: linux
      name: CAPKV_Pool
      hostArchitecture: amd64

    variables:
      argusToolkitSourceDirectory: $(Build.SourcesDirectory)/argus-toolkit

      ob_outputDirectory: $(argusToolkitSourceDirectory)/build
      ob_artifactBaseName: provisioning-os-template

    steps:
    - checkout: ${{ parameters.argusRepo }}

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: ${{ parameters.downloadBuildType }}
        project: ECF
        definition: ${{ parameters.tridentPipeline }}
        buildVersionToDownload: 'latest'
        allowFailedBuilds: true
        artifactName: ${{ parameters.artifactName }}
        branchName: 'refs/heads/main'
        targetPath: '$(System.ArtifactsDirectory)/trident'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          set -eux
          make input/trident
          # Copy trident, trident-service and trident-provisioning rpms to the
          # input/trident directory.
          cp $(System.ArtifactsDirectory)/trident/trident-*.rpm $(argusToolkitSourceDirectory)/input/trident
        workingDirectory: $(argusToolkitSourceDirectory)
      displayName: "Moving trident rpms to input directory"

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          set -eux
          mkdir -p $(argusToolkitSourceDirectory)/build

          # Use default value of MARINER_GIT_REF from the argus-toolkit.
          mariner_git_ref=$(
              grep \
                  'MARINER_GIT_REF ?= [^ ]*' \
                  $(argusToolkitSourceDirectory)/Makefile | \
              sed 's/MARINER_GIT_REF ?= //')

          $(argusToolkitSourceDirectory)/prov-builder/build.sh \
              $(argusToolkitSourceDirectory)/input/trident \
              $(argusToolkitSourceDirectory)/build \
              $mariner_git_ref
        workingDirectory: $(argusToolkitSourceDirectory)
      displayName: "Build Provisioning OS ISO Template"
