parameters:
  - name: baseImagePipelineBuildId
    displayName: "Build Id of the pipeline run, default will select latest successful run from pipeline 2116 ([AMD64-6-OneBranch]-Prod-BuildImages) with tag 3.0-preview"
    type: string
  - name: baseImageArm64PipelineBuildId
    displayName: "Build Id of the pipeline run, default will select latest successful run from pipeline 2117 ([ARM64-6-OneBranch]-Prod-BuildImages) with tag 3.0-preview"
    type: string
  - name: buildType
    displayName: "Pick build type, select 'dev' to pull images and rpms from specified build, select preview to find preview version from specified build and pull images and rpms from feeds and packages.microsoft.com"
    type: string
    default: dev
    values:
    - dev
    - preview

trigger: none

resources:
  repositories:
    - repository: argus-toolkit
      type: git
      name: argus-toolkit
      ref: refs/heads/main

    - repository: platform-tests
      type: git
      name: platform-tests
      ref: refs/heads/main

    - repository: platform-pipelines
      type: git
      name: platform-pipelines
      ref: refs/heads/main

    - repository: test-images
      type: git
      name: test-images
      ref: refs/heads/main

    - repository: platform-telemetry
      name: platform-telemetry
      type: git
      ref: refs/heads/main

extends:
  template: templates/MockOB.yml
  parameters:
    stages:
      - template: templates/trident-platform-cicd-template.yml
        parameters:
          buildType: ${{ parameters.buildType }}
          baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}
          baseImageArm64PipelineBuildId: ${{ parameters.baseImageArm64PipelineBuildId }}
