parameters:
  - name: baseimgBuildType
    displayName: Base Image build type
    type: string
    values:
      - preview
      - release
    default: "release"

  - name: "debug"
    displayName: "Enable debug output"
    type: boolean
    default: false

  - name: baseImagePipelineBuildId
    displayName: "Build Id of the pipeline run, default will select latest successful run from pipeline 2116 ([AMD64-6-OneBranch]-Prod-BuildImages) with tag 3.0-preview"
    type: string
    default: "latestFromBranch"

  - name: baseImageArm64PipelineBuildId
    displayName: "Build Id of the pipeline run, default will select latest successful run from pipeline 2117 ([ARM64-6-OneBranch]-Prod-BuildImages) with tag 3.0-preview"
    type: string
    default: "latestFromBranch"

  - name: baseimgAzlVersion
    displayName: Base Image AZL version
    type: string
    default: "3.0"

  - name: numberOfWorkers
    displayName: Number of worker to run tests on (max of 256)
    type: number
    default: 256

  - name: numberOfUpdateIterations
    displayName: Number of times each worker invokes A/B Update
    type: number
    default: 100

  - name: forceTridentRebuild
    displayName: "Force trident rebuild rather than downloading previously built."
    type: boolean
    default: false

trigger: none

variables:
  - name: CDP_DEFINITION_BUILD_COUNT
    value: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  - name: system.debug
    value: ${{ parameters.debug }}
  # ENABLE_PRS_DELAYSIGN: 0
  # ROOT: $(Build.SourcesDirectory)
  # REPOROOT: $(Build.SourcesDirectory)
  # OUTPUTROOT: $(REPOROOT)\out
  - name: DEBIAN_FRONTEND
    value: noninteractive

resources:
  repositories:
    - repository: platform-tests
      type: git
      name: platform-tests
      ref: refs/heads/main

    - repository: platform-pipelines
      type: git
      name: platform-pipelines
      ref: refs/heads/main

    - repository: test-images
      type: git
      name: test-images
      ref: refs/heads/main

    - repository: platform-telemetry
      name: platform-telemetry
      type: git
      ref: refs/heads/main

  pipelines:
    - pipeline: "[AMD64-6-OneBranch]-Prod-BuildImages"
      source: "[AMD64-6-OneBranch]-Prod-BuildImages"
      project: mariner
      branch: master
      tags:
        - "3.0-preview"
    - pipeline: "[ARM64-6-OneBranch]-Prod-BuildImages"
      source: "[ARM64-6-OneBranch]-Prod-BuildImages"
      project: mariner
      branch: master
      tags:
        - "3.0-preview"

extends:
  template: templates/MockOB.yml
  parameters:
    stages:
      - template: templates/scale-template.yml
        parameters:
          stageType: pre
          baseimgBuildType: ${{ parameters.baseimgBuildType }}
          verboseLogging: ${{ parameters.debug }}
          baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}
          baseImageArm64PipelineBuildId: ${{ parameters.baseImageArm64PipelineBuildId }}
          baseimgAzlVersion: ${{ parameters.baseimgAzlVersion }}
          numberOfWorkers: ${{ parameters.numberOfWorkers }}
          numberOfUpdateIterations: ${{ parameters.numberOfUpdateIterations }}
          forceTridentRebuild: ${{ parameters.forceTridentRebuild }}
          includeQemu: true
          includeAzure: false
          includeUKI: true
