#!/usr/bin/env python3

# Invert the target-configurations.yaml file to produce a configurations.yaml file
# that lists, for each test configuration, the lowest pipeline ring it should be run in.

import sys
import yaml

from pathlib import Path

header = """\
# This file is autogenerated by invert.py from: {0}
# Do not edit this file directly.
#
# The file is structured as:
#
# ```yaml
# <config_name>:
#   <hardware_type>:
#     <runtime>: <lowest_pipeline_ring>
# ```
#
# Where:
# - <config_name> is the name of the test configuration.
# - <hardware_type> is either "bm" (bare metal) or "vm" (virtual machine).
# - <runtime> is either "host" or "container".
# - <lowest_pipeline_ring> is the first test ring where this scenario should be run.
#
# The pipeline rings are ordered as follows (from earliest to latest in the validation process):
# {1}
#
# A scenario marked to run in a given ring will also run in all later rings.
# For example, if a scenario is marked as "pre", it will run in the "pre" ring and all higher rings
# ("full-validation").
# Scenarios not listed in this file will not be run in any ring.
"""

# Configurations enabled for the storm-based E2E flow, validated end-to-end on
# a real VM (base/encryption/verity/uki paths).
#
# Runtime self-selection: encryption+UKI configs (combined,
# memory-constraint-combined, rerun) seal to PCR 7, which Trident forbids under
# a containerized runtime, so config_is_runtime_incompatible() drops them from
# the container matrix (host only). See that helper for details.
#
# The UKI/usr-verity images boot their kernel directly through firmware Secure
# Boot, so they require the image signing certificate injected via
# --signing-cert (the CI template passes the usrverity-testimage ca_cert.pem
# for usrverity images).
ALLOWED_CONFIGS = [
    "base",
    "simple",
    "misc",
    "raid-big",
    "raid-mirrored",
    "raid-resync-small",
    "raid-small",
    "extensions",
    "encrypted-partition",
    "encrypted-raid",
    "encrypted-swap",
    "root-verity",
    "health-checks-install",
    "usr-verity",
    "usr-verity-raid",
    "combined",
    "memory-constraint-combined",
    "rerun",
    "split",
]
ALLOWED_HARDWARES = ["vm"]
ALLOWED_RUNTIMES = ["host", "container"]

# Special settings to merge into specific configurations
SPECIAL_SETTINGS = {
    "rerun": {
        "maxExpectedFailures": 1,
    },
    "memory-constraint-combined": {
        "maxExpectedFailures": 1,
    },
    "health-checks-install": {
        "ignorePhonehomeFailures": True,
    },
}


def config_has_uki_marker(repo_root, name):
    """Return True if the config's test-selection.yaml lists the "uki" marker."""
    selection_file = (
        repo_root
        / "tests"
        / "e2e_tests"
        / "trident_configurations"
        / name
        / "test-selection.yaml"
    )
    try:
        with open(selection_file, "r") as f:
            selection = yaml.safe_load(f) or {}
    except FileNotFoundError:
        return False

    return "uki" in (selection.get("compatible") or [])


# PCR 7 (secure-boot-policy) cannot be used to seal encryption for a UKI target
# OS when Trident itself runs inside a container: Secure Boot measures the
# host's boot chain, not the container's, so the sealed policy would never
# reproduce. Trident rejects this combination during dynamic validation
# (crates/trident/src/subsystems/storage/encryption.rs). Match that constraint
# here so such configs are not scheduled on the container runtime.
PCR7_ALIASES = {"secure-boot-policy", 7, "7"}


def config_needs_pcr7_for_encryption(repo_root, name):
    """Return True if the config encrypts volumes sealed to PCR 7."""
    config_file = (
        repo_root
        / "tests"
        / "e2e_tests"
        / "trident_configurations"
        / name
        / "trident-config.yaml"
    )
    try:
        with open(config_file, "r") as f:
            config = yaml.safe_load(f) or {}
    except FileNotFoundError:
        return False

    encryption = (config.get("storage") or {}).get("encryption")
    if not encryption:
        return False
    pcrs = encryption.get("pcrs") or []
    return any(pcr in PCR7_ALIASES for pcr in pcrs)


def config_is_runtime_incompatible(repo_root, name, runtime):
    """Return True if name must not run on the given Trident runtime."""
    if runtime == "container":
        # UKI + PCR-7-sealed encryption cannot install under a containerized
        # Trident (see PCR7_ALIASES note above).
        return config_has_uki_marker(repo_root, name) and (
            config_needs_pcr7_for_encryption(repo_root, name)
        )
    return False


def main():
    repo_root = Path(__file__).parent.parent.parent.parent
    target_configurations_yaml = (
        Path("tests") / "e2e_tests" / "target-configurations.yaml"
    )
    input_file = repo_root / target_configurations_yaml

    with open(input_file, "r") as f:
        data = yaml.safe_load(f)

    # Rename hardware types
    hw_renames = {
        "bareMetal": "bm",
        "virtualMachine": "vm",
    }

    # Rename pipelines to ring names
    pl_renames = {
        "weekly": "full-validation",
        "daily": "pre",
        "post_merge": "ci",
        "pullrequest": "pr-e2e",
    }

    # Pipeline ring order from lowest to highest
    pl_order = ["pr-e2e", "ci", "pre", "full-validation"]

    inverted = {}

    # Read the data
    for hw, rts in data.items():
        for rt, pls in rts.items():
            for pl, names in pls.items():
                for name in names:
                    # Apply renames
                    hw_rename = hw_renames.get(hw, hw)
                    pl_rename = pl_renames.get(pl)

                    if pl_rename is None:
                        if pl != "validation":
                            print(
                                f"Warning: Unknown pipeline type '{pl}' for scenario '{name}', hardware '{hw}', runtime '{rt}'. Skipping.",
                                file=sys.stderr,
                            )
                        continue

                    if name not in ALLOWED_CONFIGS:
                        continue
                    if hw_rename not in ALLOWED_HARDWARES:
                        continue
                    if rt not in ALLOWED_RUNTIMES:
                        continue
                    if config_is_runtime_incompatible(repo_root, name, rt):
                        continue

                    # Build inverted structure
                    hw_cfg = inverted.setdefault(name, {}).setdefault(hw_rename, {})
                    rt_cfg = hw_cfg.setdefault(rt, [])
                    rt_cfg.append(pl_rename)

    # For each scenario, hardware, and runtime, keep only the earliest pipeline ring
    for name, hws in inverted.items():
        for hw, rts in hws.items():
            for rt, pls in rts.items():
                # Only keep the earliest ring
                rts[rt] = min(pls, key=lambda x: pl_order.index(x))

    # Apply special settings
    for name, settings in SPECIAL_SETTINGS.items():
        if name not in inverted:
            continue
        for k, v in settings.items():
            inverted[name][k] = v

    # Set isUki for configurations whose test selection declares the "uki"
    # marker. This mirrors the pytest `isUki` fixture (uki in compatible) and
    # drives the expected TPM2 policy in the encryption validation.
    for name in inverted:
        if config_has_uki_marker(repo_root, name):
            inverted[name]["isUki"] = True

    # Re-sort configs by name
    inverted = dict(sorted(inverted.items()))

    output_yaml_file = Path(__file__).parent / "configurations" / "configurations.yaml"

    formatted_header = header.format(
        str(target_configurations_yaml), ", ".join(pl_order)
    )

    with open(output_yaml_file, "w") as f:
        f.write(formatted_header)
        f.write("\n")
        yaml.dump(inverted, f, sort_keys=False)
    print(f"Wrote inverted test configurations to {output_yaml_file}", file=sys.stderr)


if __name__ == "__main__":
    main()
