#!/usr/bin/env python3

# Invert the target-configurations.yaml file to produce a configurations.yaml file
# that lists, for each test configuration, the lowest pipeline ring it should be run in.

import sys
import yaml

from pathlib import Path

header = """\
# This file is autogenerated by invert.py from: {0}
# Do not edit this file directly.
#
# The file is structured as:
#
# ```yaml
# <config_name>:
#   <hardware_type>:
#     <runtime>: <lowest_pipeline_ring>
# ```
#
# Where:
# - <config_name> is the name of the test configuration.
# - <hardware_type> is either "bm" (bare metal) or "vm" (virtual machine).
# - <runtime> is either "host" or "container".
# - <lowest_pipeline_ring> is the first test ring where this scenario should be run.
#
# The pipeline rings are ordered as follows (from earliest to latest in the validation process):
# {1}
#
# A scenario marked to run in a given ring will also run in all later rings.
# For example, if a scenario is marked as "pre", it will run in the "pre" ring and all higher rings
# ("full-validation").
# Scenarios not listed in this file will not be run in any ring.
"""


def main():
    repo_root = Path(__file__).parent.parent.parent.parent
    target_configurations_yaml = (
        Path("tests") / "e2e_tests" / "target-configurations.yaml"
    )
    input_file = repo_root / target_configurations_yaml

    with open(input_file, "r") as f:
        data = yaml.safe_load(f)

    # Rename hardware types
    hw_renames = {
        "bareMetal": "bm",
        "virtualMachine": "vm",
    }

    # Rename pipelines to ring names
    pl_renames = {
        "weekly": "full-validation",
        "daily": "pre",
        "post_merge": "ci",
        "pullrequest": "pr-e2e",
    }

    # Pipeline ring order from lowest to highest
    pl_order = ["pr-e2e", "ci", "pre", "full-validation"]

    inverted = {}

    # Read the data
    for hw, rts in data.items():
        for rt, pls in rts.items():
            for pl, names in pls.items():
                for name in names:
                    # Apply renames
                    hw_rename = hw_renames.get(hw, hw)
                    pl_rename = pl_renames.get(pl)

                    if pl_rename is None:
                        print(
                            f"Warning: Unknown pipeline type '{pl}' for scenario '{name}', hardware '{hw}', runtime '{rt}'. Skipping.",
                            file=sys.stderr,
                        )
                        continue

                    # Build inverted structure
                    hw_cfg = inverted.setdefault(name, {}).setdefault(hw_rename, {})
                    rt_cfg = hw_cfg.setdefault(rt, [])
                    rt_cfg.append(pl_rename)

    # For each scenario, hardware, and runtime, keep only the earliest pipeline ring
    for name, hws in inverted.items():
        for hw, rts in hws.items():
            for rt, pls in rts.items():
                # Only keep the earliest ring
                rts[rt] = min(pls, key=lambda x: pl_order.index(x))

    output_yaml_file = Path(__file__).parent / "configurations" / "configurations.yaml"

    formatted_header = header.format(
        str(target_configurations_yaml), ", ".join(pl_order)
    )

    with open(output_yaml_file, "w") as f:
        f.write(formatted_header)
        f.write("\n")
        yaml.dump(inverted, f)
    print(f"Wrote inverted test configurations to {output_yaml_file}", file=sys.stderr)


if __name__ == "__main__":
    main()
