core:
  phonehome: http://<SOME_IP>:<SOME_PORT>

network-provision:
  # This is just netplan
  ethernets:
    vmeths:
      match:
        name: enp*
      dhcp4: false
      addresses: [192.168.242.50/24]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.242.1
      nameservers:
        addresses: [192.168.242.1]

storage:
  disks:
    - id: disk0
      device: "/dev/disk/by-path/pci-0000:00:1f.2-ata-1.0"
      partition-table-type: gpt
      partitions:
        - id: part0
          type: esp
          size: 1G
          label: boot
        - id: part1
          type: root-a
          size: 8G
          label: A
        - id: part2
          type: root-b
          size: 8G
          label: B
  mount-points:
    - path: /boot/efi
      target-id: part0
      filesystem: vfat
      options: [defaults]
    - path: /
      target-id: root
      filesystem: ext4
      options: [defaults]

imaging:
  images:
    - url: "file:///boot.raw.zst"
      sha256: b789802a93269486dc070faad41dc4d3bf0c5d018d3dea772917cf457a7f3115
      format: raw-zstd
      target-id: part0
    - url: "file:///rootfs.raw.zst"
      sha256: 8c11d8fe3a99d360f204e789d426ed70aaf4bf72163c8f4476a31fcf894601e6
      format: raw-zstd
      target-id: root
  overlays:
  ab-update:
    volume-pairs:
      - id: root
        volume-a-id: part1
        volume-b-id: part2


network:
  # This is just netplan
  ethernets:
    vmeths:
      match:
        name: enp*
      dhcp4: true
