parameters:
  - name: isoHttpdServerIp
    type: string
    default: "10.248.0.4"

  - name: oamIp
    type: string
    default: "10.8.4.70"

  - name: sshKeyFile
    type: string

  - name: interfaceForOamIp
    type: string
    default: "eno8303"

  - name: tridentConfigFile
    type: string

steps:
  - bash: |
      set -xe

      # Add poetry to PATH.
      export PATH="$HOME/.local/bin:$PATH"

      ls -l

      # Run script to update the trident.yaml file
      python3 ./.pipelines/templates/stages/deployment_testing/baremetal/update_host_config.py \
            --trident-yaml ${{ parameters.tridentConfigFile }} \
            --iso-httpd-ip ${{ parameters.isoHttpdServerIp }} \
            --oam-ip ${{ parameters.oamIp }} \
            --ssh-pub-key ${{ parameters.sshKeyFile }}.pub  \
            --interface-name ${{ parameters.interfaceForOamIp }}
      cat ${{ parameters.tridentConfigFile }}
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    displayName: "Update trident.yaml to reflect the OAM IP, HTTP server and SSH Key Details"

  - bash: |
      set -xe

      pwd
      ls -l

      mkdir -p ./bin

      # Rebuilding the trident binary 
      make bin/trident
      ls -ltr
      ls -ltr ./bin
      ./bin/trident --help

      # Run validate against the tridentConfigFile
      ./bin/trident validate --config ${{ parameters.tridentConfigFile }}
    displayName: "Validate the modified HostConfig by running trident validate"
