parameters:
  - name: baseimgBuildType
    displayName: Base Image build type
    type: string
    values:
      - dev
      - preview
      - release
    default: "release"

  - name: baseImagePipelineBuildId
    displayName: "Build Id of the pipeline run, default will select latest successful run from pipeline 2116 ([AMD64-6-OneBranch]-Prod-BuildImages) with tag 3.0-preview"
    type: string
    default: "latestFromBranch"

  - name: baseimgAzlVersion
    displayName: Base Image AZL version
    type: string
    default: "3.0"

  - name: micBuildType
    displayName: MIC Build Type
    type: string
    values:
    - dev
    - preview
    - release
    default: release

  - name: micVersion
    displayName: MIC Version
    type: string
    default: "*.*.*"

stages:
- stage: TridentTestImg_azl_installer
  displayName: Build azl-installer
  dependsOn:
    - GetTridentBinaries_rpms
    - BuildTridentContainerImage

  jobs:
  - job: BuildTridentTestImg
    displayName: Build
    timeoutInMinutes: 20
    pool:
      type: linux

    variables:
      ob_outputDirectory: $(Pipeline.Workspace)/s/test-images/output
      ob_artifactBaseName: azl-installer

    steps:
    - checkout: test-images
      fetchDepth: 1
      path: s/test-images

    - template: ../common_tasks/avoid-pypi-usage.yml

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: current
        artifactName: trident-binaries
        targetPath: "$(Build.ArtifactStagingDirectory)/trident"
      displayName: Download Trident RPMs

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: current
        artifactName: "trident-docker-image"
        patterns: "**/trident-container.tar.gz"
        targetPath: "$(Build.ArtifactStagingDirectory)/trident-docker-image"
      displayName: Download trident docker image

    - script: |
        sudo tdnf install -y squashfs-tools lsof
      displayName: Ensure mksquashfs

    - script: |
        set -eux
        docker \
            load \
            --input $(Build.ArtifactStagingDirectory)/trident-docker-image/trident-container.tar.gz

        ls -l $(Pipeline.Workspace)/s/test-images/platform-integration-images/azl-installer/mos/files
        cat $(Pipeline.Workspace)/s/test-images/platform-integration-images/azl-installer/mos/files/default-trident-config.yaml

        docker \
            run \
            -v $(Pipeline.Workspace)/s/test-images/platform-integration-images/azl-installer/mos/files:/etc/trident_config \
            trident/trident:latest \
            validate /etc/trident_config/default-trident-config.yaml

      displayName: "Validate usb-iso trident configuration."
      # There is a bit of chicken and egg related to trident and test-images.  To minimize this, use
      # continueOnError to make note of the usb-iso config error, but do not break the pipeline.  In
      # future, we should move the usb-iso code to the trident repo and then we can remove this.
      continueOnError: true

    - template: ../common_tasks/find-base-image-version.yml
      parameters:
        baseimgBuildType: ${{ parameters.baseimgBuildType }}
        baseImagePipelineBuildId: ${{ parameters.baseImagePipelineBuildId }}

    - template: .pipelines/templates/trident-testimg-template.yml@test-images
      parameters:        
        target: build/azl-installer.iso
        outputDirectory: ${{ variables.ob_outputDirectory }}
        testImagesRepo: test-images
        micBuildType: ${{ parameters.micBuildType }}
        micVersion: ${{ parameters.micVersion }}
        baseimgBuildType: ${{ parameters.baseimgBuildType }}
        baseimgVersion: $(baseimgVersion)
        baseimgAzureLinuxVersion: ${{ parameters.baseimgAzlVersion }}
        downloadTrident: false
    
- stage: Test_azl_installer
  displayName: Test azl-installer
  dependsOn:
    - TridentTestImg_azl_installer

  jobs:
  - job: BuildTridentTestImg
    displayName: Validate
    timeoutInMinutes: 15
    pool:
      type: linux
      name: maritimus-ado-1es-pool-ubuntu2404-amd64
      hostArchitecture: amd64

    variables:
      ob_outputDirectory: $(Pipeline.Workspace)/azl-installer-test
      ob_artifactBaseName: azl-installer-test

    steps:
    - template: validate-usb-iso.yml
   