package scenario

import (
	"os"
	"path/filepath"

	"github.com/microsoft/storm"
	"github.com/sirupsen/logrus"
)

// publishLogs publishes log and metrics files as artifacts for ADO collection.
// This consolidates the display-logs and metrics collection that was previously
// done as separate YAML pipeline steps.
func (s *TridentE2EScenario) publishLogs(tc storm.TestCase) error {
	// Publish logstream file
	if s.args.LogstreamFile != "" {
		publishFileIfExists(tc, s.args.LogstreamFile)
	}

	// Publish tracestream (metrics) file from clean install
	traceStreamFile := s.args.TracestreamFile
	if traceStreamFile == "" {
		traceStreamFile = "trident-clean-install-metrics.jsonl"
	}
	publishFileIfExists(tc, traceStreamFile)

	// Publish boot metrics file
	publishFileIfExists(tc, bootMetricsFile)

	// Publish AB update metrics files (generated by netlisten during AB updates)
	matches, err := filepath.Glob("metrics-*.jsonl")
	if err == nil {
		for _, m := range matches {
			publishFileIfExists(tc, m)
		}
	}

	return nil
}

// publishFileIfExists publishes a file as an artifact if it exists.
func publishFileIfExists(tc storm.TestCase, filePath string) {
	if _, err := os.Stat(filePath); err != nil {
		logrus.Debugf("Skipping artifact %s: %v", filePath, err)
		return
	}

	artifactName := filepath.Base(filePath)
	tc.ArtifactBroker().PublishLogFile(artifactName, filePath)
	logrus.Infof("Published artifact: %s", artifactName)
}
