name: gh-pages-docs

on:
  workflow_dispatch:

  release:
    types: [published]
  # push:
  #   branches: [main]
  #   path:
  #     - 'website/*'
  #     - 'docs/*'
  #     - '.github/workflows/deploy-website.yml'
  # workflow_dispatch:
  # merge_group:
  #   types: [checks_requested]

jobs:
  gh-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Build website
        run: |
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./website/build