name: gh-pages-docs

on:
  # temp trigger for push
  push:
    branches:
      - user/bfjelds/docusaurus-poc

  # Manual trigger
  workflow_dispatch:

  # Trigger on release
  release:
    types: [published]

jobs:
  gh-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Build website
        run: |
          npm install --force
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./website/build